### ISSUE TITLE
Click to move does not work

### ISSUE THREAD

**Issue by SSSSSSSSSSSera** [vinegarhq/sober#10]
Click to move does not work

https://github.com/user-attachments/assets/2d499508-a68d-4acb-b9f0-545048e9c1b9

**Comment by SSSSSSSSSSSera** [comment]
wait for some reason i just realized
if i rapidly press right click and then left click it suddenly works????? no idea why but its still not properly functioning

**Comment by apprehensions** [comment]
Right click is the preferred method for it.
