### ISSUE TITLE
Crashing in "Pilgrammed"

### ISSUE THREAD

**Issue by sunglocto** [vinegarhq/sober#102]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The game crashes a few seconds after loading or immediately.

https://github.com/user-attachments/assets/e7dfff4c-e2d8-4674-a38e-ed1e91c8f4d8

### Roblox Experience link

https://www.roblox.com/games/6735572261/

**Comment by PanIntegralus** [comment]
Maybe an issue on your end

![image](https://github.com/user-attachments/assets/e42320eb-6a78-48cb-aacb-f773388f35cd)

**Comment by sunglocto** [comment]
Doesn't happen anymore in the latest update
