### ISSUE TITLE
Crashing due to glibc error

### ISSUE THREAD

**Issue by ViseTineP3** [vinegarhq/sober#103]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox randomly freeze and I can only close it killing the process.
There is no error in the log, but when running from the command line I get:

`Fatal glibc error: pthread_mutex_lock.c:172 (___pthread_mutex_lock): assertion failed: PTHREAD_MUTEX_TYPE (mutex) == PTHREAD_MUTEX_ERRORCHECK_NP`

Some system info:
```
System:
  Kernel: 6.10.4-gentoo arch: x86_64 bits: 64 compiler: clang v: 18.1.8
  Desktop: KDE Plasma v: 6.1.4 Distro: Gentoo Base System release 2.15
CPU:
  Info: quad core model: Intel Xeon E31270 bits: 64 type: MT MCP
    arch: Sandy Bridge rev: 7 cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 3517 high: 3533 min/max: 1600/3800 cores: 1: 3492
    2: 3513 3: 3527 4: 3527 5: 3497 6: 3527 7: 3533 8: 3527 bogomips: 54275
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: AMD Polaris 20 XL [Radeon RX 580 2048SP] driver: amdgpu v: kernel
    arch: GCN-4 bus-ID: 01:00.0 temp: 56.0 C
  Display: unspecified server: X.Org v: 24.1.2 with: Xwayland v: 24.1.2
    driver: X: loaded: amdgpu unloaded: modesetting dri: radeonsi gpu: amdgpu
    s-res: 1366x768 resolution: 1366x768
  API: EGL v: 1.5 drivers: radeonsi,swrast platforms:
    active: gbm,x11,surfaceless,device inactive: wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.0-rc4 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon RX 580 2048SP (radeonsi polaris10
    LLVM 18.1.8 DRM 3.57 6.10.4-gentoo)
```

**Comment by ViseTineP3** [comment]
Sometimes I get this error too:

> Fatal glibc error: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)

**Comment by Amgsdfyhadfgybi** [comment]
has anyone even found a fix for this yet

**Comment by Thanatoslayer6** [comment]
> has anyone even found a fix for this yet

I tried one of the recent apk versions of Roblox, and it worked, specifically the August 15 package; don't use the latest one.

**Comment by tunis4** [comment]
fixed in latest update
