### ISSUE TITLE
Cursor is locked is some games

### ISSUE THREAD

**Issue by koeqaife** [vinegarhq/sober#109]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

In some games like 3008 I can't eat food etc because the cursor is always centered

### Roblox Experience link

https://www.roblox.com/games/2768379856

**Comment by ryand56** [comment]
Did you try pressing F1?

**Comment by koeqaife** [comment]
no, and its working!! tysm
