### ISSUE TITLE
cannot install sober

### ISSUE THREAD

**Issue by PyczekFromPoland** [vinegarhq/sober#110]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i've tried to install sober with flatpak (ofc) and the first 7 packages installed, but when was the sober turn i've got and issue (didn't take a screenshot), so then i've tried again and this was the error that i've got
![image](https://github.com/user-attachments/assets/fa109471-c45b-4868-b8ac-0ff08acc81e2)

**Comment by apprehensions** [comment]
Can you run `flatpak remote-ls | grep sober`?

**Comment by apprehensions** [comment]
Also, please try again.

**Comment by PyczekFromPoland** [comment]
okay, i've tried the second time, and it worked! but it doesn't find my apk files
![image](https://github.com/user-attachments/assets/fd086203-d1f8-4624-b0ff-e83735c7a170)

**Comment by km9l** [comment]
> okay, i've tried the second time, and it worked! but it doesn't find my apk files ![image](https://private-user-images.githubusercontent.com/169494703/358411545-fd086203-d1f8-4624-b0ff-e83735c7a170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDc5MDYsIm5iZiI6MTcyMzgwNzYwNiwicGF0aCI6Ii8xNjk0OTQ3MDMvMzU4NDExNTQ1LWZkMDg2MjAzLWQxZjgtNDYyNC1iMGZmLWU4MzczNWM3YTE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMTI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2UxMGE2ZmNhNWEyN2E4MjVkOWE1YTVkNjU0YjY5ODgyOGVmMTBjYWM2NTgxYjAzZTk5ZGYwM2I3NjUzMGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vAMU0gqo5tcJXGRqgpxEM5IKhWfzjEsB2RN0JrOX694)

do you have any filepicker portal for xdg-desktop-portal
install `xdg-desktop-portal-gtk` if unsure

**Comment by ParijatBasak** [comment]
> Can you run `flatpak remote-ls | grep sober`?

Tried this but did nothing. Instead gives a new error 

![Image](https://github.com/user-attachments/assets/7a0da04d-d61a-4085-86d7-3fd3e8da18ce)

**Comment by CR7-SPEC** [comment]
a solution please
