### ISSUE TITLE
file picker doesn't recognize (?) my apk files

### ISSUE THREAD

**Issue by PyczekFromPoland** [vinegarhq/sober#112]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so, i've installed sober and i've put all my apks in my home directory, and the file picker doesn't recognize them
![image](https://github.com/user-attachments/assets/0ae79584-df23-4480-ac6d-a0a25dfb8092)
(and yes, i have xdg-desktop-portal-gtk installed)

**Comment by km9l** [comment]
> (and yes, i have xdg-desktop-portal-gtk installed)

clearly its not using it
what DE or window manager is this? `echo $XDG_CURRENT_DESKTOP`?

**Comment by PyczekFromPoland** [comment]
> echo $XDG_CURRENT_DESKTOP
![image](https://github.com/user-attachments/assets/63cb54ba-0f88-4735-83ad-595f4295f543)
im using dwm

**Comment by trustytrojan** [comment]
same issue, i am using swaywm. `XDG_CURRENT_DESKTOP` isn't set for me either, do we need to set it to something?

**Comment by PyczekFromPoland** [comment]
> fixed this using `flatpak document-export -a org.vinegarhq.Sober <apkfile>`

it just shows this 
![image](https://github.com/user-attachments/assets/edf0488a-98ea-478c-8c07-c99fcb39ac7d)

**Comment by km9l** [comment]
> im using dwm

`systemctl status --user xdg-desktop-portal*`?

**Comment by PyczekFromPoland** [comment]
> systemctl status --user xdg-desktop-portal*

![image](https://github.com/user-attachments/assets/d74e5a9f-703f-498d-bfe5-1883fc47979f)

**Comment by km9l** [comment]
> > systemctl status --user xdg-desktop-portal*
> 
> ![image](https://private-user-images.githubusercontent.com/169494703/358667392-d74e5a9f-703f-498d-bfe5-1883fc47979f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzA3MjQsIm5iZiI6MTcyMzgzMDQyNCwicGF0aCI6Ii8xNjk0OTQ3MDMvMzU4NjY3MzkyLWQ3NGU1YTlmLTcwM2YtNDk4ZC1iZmU1LTE4ODNmYzQ3OTc5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxNzQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDQyYmM1NzkxM2E0Yzg3OGU2Y2Q4ZTZmNTFkZDZmNmUwN2YxZTA2NGM3ZGQ2YTgwZGZlNGE5M2U3ZGYxYzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bASOAzwEL9Z7Fp8JpL6JvHeIziMdisNS0YDYQGpTKU4)

its not running xdg-desktop-portal-gtk
add this config to `~/.config/xdg-desktop-portal/portals.conf`
```
[preferred]
default=gtk
```
`systemctl restart --user xdg-desktop-portal`

**Comment by PyczekFromPoland** [comment]
alr everything works now, THANK YOU!!!

**Comment by trustytrojan** [comment]
> > fixed this using `flatpak document-export -a org.vinegarhq.Sober <apkfile>`
> 
> it just shows this ![image](https://private-user-images.githubusercontent.com/169494703/358635331-edf0488a-98ea-478c-8c07-c99fcb39ac7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NDExMzEsIm5iZiI6MTcyMzg0MDgzMSwicGF0aCI6Ii8xNjk0OTQ3MDMvMzU4NjM1MzMxLWVkZjA0ODhhLTk4ZWEtNDc4Yy04YzA3LWM5OWZjYjM5YWM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQyMDQwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjdhZDM3ZWU5NzlkYjY3YWI3Mjk4YzcxMGVhNzVmNmZmN2E1MmFlNDAwYWI3YzYzNDljYTI1NGNhZDZiZDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BD8c_Tut4I3Q8FcrdDBpJB_i3ZaIJpMeJZ6qvz8Le1M)

what i forgot to mention is that the output of that command is the path where sober can read the file.
