### ISSUE TITLE
Impossible to join specific servers

### ISSUE THREAD

**Issue by aeroglass7** [vinegarhq/sober#116]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Can join games, but when I click "servers" on the game page it says no one is online, no matter how many people are. Used to work before I updated Sober.

**Comment by unexp** [comment]
while this isn't fixed you can join servers through the website as a workaround

**Comment by tunis4** [comment]
please check if this still happens in latest update

**Comment by aeroglass7** [comment]
it does not. YAY!
