### ISSUE TITLE
Flatpak install/update error

### ISSUE THREAD

**Issue by JimBimBum** [vinegarhq/sober#12]
Aborted due to failure (While trying to checkout 09f383dc5b5e0dd62fcffeed1ca5c2d194ed3a80f281d980329b7407b0c0461d into /home/user/.local/share/flatpak/app/org.vinegarhq.Sober/x86_64/master/.09f383dc5b5e0dd62fcffeed1ca5c2d194ed3a80f281d980329b7407b0c0461d-PnDAqW: No such metadata object 22cb03a389137b0a49d192f42843a45a508abeae3028e61b6427f23c2a254d5b.dirtree)

when i had it installed it said the update date was older than the one already installed but now that i uninstalled it won't install.

**Comment by Dekomoro** [comment]
seems legit

**Comment by BrycensRanch** [comment]
config issue smh

**Comment by Dekomoro** [comment]
tbh tho, An updates being built which is why you are having this issue. This will be resolved automatically.

**Comment by apprehensions** [comment]
Fixed
