### ISSUE TITLE
Steam Deck Aspect Ratio

### ISSUE THREAD

**Issue by agedje** [vinegarhq/sober#124]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Seems like roblox on a steam deck launches in a strange aspect ratio / screen resolution (what causes these big black stripes to appear on the edges of the screen)
![image0](https://github.com/user-attachments/assets/5e9d04f1-81ac-444d-aad0-ba3f763335db)

### Describe the Solution you'd Like

A way to change aspect ratio

### Describe Alternatives you've considered

Tried to change resolution of sober in steam but roblox seems to ignore that, so i haven't found any alternatives

**Comment by ryand56** [comment]
Related to #86

**Comment by agedje** [comment]
> Related to #86

thanks!
