### ISSUE TITLE
Sober does not shut down Roblox properly upon being closed

### ISSUE THREAD

**Issue by Macosaro** [vinegarhq/sober#125]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Once Sober is closed using SIGTERM (be it the exit button or ALT + F4/ALT + Q/whatever the user has bound closing the window to), such issues happen:
1. Player is not properly disconnected from the server, causing them to remain on it for ~10 seconds before getting kicked
2. Any changed user settings are not saved

**Comment by tunis4** [comment]
fixed in latest update
