### ISSUE TITLE
Failed to retrieve .flatpak using either method

### ISSUE THREAD

**Issue by DOBsby** [vinegarhq/sober#130]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I checked all three pages of issues (titles only) and didn't see anything like this. I tried both install methods and they can't be retrieved it seems.

**god@raspberry:~/Downloads $ flatpak install sober.flatpakref
The remote 'sober', referred to by 'org.vinegarhq.Sober' at location https://sober.vinegarhq.org/repo/ contains additional applications.
Should the remote be kept for future installations? [Y/n]: Y
error: No such ref 'app/org.vinegarhq.Sober/i386/master' in remote sober**

_god@raspberry:~/Downloads $ flatpak install --user https://sober.vinegarhq.org/sober.flatpakref
error: No such ref 'app/org.vinegarhq.Sober/i386/master' in remote sober_

**Comment by apprehensions** [comment]
We only support x86_64.
