### ISSUE TITLE
Add GenericName to desktop entry

### ISSUE THREAD

**Issue by mak448a** [vinegarhq/sober#131]
![image](https://github.com/user-attachments/assets/aa854d78-2182-4c80-8a63-3df8f612d185)
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

The Sober desktop entry doesn't have a `GenericName=` description for viewing under KDE Plasma.

### Describe the Solution you'd Like

Add the `GenericName=Roblox Player on Linux` to the desktop entry

### Describe Alternatives you've considered

Doing nothing with it.

### Additional context

![image](https://github.com/user-attachments/assets/6de914bd-a905-4e72-a57c-ed699ee5a56c)
Compared to a different app
![image](https://github.com/user-attachments/assets/2fb78575-f621-4144-b5d7-c710ab2fd937)

**Comment by Twig6943** [comment]
I second this

**Comment by tunis4** [comment]
added in update
