### ISSUE TITLE
BOMBLINE [Alpha] crashes after a few minutes of playtime

### ISSUE THREAD

**Issue by tristann21** [vinegarhq/sober#132]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This seems to be the only game I'm having issues with Sober, every other game runs great.

Running steam deck on bazzite

[systeminfo.txt](https://github.com/user-attachments/files/16669018/systeminfo.txt)

[terminal output.txt](https://github.com/user-attachments/files/16668994/terminal.output.txt)

[sober logs.log](https://github.com/user-attachments/files/16669013/sober.logs.log)

### Roblox Experience link

https://www.roblox.com/games/10469988463/BOMBLINE-Alpha

**Comment by tunis4** [comment]
fixed in latest update
