### ISSUE TITLE
text loads slowly

### ISSUE THREAD

**Issue by Rain-Gayming** [vinegarhq/sober#135]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When typing the text generates REALLY slow with about a 3 second delay
it makes typing bearly doable

**Comment by KindaFunnyYT** [comment]
I just move my mouse after typing and the text loads faster. Weird but it works.

**Comment by tunis4** [comment]
fixed in newest version
