### ISSUE TITLE
Sober doesnt want to turn on.

### ISSUE THREAD

**Issue by FilipoDeveloperMan** [vinegarhq/sober#137]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After installing sober the proper way using flatpak, i go to launch it and it DOESNT work... It just stays in my taskbar doing nothing (arch user btw). i tried launching it with the flatpak run command but it just dumps this error:

$ flatpak run org.vinegarhq.Sober
Roblox installation is required, starting onboarding flow UI...
libEGL warning: MESA-LOADER: failed to open simpledrm: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/simpledrm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)

MESA: error: zink: could not create swapchain
$ flatpak run org.vinegarhq.Sober
Roblox installation is required, starting onboarding flow UI...
libEGL warning: MESA-LOADER: failed to open simpledrm: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/simpledrm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)

MESA: error: zink: could not create swapchain

Any help is wanted...

**Comment by apprehensions** [comment]
did you check if the power is connected and the power switch is on

**Comment by FilipoDeveloperMan** [comment]
I need this fix urgently please dont joke!!!

**Comment by FilipoDeveloperMan** [comment]
;-;

**Comment by FilipoDeveloperMan** [comment]
I've figured it out, nvidia drivers dont support simpledrm, will investigate and find solution to issue

**Comment by Cristiandis** [comment]
> I've figured it out, nvidia drivers dont support simpledrm, will investigate and find solution to issue

you can try adding the kernel parameters `nvidia_drm.fbdev=1` and `nvidia_drm.modeset=1` if you're on 545 and later to disable simpledrm

**Comment by FilipoDeveloperMan** [comment]
how do i do that? (im on 560)

**Comment by FilipoDeveloperMan** [comment]
FOUND SOLUTION!!!! solution for me was to install mesa drivers...
