### ISSUE TITLE
game specific bug (PHIGHTING!) - unable to chat while in a match

### ISSUE THREAD

**Issue by teamkill3d** [vinegarhq/sober#14]
i've discovered a weird game specific bug tangentially related to sober

when playing phighting, if you are in control of your character, you are unable to use the chat menu

this only happens when you're in control of your character, because when you're in a place where you can't do anything with your character (i.e. flipside map voting cutscene and phighter select menu), you are able to use the chat menu normally

please let me know if i should bring this bug up to boggio instead of vinegarhq

game link: [https://www.roblox.com/games/7138009149/PHIGHTING-ALPHA](https://www.roblox.com/games/7138009149/PHIGHTING-ALPHA)

**Comment by teamkill3d** [comment]
after further testing, i have found out that chatting in crossroads is possible, but chatting in the game lobby itself is not

**Comment by sunglocto** [comment]
I am experiencing this as well

**Comment by teamkill3d** [comment]
the bug appears to be fixed
