### ISSUE TITLE
Invalid Bundle Version

### ISSUE THREAD

**Issue by ScarlettPPC** [vinegarhq/sober#141]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Just installed Sober using Flatpak and the newest version of the Roblox APK bundle from APKMirror, making sure it's the universal variant. The app launches fine but does not accept any of my bundles. It just says "The version of the bundle you provided isn't supported by this version of Sober." I tried the last 3 versions as well but to no avail. Everything, including Sober is on the latest version. My distro is Void Linux.

**Comment by Anothuoretta** [comment]
same issue linux mint

**Comment by MrGenie151** [comment]
Same Issue

**Comment by cappynine98** [comment]
same issue, i use Pop!_OS.

**Comment by cappynine98** [comment]
I found the fix but it's not sober's fault. You press on the uh file thing and You go to the extracted folder and hold ctrl and only select the apk files.

**Comment by ScarlettPPC** [comment]
I tried that as well, but it gave me the exact same error.

**Comment by GuilianCD** [comment]
Same issue, endeavouros. Sober version is 0.0.0-7a34212, tried roblox apk versions 2.637.730, 2.635.590, and 2.639.688.

**Comment by KirbyHacks** [comment]
Same issue, Debian 12.

**Comment by xCxsmix598** [comment]
you need the roblox version 2.638.610

https://www.apkmirror.com/apk/roblox-corporation/roblox/roblox-2-638-610-release/roblox-2-638-610-android-apk-download/download/?key=8256b34696f8c167b3a8216c88e95dc08c4e7240

**Comment by GuilianCD** [comment]
> you need the roblox version 2.638.610
> 
> https://www.apkmirror.com/apk/roblox-corporation/roblox/roblox-2-638-610-release/roblox-2-638-610-android-apk-download/download/?key=8256b34696f8c167b3a8216c88e95dc08c4e7240
> 
> this worked for me, but idk... it may vary

it worked like a charm, thanks !

**Comment by xCxsmix598** [comment]
> > you need the roblox version 2.638.610
> > https://www.apkmirror.com/apk/roblox-corporation/roblox/roblox-2-638-610-release/roblox-2-638-610-android-apk-download/download/?key=8256b34696f8c167b3a8216c88e95dc08c4e7240
> > this worked for me, but idk... it may vary
> 
> it worked like a charm, thanks !

Man they really need to start telling us what particular Roblox version is supported by Sober's current build

**Comment by tunis4** [comment]
new sober update supports 639 now and we added the current supported version number to the gui
