### ISSUE TITLE
the list of private servers is not show servers

### ISSUE THREAD

**Issue by ZozyaBruh** [vinegarhq/sober#142]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot_20240823_030058](https://github.com/user-attachments/assets/f1cf09a8-3fa4-4805-82ca-a35d0bf63487)

I use Steam OS if it helps

**Comment by tunis4** [comment]
fixed in the update
