### ISSUE TITLE
Mouse lock in some games where it should be unlocked at that time

### ISSUE THREAD

**Issue by fernando433566** [vinegarhq/sober#144]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've played two games in the last few days that have had this error being: [PHIGHTING! [ALPHA]](https://www.roblox.com/es/games/7138009149/PHIGHTING-ALPHA) and [Midnight Burger.](https://www.roblox.com/es/games/17816926167/Midnight-Burger-HORROR) In both games there is a point where it is necessary to move the mouse to progress, but the mouse does not unlock (even dough it shows the cursor again) and I doubt that it is a game error since I played those games with a friend (Windows) and those errors did not happen to him. also, you can't move the mouse outside the sober app for some reason

### Roblox Experience link

https://www.roblox.com/es/games/7138009149/PHIGHTING-ALPHA

**Comment by 4nexus5** [comment]
Literally went to report this and this is the first thing I see on the issues list. I have the exact same bug, happening in both Arsenal and Counter Blox. Not the games' issue, it is a Sober issue. Hoping update rolls out soon.

Besides this, the mouse in Arsenal keeps locking to the middle every half a second, I want to click a button but it is really hard as it constantly goes back to the middle, the only option is to use high DPI on the mouse and just repeat until the mouse doesn't go in the middle again.

**Comment by Dimitriyo** [comment]
https://github.com/vinegarhq/sober/issues/5
Try pressing F1, it unlocks your mouse

**Comment by fernando433566** [comment]
I tried it again and I think it has been solved
