### ISSUE TITLE
Roblox Studio Support ?

### ISSUE THREAD

**Issue by lemmings189** [vinegarhq/sober#145]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

No

### Describe the Solution you'd Like

Hello,
is there a way to use Roblox Studio with Sober ? I guess not because we cannot use it on Mobile. What is the best way then, outside of Sober ?

### Describe Alternatives you've considered

Vinegar or Wine with old Windows releases ?

**Comment by apprehensions** [comment]
Vinegar
