### ISSUE TITLE
[REQ] Make not focused to NOT controll camera

### ISSUE THREAD

**Issue by Vlad55432** [vinegarhq/sober#15]
When I'm alt tabing and moving mouse behind sober client, you can control camera. 
I want control camera only, when I'm focused on sober

https://github.com/user-attachments/assets/f551d0e8-3296-42d4-b00e-6a24f93fb2e0

**Comment by Vlad55432** [comment]
oh shucks, format unsuported

**Comment by apprehensions** [comment]
This is due to your desktop environment, it's automatically giving focus back to Sober.

Duplicate of #6

**Comment by Vlad55432** [comment]
oops
