### ISSUE TITLE
Weird mouse movement

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#151]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

for some reason the mouse cant leave the window idk why

**Comment by Dimitriyo** [comment]
https://github.com/vinegarhq/sober/issues/5
Try pressing F1, it unlocks your mouse

**Comment by Amgsdfyhadfgybi** [comment]
> #5 Try pressing F1, it unlocks your mouse

dawg thats not what i meant
