### ISSUE TITLE
Making the F1 Mouse lock/unlock feature more obvious to the user

### ISSUE THREAD

**Issue by Dimitriyo** [vinegarhq/sober#153]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

No, not a application problem, but the fact that the F1 mouse lock feature isn't listed on the website, and the README in this github. I have not checked the discord server, as I'm not aware of a link. Regardless, this feature should be made clear on the website's FAQ, this repo's README, and the App itself.

### Describe the Solution you'd Like

A clear and obvious notice of the F1 key's Mouse lock/unlock function on the App, the Website's FAQ, and this repo's README.

### Describe Alternatives you've considered

The alternative is to dig into the issues page, to which there have been multiple repeated issues with the same problem, 2 still open at the time or writing. This is simply too convoluted and complicated for your average user, who expects everything to work out of the box. 

Having this feature made obvious would enhance the user experience as well as the amount of open issues asking about the same problem.

**Comment by tunis4** [comment]
we already removed the f1 keybind, update sober

**Comment by marvin1099** [comment]
why did you remove it, i mean how do i unlock the mouse if i'm in first person and a store gui or something pops up. now i cant move the mouse on the store gui and i cant zoom out (so the mouse can move) since the gui is in the middle of the screen.

**Comment by LotEep** [comment]
This is a problem that Roblox has always had, no matter the operating system or client, the solution I use is to press esc to unlock your cursor, hover your mouse over the exit button of the menu or wherever you want to press, spam click and at the same time press esc to exit the esc menu

**Comment by marvin1099** [comment]
> This is a problem that Roblox has always had, no matter the operating system or client, the solution I use is to press esc to unlock your cursor, hover your mouse over the exit button of the menu or wherever you want to press, spam click and at the same time press esc to exit the esc menu

I mean that may be true (I don't know), but the f1 button was basically a solution, so I'm still not shure why they removed it.
