### ISSUE TITLE
Add support for not running as a flatpak

### ISSUE THREAD

**Issue by jfkgettingshot** [vinegarhq/sober#157]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Related to nvidia gpu issues

### Describe the Solution you'd Like

Being able to install via other methods and not have to deal with flatpak drivers

### Describe Alternatives you've considered

I actually cant think of anything

### Additional context

The flatpak nvidia drivers have caused nothing but pain causing GPU Not found issues.
this is not an issue with my computer as every other game works fine

**Comment by apprehensions** [comment]
No.

**Comment by jfkgettingshot** [comment]
> No.

Fix the issues with nvidia then

**Comment by apprehensions** [comment]
That is an issue introduced by Flathub: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/288
