### ISSUE TITLE
please add a question request

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#164]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

even if i already requested something like this, and that the discussions tab exists, discussions are dead as a fucking dodo

### Describe the Solution you'd Like

add a question request to the issues tab

### Describe Alternatives you've considered

discussions tab (it sucks)

**Comment by apprehensions** [comment]
https://github.com/vinegarhq/sober/discussions
