### ISSUE TITLE
Freeze & crash on Multitank Crew Combat 4

### ISSUE THREAD

**Issue by Username404-59** [vinegarhq/sober#18]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[robloxlogs.txt](https://github.com/user-attachments/files/16482629/robloxlogs.txt)

After a dozens of seconds to a few minutes, the game freezes and crashes, also leading KDE to apparently die and come back

Happens with both flatpak's default mesa and mesa-git

### Roblox Experience link

https://www.roblox.com/fr/games/9520328730/Multicrew-Tank-Combat-4

**Comment by apprehensions** [comment]
Provide the experience link, there is a place for it.

**Comment by Username404-59** [comment]
> Provide the experience link, there is a place for it.

Yeah my dumb brain skipped it

**Comment by tunis4** [comment]
assuming this was caused by highlight rendering, which has been fixed

**Comment by Username404-59** [comment]
nope, it's still happening

**Comment by Username404-59** [comment]
> are you on latest sober?

I was; reinstalled my whole OS and I somehow don't have this issue anymore

**Comment by Username404-59** [comment]
Doesn't happen anymore with latest sober + linux 6.11 🥳
