### ISSUE TITLE
Voice chat not working and not able to choose mic input

### ISSUE THREAD

**Issue by Lqnz** [vinegarhq/sober#195]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've seen some bug reports regarding about this issue and I just wanna make a bug report about this so that this issue will hopefully be fixed eventually. 

But I just wanna say that I can't choose my mic options / input on the game settings and whenever I want to unmute and talk, the players wouldn't hear me on their end but the game does detect my voice for some reason because the mic icon on the top of my head was moving but once again, players can't hear me in-game :(

**Comment by Naymmmm** [comment]
You cannot change your mic input due to it being the Android app, you must change your default input in your DE/Settings app.

This is not a Sober issue, therefore you should close with "notourbug"
