### ISSUE TITLE
error: Can't load uri https://sober.vinegarhq.org/sober.flatpakref: While fetching https://sober.vinegarhq.org/sober.flatpakref: [60] SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by FrostyyyDev** [vinegarhq/sober#197]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

ok, so this error pops up on my chromeOS (flex) running debian 10, and I wanted to know if there was a way to fix it. i've searched everywhere, but it seems that no one else has has this issue... please respond asap, my last issue got completely ignored

**Comment by foxbat44** [comment]
There is nothing you can do to fix this as a user. Also, Sober does not support Linux VMs running on ChromeOS.
