### ISSUE TITLE
add option to change resolution

### ISSUE THREAD

**Issue by unicornsandcandies** [vinegarhq/sober#209]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

My feature is related to an issue. When launching the game in gamescope, it doesn't respect the resolution set by steam. I have black bars on the left and right, no matter what I do 

### Describe the Solution you'd Like

My solution is a launcher option, to set resolution of the game window.

### Describe Alternatives you've considered

I tried launching it maximized and changing the resolution in game mode

### Additional context

I'm using bazzite os, fedora silverblue fork on steam deck OLED.

**Comment by tunis4** [comment]
did you try fullscreening sober by pressing f11
