### ISSUE TITLE
Shift lock camera glitch

### ISSUE THREAD

**Issue by Yaco-Taco** [vinegarhq/sober#212]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Activating shift lock will often cause the camera to snap to a different direction than it was facing with shift lock disabled. It doesn't happen every time, and I don't know what triggers it. But it happens often enough that fast paced obby games are unplayable sometimes. It happens regularly in flood escape 2.

edit: it doesn't seem to happen if I keep my cursor in the center of my screen while turning shiftlock on and off

This is the same issue from someone else on discord: 

https://github.com/user-attachments/assets/323fe662-91b0-4f81-8969-d6813763e69f

https://discord.com/channels/1069506340973707304/1279069764085354519

### Roblox Experience link

https://www.roblox.com/games/738339342/Flood-Escape-2

**Comment by HyperNfs** [comment]
I had the same problem when you turn off shift lock press f1 it should fix it

**Comment by Yaco-Taco** [comment]
> I had the same problem when you turn off shift lock press f1 it should fix it

I mean the mouse fixes itself almost immediately, but the camera has already jumped to a new direction by then

**Comment by tunis4** [comment]
probably fixed in the previous update
