### ISSUE TITLE
high ping

### ISSUE THREAD

**Issue by AceVR12** [vinegarhq/sober#217]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Though i get significantly more frames, the ping is 60+ higher than windows. For example, On windows i get 15 - 40 ping. On linux i get 75 - 120 ping. Can someone help me fix this?

**Comment by TanksNBoats** [comment]
From what I know, this isn't a sober issue, some things that could be of cause could be

- Being on a HDD rather than SSD
- Not updated Device Manager
- Other linux issues when it comes to device manager as they're incompatibilities everywhere, and might just be best to search up similar issues for fixes like in configs or installing/updating packages.

**Comment by trnahuman** [comment]
You might want to check this site for seeing issue it's bufferbloat https://www.waveform.com/tools/bufferbloat

**Comment by AceVR12** [comment]
> You might want to check this site for seeing issue it's bufferbloat https://www.waveform.com/tools/bufferbloat
M

Grade: c 
download: 351.1
upload: 372.4

**Comment by AceVR12** [comment]
> From what I know, this isn't a sober issue, some things that could be of cause could be
> 
> * Being on a HDD rather than SSD
> * Not updated Device Manager
> * Other linux issues when it comes to device manager as they're incompatibilities everywhere, and might just be best to search up similar issues for fixes like in configs or installing/updating packages.

I use a NVme (samsung 980 1tb)
2, i have nothing out of date
3: nobody uses sober that posts videos

**Comment by TanksNBoats** [comment]
I was talking about network manager, not sober

try putting IWD as your backend

**Comment by trnahuman** [comment]
> > You might want to check this site for seeing issue it's bufferbloat https://www.waveform.com/tools/bufferbloat
> M
> 
> Grade: c 
> download: 351.1
> upload: 372.4

The problem is obvious, you have a bufferbloat problem

**Comment by Naymmmm** [comment]
Either your WiFi sucks, you lack drivers, you are using an obsolete storage type or your kernel sucks.
