### ISSUE TITLE
Hard Freezing in Typical Colors 2

### ISSUE THREAD

**Issue by Vlad55432** [vinegarhq/sober#22]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Crashes every time, randomly
[2.636.0.626_20240803T203001Z_Player_4f71b_last.log](https://github.com/user-attachments/files/16482844/2.636.0.626_20240803T203001Z_Player_4f71b_last.log)
Fatal glibc error: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)
UPD: Nvidia issue & duplicate of https://github.com/vinegarhq/sober/issues/2, sry guys for reporting before rechecking
UPD2: OK, Maybe I should reopen this, because it became freezing. Idk why it happens honestly 
![зображення](https://github.com/user-attachments/assets/d78fd48c-8add-418e-b7e8-bb839c55a9e9)

[2.636.0.626_20240803T215901Z_Player_df900_last.log](https://github.com/user-attachments/files/16482996/2.636.0.626_20240803T215901Z_Player_df900_last.log)

### Roblox Experience link

https://www.roblox.com/games/328028363/Typical-Colors-2-NEW-MOBILE-BETA

**Comment by Topercessen** [comment]
I got the same issue
`Fatal glibc error: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)`

**Comment by Vlad55432** [comment]
oh, damn. let me retest
https://github.com/vinegarhq/sober/issues/2#issuecomment-2266627814

**Comment by Vlad55432** [comment]
> UPD2: OK, Maybe I should reopen this, because it became crashing, but not because of glibc. Idk why it crashes honestly

**Comment by Topercessen** [comment]
I found out one of the causing events of this. If you die, per say in a battlegrounds game _(I tried many)_ it will cause this crash.

**Comment by Vlad55432** [comment]
I've found a workaround & why this happens. Sometimes, when model gets highlighted, it oftenly causing nvidia drivers go insane and freeze whole game.
For workaround use this fflag "FFlagRealMobileOutline": false

**Comment by Topercessen** [comment]
> I've found a workaround & why this happens. Sometimes, when model gets highlighted, it oftenly causing nvidia drivers go insane and freeze whole game. For workaround use this fflag `"FFlagRealMobileOutline": false`

I don't use Nvidia though and I have a 7700XT.

I think it's related to some HumanoidStateTypes like ragdoll and death, and when these events fire it causes the crash. But I don't know.

**Comment by Vlad55432** [comment]
> > I've found a workaround & why this happens. Sometimes, when model gets highlighted, it oftenly causing nvidia drivers go insane and freeze whole game. For workaround use this fflag `"FFlagRealMobileOutline": false`
> 
> I don't use Nvidia though and I have a 7700XT.
oh, my bad, I thought it's another nvidia moment

**Comment by Topercessen** [comment]
So is the driver tag really necessary? I don't think it's related to drivers.

**Comment by Vlad55432** [comment]
another freezing (man...)
still freezing randomly
roblox logs doesn't show anything anyway, but dmesg do
[2.636.0.626_20240804T193303Z_Player_be3f4_last.log](https://github.com/user-attachments/files/16488709/2.636.0.626_20240804T193303Z_Player_be3f4_last.log)

![зображення](https://github.com/user-attachments/assets/a8654567-1104-4164-9260-70645db9d808)

[ 6434.334521] [vkps] Update[14984]: segfault at 7f8e089f43d0 ip 00007f8e089f43d0 sp 00007f8bddfff240 error 14 in libEGL_nvidia.so.555.58.02[7f8e0a600000+e4000] likely on CPU 3 (core 3, socket 0)
[ 6434.334534] Code: Unable to access opcode bytes at 0x7f8e089f43a6.
[ 6472.587822] [vkps] Update[15380]: segfault at 7ff2671f43d0 ip 00007ff2671f43d0 sp 00007ff07d3ff240 error 14 likely on CPU 9 (core 3, socket 0)
[ 6472.587833] Code: Unable to access opcode bytes at 0x7ff2671f43a6.
uhhhhhhh

**Comment by Vlad55432** [comment]
Here's new one
```
[ 7349.743044] [vkps] Update[17594]: segfault at 7f2514bf43d0 ip 00007f2514bf43d0 sp 00007f24febff240 error 14 likely on CPU 3 (core 3, socket 0)
[ 7349.743054] Code: Unable to access opcode bytes at 0x7f2514bf43a6.
```

**Comment by ehunt34** [comment]
Has anyone found a fix for the `tpp.c:83` error?

**Comment by Vlad55432** [comment]
here's new crash
`Fatal glibc error: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)
`

**Comment by tunis4** [comment]
fixed in latest update

**Comment by Vlad55432** [comment]
> fixed in latest update

God bless you!
