### ISSUE TITLE
Issues using / to open the chat in quite a few games

### ISSUE THREAD

**Issue by XxsjrapsxX** [vinegarhq/sober#224]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have noticed that when attempting to press the / button to open the chat it does not seem to work which can be a little inconvenient when wanting to chat quickly, especially in pvp games.

**Comment by Hri7566** [comment]
have you seen any games where it does work?

**Comment by XxsjrapsxX** [comment]
not as of recently

**Comment by fuckindumbfox** [comment]
i am also suffering from this bug.

**Comment by Yaco-Taco** [comment]
same here

**Comment by XxsjrapsxX** [comment]
is anyone here also having issues with getting shift lock to work well? It seems a lot of features that are existent on basic pc versions are missing when i comes to controls and actual settings in roblox.

**Comment by fuckindumbfox** [comment]
> is anyone here also having issues with getting shift lock to work well? It seems a lot of features that are existent on basic pc versions are missing when i comes to controls and actual settings in roblox.

for some reason for me the shift lock toggle in settings is missing too, but shift lock itself works well for me

**Comment by JuniorBeats10** [comment]
same here

**Comment by Naymmmm** [comment]
This is an issue with LegacyChatService and is likely not a Sober issue. As an alternative you can press "." to open chat.

**Comment by Naymmmm** [comment]
This is an issue with LegacyChatService and is likely not a Sober issue. As an alternative you can press "." to open chat.

**Comment by tunis4** [comment]
duplicate of #254
