### ISSUE TITLE
outlines/highlights not rendering properly in some situations

### ISSUE THREAD

**Issue by teamkill3d** [vinegarhq/sober#23]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

on outlined models that are extremely thin, artifacting in the form of red pixels can appear where the highlight should be

here's an example
![Untitled](https://github.com/user-attachments/assets/dfb1be86-cea6-4bd2-8a9b-e0556ea83912)

i already know about the crash that outlines can cause, and i have accounted for it in my settings

### Roblox Experience link

universal issue

**Comment by km9l** [comment]
i see this as a likely roblox vulkan engine bug

**Comment by tunis4** [comment]
fixed in the update
