### ISSUE TITLE
DragDetectors (DragStyle: RotateAxis; ResponseStyle: Geometric) battle between start and actual locations during drags

### ISSUE THREAD

**Issue by mrhoomanwastaken** [vinegarhq/sober#238]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when playing a game that has DragDetectors a weird jittery/snappy motion prevents the object from being dragged. I have encountered this bug in only one game, but after talking to the dev it seems like there might be an issue with "DragDetector" instance.  [https://create.roblox.com/docs/reference/engine/classes/DragDetector](url) ps.sorry for the horrible video compression. 

https://github.com/user-attachments/assets/7e6cbbd9-fdac-4880-8d7a-62d113e2e0ff

### Roblox Experience link

https://www.roblox.com/games/13412842185/Breadwinner-World

**Comment by tunis4** [comment]
fixed in update
