### ISSUE TITLE
libnvidia-glcore.so.560.35.03 Segfault

### ISSUE THREAD

**Issue by Vlad55432** [vinegarhq/sober#244]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?
My specs: Ryzen 5600 & RTX 3060 with proprietary 560.35.03 drivers
Was Playing [Left 4 Blox](https://www.roblox.com/games/17742439482/Left-4-Blox-V1-21)
Sober was runned with XWayland, because of explicit sync related crashes
I was just playing chilly, I don't know how I managed to crash Roblox
Maybe game crashes randomly, probably?
[latest.log](https://github.com/user-attachments/files/17059796/latest.log)
![зображення](https://github.com/user-attachments/assets/5ae504ff-d54f-45dd-892a-751dbe4f6466)
![зображення](https://github.com/user-attachments/assets/c9ec7479-c498-45a9-a955-fb7062b47564)

```
[ 2397.933365] sober[50316]: segfault at f0 ip 00007f88a23bca10 sp 00007f889e3fc448 error 4 in libnvidia-glcore.so.560.35.03[dbca10,7f88a1600000+1eab000] likely on CPU 9 (core 3, socket 0)
[ 2397.933374] Code: 41 0f 95 c1 45 21 f9 4d 85 f6 0f 84 59 05 00 00 4d 8b 18 bf ff ff ff ff 4d 85 d2 74 0d 49 8b ba f8 00 00 00 8b
```

### Roblox Experience link

https://www.roblox.com/games/17742439482/Left-4-Blox-V1-21

**Comment by teamkill3d** [comment]
a similar bug happens on [detriment](https://www.roblox.com/games/6958681991)

**Comment by AshtakaOOf** [comment]
Have you tried the Nvidia 555 drivers? Rolling back from 560 fixed a bunch of random crashes for me.

**Comment by Vlad55432** [comment]
> Have you tried the Nvidia 555 drivers?

555 drivers is basically not available in rpmnonfree repo, only 550

**Comment by AshtakaOOf** [comment]
You could try installing 555 using these [rpmfusion koji](https://koji.rpmfusion.org/koji/search?terms=nvidia&type=package&match=regexp) links.
```
https://koji.rpmfusion.org/kojifiles/packages/nvidia-kmod/555.58.02/1.fc40/x86_64/akmod-nvidia-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-cuda-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-cuda-libs-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia--devels-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-kmodsrc-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-libs-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/xorg-x11-drv-nvidia/555.58.02/1.fc40/x86_64/xorg-x11-drv-nvidia-power-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/nvidia-persistenced/555.58.02/1.fc40/x86_64/nvidia-persistenced-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/nvidia-modprobe/555.58.02/1.fc40/x86_64/nvidia-modprobe-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/nvidia-settings/555.58.02/1.fc40/x86_64/nvidia-settings-555.58.02-1.fc40.x86_64.rpm
https://koji.rpmfusion.org/kojifiles/packages/nvidia-xconfig/555.58.02/1.fc40/x86_64/nvidia-xconfig-555.58.02-1.fc40.x86_64.rpm
```
You can just plug them into `dnf install`, or you can put them in a txt file and do `sudo dnf install $(cat links.txt) --allowerasing`.
ps: if I messed up a link please tell me :)
