### ISSUE TITLE
I know it's probably my bad GPU but I need to make sure it's not my fault and it's only because my GPU is bad

### ISSUE THREAD

**Issue by verydeaad** [vinegarhq/sober#248]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Is my GPU not supported or did I incorrectly set up sober

My GPU is  AMD Radeon HD 8470D 

I know and half certain that it might be my GPU that is too old but I might have set up something incorrectly who knows

**Comment by Wildtick** [comment]
can you run `flatpak run -v org.vinegarhq.Sober`

**Comment by verydeaad** [comment]
> can you run `flatpak run -v org.vinegarhq.Sober`

Yes, It displays a window titled "Sober" and it disappears in 1-2 seconds.

**Comment by tunis4** [comment]
your gpu is too old to support vulkan
