### ISSUE TITLE
Roblox Player lags while typing within in-app text chat (NOT within a game)

### ISSUE THREAD

**Issue by some-username-here1** [vinegarhq/sober#249]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm not sure if it's the roblox app or sober, but when typing into the text box within a DM with someone, the text chat lags and my text input are slow. It's random and I'm not sure why it speeds up all of a sudden, only to slow down again, at times.

Here's my [log](https://github.com/user-attachments/files/17085605/2.642.0.635_20240921T185744Z_Player_d5f7a_last.log) in case it ever ends up providing useful information for figuring this out.

**Comment by Naymmmm** [comment]
I have tested this on my Android device and it seems it is not exclusive to Sober.

**Comment by cyewashish** [comment]
Moving your cursor around seems to speed it up. Happens on the login screen too.

**Comment by tunis4** [comment]
fixed in update
