### ISSUE TITLE
Sober on WSL / Launch from command line

### ISSUE THREAD

**Issue by tommarekCZE** [vinegarhq/sober#253]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Nope

### Describe the Solution you'd Like

I want to be able launch sober from command line, like for example "sober --launch https://roblox.com/experiences/testexample",
so It would make technically some kind support for WSL

### Describe Alternatives you've considered

I couldnt find any way how to launch sober from command line on linux

**Comment by hdgetban** [comment]
What tf did you just say?

**Comment by jumanji144** [comment]
>be on windows
>download wsl
>use sober through wsl to play roblox on windows
>???
>profit

**Comment by hdgetban** [comment]
BRO YOU HAVE ROBLOX ON WINDOWS ALREADY???? And it you want sober really bad use linux how hard is it

**Comment by tunis4** [comment]
have you tried `flatpak run org.vinegarhq.Sober`
