### ISSUE TITLE
Mouse unusable in menus where game forces first person mode

### ISSUE THREAD

**Issue by ryand56** [vinegarhq/sober#27]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When playing games where it forces first person mode, I am unable to interact with any menus as my mouse is frozen. One example of a game is Evade.

### Roblox Experience link

https://www.roblox.com/games/9872472334/Evade

**Comment by ajd07** [comment]
Duplicate post
Press `F1` and it'll unlock the cursor, press `F1` again to lock it.

**Comment by ryand56** [comment]
> Duplicate post Press `F1` and it'll unlock the cursor, press `F1` again to lock it.

Ah, sorry, didn't know this was a thing
