### ISSUE TITLE
Client crashing in Defusal

### ISSUE THREAD

**Issue by vovan2055** [vinegarhq/sober#270]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober crashes mid-game when playing Defusal
[log.txt](https://github.com/user-attachments/files/17215288/log.txt)

### Roblox Experience link

https://www.roblox.com/games/3577061261/Defuse

**Comment by tunis4** [comment]
duplicate of #258
