### ISSUE TITLE
Arch Linux, NVidia GPU, crashes with Vulkan error on start

### ISSUE THREAD

**Issue by xthemed** [vinegarhq/sober#274]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Worked fine on Zorin OS, decided to go Arch, and now it doesn't work? I'm using the nouveu driver or whatever it's called.

[2.642.0.635_20241002T144637Z_Player_97218_last.log](https://github.com/user-attachments/files/17231332/2.642.0.635_20241002T144637Z_Player_97218_last.log)

**Comment by xthemed** [comment]
wayland btw

**Comment by xthemed** [comment]
![image](https://github.com/user-attachments/assets/f7ab2891-c9f4-4451-b82d-2328f39ce0f5)

**Comment by kirbix12** [comment]
Which NVIDIA GPU do you have? Nouveu does not have Vulkan drivers. Unless you have a card that is Turning (RTX 20XX or GTX 16XX) or later (Ampere RTX 30XX + Ada RTX 40XX), you will have to use the proprietary drivers.

**Comment by tunis4** [comment]
try installing the proper driver instead of nouveau

**Comment by quuinnn** [comment]
https://wiki.archlinux.org/title/Nouveau#Using_the_Mesa_NVK_Vulkan_Driver

**Comment by skoove** [comment]
also run `flatpak update` you need the flatpak version of drivers as well as the normal ones
