### ISSUE TITLE
Server list has a broken layout and does not display any servers.

### ISSUE THREAD

**Issue by Xatra1** [vinegarhq/sober#277]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When opening the servers list on a game's page, the following occurs:
![image](https://github.com/user-attachments/assets/711ad75b-acb0-47f2-87ad-e251405c46ed)
I am using Arch Linux.

**Comment by m-attz** [comment]
Which WM are you using?

**Comment by Xatra1** [comment]
KWin on Wayland.

**Comment by m-attz** [comment]
Make sure that your graphics drivers are updated and are compatible with Vulkan (as well as with WM). If this still doesn't work then try and test another WM.

**Comment by Xatra1** [comment]
The issue appears to be with Wayland. Both KWin and Mutter show the page properly when using X11.

**Comment by m-attz** [comment]
Yeah, I think a lot of issues have been reported with users that are using Wayland (I have also ran into some minor issues). It's something the developers will need to look at.

**Comment by reflexran** [comment]
This is an issue related to WebView, you pretty much can't do anything about it and the only solution is to use the Roblox website to join servers.

**Comment by FoxoBread** [comment]
> This is an issue related to WebView, you pretty much can't do anything about it and the only solution is to use the Roblox website to join servers.

How does one forward Roblox launch requests to sober from a web browser?

**Comment by Xatra1** [comment]
> > This is an issue related to WebView, you pretty much can't do anything about it and the only solution is to use the Roblox website to join servers.
> 
> How does one forward Roblox launch requests to sober from a web browser?

Just join a server from the Roblox website like normal. Sober will then automatically open.

**Comment by FoxoBread** [comment]
> > > This is an issue related to WebView, you pretty much can't do anything about it and the only solution is to use the Roblox website to join servers.
> > 
> > 
> > How does one forward Roblox launch requests to sober from a web browser?
> 
> Just join a server from the Roblox website like normal. Sober will then automatically open.

I'm afraid that is non-functional for me. Is there a way to manually call the sober binary and pass a server URL?

**Comment by FoxoBread** [comment]
This seems to be fixed for me, as of latest update to WebView and Sober.

**Comment by Xatra1** [comment]
The issue I reported seems to be fixed as well. Nice work.
