### ISSUE TITLE
Stuttering on Ubuntu

### ISSUE THREAD

**Issue by MatTrof** [vinegarhq/sober#278]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Linux version: Ubuntu 24.04

GPU: Nvidia Geforce RTX 3070 

massive stuttering, makes my eyes die
also no video and pics because couldnt get it on camera
if theres any help, please reply (i havent tinkered with the settings yet because i dont know how to)

**Comment by m-attz** [comment]
Is the issue occurring when you are playing a game?

**Comment by MatTrof** [comment]
> Is the issue occurring when you are playing a game?

its occuring everywhere in the app

**Comment by m-attz** [comment]
Okay, that must be an eye sore. Do you have the latest drivers for your graphics card installed?

**Comment by MatTrof** [comment]
> Okay, that must be an eye sore. Do you have the latest drivers for your graphics card installed?

![image](https://github.com/user-attachments/assets/0d2a5fe0-87d7-494d-af7e-f7abd24b8dfa)
yeah i think so

**Comment by MatTrof** [comment]
I have found a solution, even tho it's not perfect. Just exit full screen mode and thats kinda it, I really love full screen mode but im gonna stop using full screen for now until i see a new update, also getting more fps without full screen

**Comment by m-attz** [comment]
I'm glad you found a decent solution. It could be related to the WM also but it's hard to debug with limited information. Hopefully the developers fix it.

**Comment by Coder2195Text** [comment]
Is it screen tearing, or some different issue? Not sure if I should open a new issue, because it also resolves with non fullscreen mode.

Visual examples if you don't know what screen tearing is:
![image](https://github.com/user-attachments/assets/60544ad7-0d5e-40a6-9385-087b3261385a)
![image](https://github.com/user-attachments/assets/17908bc0-f460-4e9d-9dc3-c60b2830a316)
![image](https://github.com/user-attachments/assets/90156678-516c-4d62-8613-5621efec2558)

**Comment by MatTrof** [comment]
> Is it screen tearing, or some different issue? Not sure if I should open a new issue, because it also resolves with non fullscreen mode.
> 
> Visual examples if you don't know what screen tearing is:
> ![image](https://github.com/user-attachments/assets/60544ad7-0d5e-40a6-9385-087b3261385a)
> ![image](https://github.com/user-attachments/assets/17908bc0-f460-4e9d-9dc3-c60b2830a316)
> ![image](https://github.com/user-attachments/assets/90156678-516c-4d62-8613-5621efec2558)
> 

screen tearing

**Comment by m-attz** [comment]
Just to add on to this discussion I found [this](https://forums.developer.nvidia.com/t/vulkan-app-with-vk-present-mode-fifo-khr-vsync-causes-desktop-stuttering-across-entire-system-when-moving-or-resizing-any-window-linux-x11/185015/4) thread. It may be something related to Vulkan using vsync and how certain window system protocols interact with it (more details within the thread).

**Comment by Coder2195Text** [comment]
in that case this is not a graphic driver issue, as Im using integrated
graphics

would be helpful to update the name to 'screen tearing while fullscreen" or
something like that for future bug reports
