### ISSUE TITLE
add support for aarch64 devices

### ISSUE THREAD

**Issue by leonpano2006** [vinegarhq/sober#279]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

i see there was older issue about arm64 support request for roblox
but not every device can run android or very hard to run android
waydroid is also not working for device such as tegra(same reason on nvidia gpu driver and stock kernel from nvidia does not have binder)
nvidia is known to have bad wayland support(do you want to run software rendering?)

### Describe the Solution you'd Like

a working sober for arm64 linux(i think armhf/el can also be added but not so necessary, arm64 priority is far higher then armhf/el)

### Describe Alternatives you've considered

waydoird?  ---> not working on stock t194/t234 kernel(binder and other what android need is missing) and if i tried to compile with that feature and even it works then will be issue of gpu is not usable(use cpu as gpu? this maybe can work but is very on pc with powerful cpu and is very inefficient)

**Comment by python-coding-404** [comment]
Install zen kernel https://github.com/zen-kernel/zen-kernel

**Comment by leonpano2006** [comment]
> Install zen kernel https://github.com/zen-kernel/zen-kernel

that wont fix anything(if you mean for waydroid)
wayland issue is on userspace not related to kernel

and to upgrade kernel to newer version such as 6.6 or 6.11 is something i wish todo but is very very hard
i tried to boot generic kernel(from ubuntu offical repo) on my jetson but that won't work at all
acpi is also not working

and reamber we are working on arm64 not amd64

**Comment by Henry-Hiles** [comment]
this would be cool

**Comment by tunis4** [comment]
https://github.com/vinegarhq/sober/issues/346#issuecomment-2442454805

**Comment by leonpano2006** [comment]
> https://github.com/vinegarhq/sober/issues/346#issuecomment-2442454805

I just want to mention that not all devices is possible to run waydroid(such as Nvidia, even if it runs then is software rendering)
