### ISSUE TITLE
Cannot run sober

### ISSUE THREAD

**Issue by MakingPanorama** [vinegarhq/sober#280]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I can't run sober.
I was tried run it with command `flatpak run org.vinegarhq.Sober
`, but nothing. I really it doesn't print nothing even about error

Info about system:
`         
OS: Arch Linux x86_64 
Host: P5KC 
Kernel: 6.11.1-arch1-1 
 Uptime: 3 hours, 4 mins 
Packages: 757 (pacman), 14 (flatpak) 
Shell: bash 5.2.37 
Resolution: 1920x1080 
DE: Plasma 6.1.5 
WM: kwin 
Theme: Default [GTK2/3] 
Icons: Deepin2022-Dark [GTK2/3] 
Terminal: konsole 
CPU: Intel Core 2 Quad Q6600 (4) @ 2.394GHz 
GPU: AMD ATI Radeon HD 8670 / R5 340X / R7 250/350/350X OEM 
Memory: 1480MiB / 3916MiB `

**Comment by reflexran** [comment]
Your CPU is too old, you need SSE4 to run roblox which your CPU doesn't support.

**Comment by MakingPanorama** [comment]
> Your CPU is too old, you need SSE4 to run roblox which your CPU doesn't support.

**Comment by reflexran** [comment]
> > Your CPU is too old, you need SSE4 to run roblox which your CPU doesn't support.
> 
> Roblox or sober itself?

Pretty sure Roblox itself but i might be wrong.

**Comment by MakingPanorama** [comment]
> > > Your CPU is too old, you need SSE4 to run roblox which your CPU doesn't support.
> > 
> > Roblox or sober itself?
> 
> Pretty sure Roblox itself but i might be wrong.

I guess i missing some dependencies to run sober. Cuz run without any error reports in terminal strange

**Comment by reflexran** [comment]
> I guess i missing some dependencies to run sober. Cuz run without any error reports in terminal strange

It's actually quite common, you can run `sudo dmesg | grep sober` to see logs.

**Comment by MakingPanorama** [comment]
> Your CPU is too old, you need SSE4 to run roblox which your CPU doesn't support.

Never meet that problem on windows roblox

**Comment by reflexran** [comment]
> Never meet that problem on windows roblox

Sober is quite different from the windows version of Roblox, all i know is that you need SSE4.

**Comment by MakingPanorama** [comment]
> > Never meet that problem on windows roblox
> 
> Sober is quite different from the windows version of Roblox, all i know is that you need SSE4.

Just checked it out. And my cpu supports ssee 4

**Comment by reflexran** [comment]
> Just checked it out. And my cpu supports SSE 4

Can you please list a source? I've looked at both the Wikipedia and TechPowerup article for that CPU and both of them said that it only supported up to SSE3.

**Comment by MakingPanorama** [comment]
https://community.intel.com/t5/Intel-ISA-Extensions/Core2-Quad-S-SSE-3-4/td-p/909136

**Comment by reflexran** [comment]
> https://community.intel.com/t5/Intel-ISA-Extensions/Core2-Quad-S-SSE-3-4/td-p/909136

The Core2 Quad Q9400 does indeed support SSE4, your CPU doesn't.

**Comment by MakingPanorama** [comment]
> > I guess i missing some dependencies to run sober. Cuz run without any error reports in terminal strange
> 
> It's actually quite common, you can run `sudo dmesg | grep sober` to see logs.

Absolutely nothing 
![изображение](https://github.com/user-attachments/assets/75e7ffcc-f025-459b-bdae-a37464f50a6f)
