### ISSUE TITLE
Cant install Sober through terminal also doesnt pop up on the store

### ISSUE THREAD

**Issue by Metroner** [vinegarhq/sober#283]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

~$ flatpak install --user https://sober.vinegarhq.org/sober.flatpakref
error: No such ref 'app/org.vinegarhq.Sober/aarch64/master' in remote sober~$ 

Im using asahi fedora edition linux

**Comment by reflexran** [comment]
Sober does't support ARM.

**Comment by kirbix12** [comment]
Sober is not hosted on Flathub. It also does not support ARM, and by extension, Asahi Linux.

Even if there is support, you can't run it on AL because there isn't any Vulkan drivers yet. (Honeykrisp is yet to release)
