### ISSUE TITLE
Fails to launch Nvidia GPU

### ISSUE THREAD

**Issue by SparklesReal** [vinegarhq/sober#284]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

sparkles@sparkles-laptop-linux:~$ flatpak run org.vinegarhq.Sober 
SDL_CreateWindow failed: Installed Vulkan doesn't implement the VK_KHR_surface extension
FATAL: 18576965336

I saw similar errors in bug reports but that is in the GUI I can't even launch it

**Comment by reflexran** [comment]
Can you please run `nvidia-smi`

**Comment by SparklesReal** [comment]
sparkles@sparkles-laptop-linux:~/Downloads$ nvidia-smi
Sat Oct  5 23:40:11 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro RTX 5000 with Max...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   60C    P5             23W /   50W |    1583MiB /  16384MiB |     31%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1107      G   /usr/lib/xorg/Xorg                            314MiB |
|    0   N/A  N/A      1395      G   /usr/bin/kwalletd6                              2MiB |
|    0   N/A  N/A      1472      G   ..._64-linux-gnu/libexec/kglobalacceld          2MiB |
|    0   N/A  N/A      1530      G   /usr/bin/ksmserver                              2MiB |
|    0   N/A  N/A      1533      G   /usr/bin/kded6                                  2MiB |
|    0   N/A  N/A      1536      G   /usr/bin/kwin_x11                             140MiB |
|    0   N/A  N/A      1587      G   /usr/bin/plasmashell                           61MiB |
|    0   N/A  N/A      1605      G   ...linux-gnu/libexec/kactivitymanagerd          2MiB |
|    0   N/A  N/A      1630      G   ...c/polkit-kde-authentication-agent-1          2MiB |
|    0   N/A  N/A      1631      G   ...inux-gnu/libexec/org_kde_powerdevil          2MiB |
|    0   N/A  N/A      1632      G   ...-gnu/libexec/xdg-desktop-portal-kde          2MiB |
|    0   N/A  N/A      1775      G   /usr/bin/kdeconnectd                            2MiB |
|    0   N/A  N/A      1785      G   /usr/bin/kaccess                                2MiB |
|    0   N/A  N/A      1789      G   ...-linux-gnu/libexec/DiscoverNotifier          2MiB |
|    0   N/A  N/A      1805      G   /usr/bin/okular                                 2MiB |
|    0   N/A  N/A      1808      G   /usr/bin/konsole                                2MiB |
|    0   N/A  N/A      1813      G   /usr/bin/dolphin                                2MiB |
|    0   N/A  N/A      2027      G   ...nu/libexec/kf6/baloo_file_extractor          2MiB |
|    0   N/A  N/A      2066      G   ...86_64-linux-gnu/libexec/baloorunner          2MiB |
|    0   N/A  N/A      2253      G   ...yOnDemand --variations-seed-version        136MiB |
|    0   N/A  N/A      3303      G   ./steamwebhelper                                4MiB |
|    0   N/A  N/A      4095      G   /opt/brave.com/brave/brave                      2MiB |
|    0   N/A  N/A      4139      G   ...84e219b8454bff99457cb83f349546f1d71        839MiB |
|    0   N/A  N/A      4273      G   ...bin/plasma-browser-integration-host          2MiB |
|    0   N/A  N/A      9205      G   /usr/bin/konsole                                2MiB |
|    0   N/A  N/A      9683      G   /usr/bin/plasma-discover                       16MiB |
+-----------------------------------------------------------------------------------------+
sparkles@sparkles-laptop-linux:~/Downloads$

**Comment by reflexran** [comment]
Sorry for the late response, can you please run `flatpak list`

**Comment by SparklesReal** [comment]
sparkles@sparkles-laptop-linux:~$ flatpak list
Name                                    Application ID                                    Version                    Branch         Origin   Installation
Wine                                    com.fightcade.Fightcade.Wine                                                 stable         flathub  system
Heroic Games Launcher                   com.heroicgameslauncher.hgl                       v2.15.2                    stable         flathub  system
HandBrake Team                          fr.handbrake.ghb                                  1.8.2                      stable         flathub  system
TAP-plugins                             org.freedesktop.LinuxAudio.Plugins.TAP            1.0.1                      23.08          flathub  system
SWH                                     org.freedesktop.LinuxAudio.Plugins.swh            0.4.17                     23.08          flathub  system
Freedesktop Platform                    org.freedesktop.Platform                          freedesktop-sdk-23.08.23   23.08          flathub  system
i386                                    org.freedesktop.Platform.Compat.i386                                         23.08          flathub  system
Mesa                                    org.freedesktop.Platform.GL.default               24.2.3                     23.08          flathub  system
Mesa                                    org.freedesktop.Platform.GL.default               24.2.3                     23.08          flathub  user
Mesa (Extra)                            org.freedesktop.Platform.GL.default               24.2.3                     23.08-extra    flathub  system
Mesa (Extra)                            org.freedesktop.Platform.GL.default               24.2.3                     23.08-extra    flathub  user
Mesa                                    org.freedesktop.Platform.GL.default               24.2.3                     24.08          flathub  system
Mesa (Extra)                            org.freedesktop.Platform.GL.default               24.2.3                     24.08extra     flathub  system
nvidia-560-35-03                        org.freedesktop.Platform.GL.nvidia-560-35-03                                 1.4            flathub  system
nvidia-560-35-03                        org.freedesktop.Platform.GL.nvidia-560-35-03                                 1.4            flathub  user
Mesa                                    org.freedesktop.Platform.GL32.default             24.2.3                     23.08          flathub  system
nvidia-535-183-01                       org.freedesktop.Platform.GL32.nvidia-535-183-01                              1.4            flathub  system
nvidia-550-107-02                       org.freedesktop.Platform.GL32.nvidia-550-107-02                              1.4            flathub  system
nvidia-560-35-03                        org.freedesktop.Platform.GL32.nvidia-560-35-03                               1.4            flathub  system
Intel                                   org.freedesktop.Platform.VAAPI.Intel                                         23.08          flathub  system
Intel                                   org.freedesktop.Platform.VAAPI.Intel                                         23.08          flathub  user
Intel                                   org.freedesktop.Platform.VAAPI.Intel                                         24.08          flathub  system
i386                                    org.freedesktop.Platform.VAAPI.Intel.i386                                    23.08          flathub  system
ffmpeg-full                             org.freedesktop.Platform.ffmpeg-full                                         23.08          flathub  system
i386                                    org.freedesktop.Platform.ffmpeg_full.i386                                    23.08          flathub  system
openh264                                org.freedesktop.Platform.openh264                 2.1.0                      2.2.0          flathub  system
openh264                                org.freedesktop.Platform.openh264                 2.1.0                      2.2.0          flathub  user
openh264                                org.freedesktop.Platform.openh264                 2.4.1                      2.4.1          flathub  system
openh264                                org.freedesktop.Platform.openh264                 2.4.1                      2.4.1          flathub  user
The GNOME Project                       org.gnome.Calculator                              47.0                       stable         flathub  system
GNOME Application Platform version 46   org.gnome.Platform                                                           46             flathub  system
GNOME Application Platform version 46   org.gnome.Platform                                                           46             flathub  user
GNOME Application Platform version 47   org.gnome.Platform                                                           47             flathub  system
Breeze GTK theme                        org.gtk.Gtk3theme.Breeze                          6.1.5                      3.22           flathub  system
Breeze GTK theme                        org.gtk.Gtk3theme.Breeze                          6.1.5                      3.22           flathub  user
KDE Application Platform                org.kde.Platform                                                             6.7            flathub  user
KDE                                     org.kde.isoimagewriter                            24.08.1                    stable         flathub  user
Krita Foundation                        org.kde.krita                                     5.2.3                      stable         flathub  system
VinegarHQ & Sober contributors          org.vinegarhq.Sober                               0.0.0-dc504d6              master         sober    user
Wine Project                            org.winehq.Wine                                   9.0                        stable-23.08   flathub  system
DXVK                                    org.winehq.Wine.DLLs.dxvk                         2.4.1                      stable-23.08   flathub  system
Gecko                                   org.winehq.Wine.gecko                                                        stable-23.08   flathub  system
Mono                                    org.winehq.Wine.mono                                                         stable-23.08   flathub  system
XClicker                                xyz.xclicker.xclicker                             1.5.0                      stable         flathub  system

**Comment by reflexran** [comment]
What distro are you using?

**Comment by SparklesReal** [comment]
> What distro are you using?

KDE Neon 6.0

**Comment by reflexran** [comment]
Can you run `sudo apt install libvulkan1` and see if it is already installed?

**Comment by SparklesReal** [comment]
sparkles@sparkles-laptop-linux:/home$ sudo apt install libvulkan1
[sudo] password for sparkles: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libvulkan1 is already the newest version (1.3.204.1-2).
libvulkan1 set to manually installed.
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages were automatically installed and are no longer required:
  acl hplip-data libhpmud0 libieee1284-3 libkf5networkmanagerqt6 libnvidia-egl-wayland1:i386 libsane-common libsane-hpaio libsnmp-base libsnmp40
  linux-headers-5.15.0-119 linux-headers-5.15.0-121 nvidia-firmware-535-535.183.01 nvidia-firmware-550-550.107.02 printer-driver-hpcups
  printer-driver-postscript-hp python3-pexpect python3-ptyprocess python3-renderpm python3-reportlab python3-reportlab-accel qdbus-qt5 sane-airscan
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by kirbix12** [comment]
> > What distro are you using?
> 
> KDE Neon 6.0

KDE Neon does not "support" NVIDIA cards and they did say on their project website to deter using Neon on those with NVIDIA hardway.

Assuming you _did_ ignore the warning anyways, which driver are you using? (Nouveau? Proprietary? Open-kernel?)

**Comment by SparklesReal** [comment]
> > > What distro are you using?
> > 
> > 
> > KDE Neon 6.0
> 
> KDE Neon does not "support" NVIDIA cards unless you're willing to use Nouveau and they did say on their project website to deter using Neon with the proprietary drivers.
> 
> Assuming you _did_ ignore the warning anyways, which driver are you using? (Nouveau? Proprietary? Open-kernel?)

I did not see this as I just installed the same distro as I am running on my main pc with a AMD card
I use the Nvidia 560 driver which is the proprietary I think

**Comment by ydrk** [comment]
> > What distro are you using?
> 
> KDE Neon 6.0

You are aware that Neon isnt a practical distro right

**Comment by SparklesReal** [comment]
> > > What distro are you using?
> > 
> > 
> > KDE Neon 6.0
> 
> You are aware that Neon isnt a practical distro right

It is a distro but it's main functions is to provided the latest version of plasma. I don't see how this is relevant to the issue tho?

**Comment by kirbix12** [comment]
> > > > What distro are you using?
> > > 
> > > 
> > > KDE Neon 6.0
> > 
> > 
> > You are aware that Neon isnt a practical distro right
> 
> It is a distro but it's main function is to provided the latest version of plasma. I don't see how this is relevant to the issue tho?

Fedora Linux (essentially their KDE Spin alone) pretty much does the same function. Fedora will update you to the latest version of plasma-workspace where when available.

**Comment by kirbix12** [comment]
Anyways, it seems as though VK_KHR_SURFACE could be related to driver problems and I would go through driver reinstallation.

I would suggest getting out of Neon while you can though, considering it isn't for NVIDIA according to KDE.

**Comment by ydrk** [comment]
> > > > What distro are you using?
> > > 
> > > 
> > > KDE Neon 6.0
> > 
> > 
> > You are aware that Neon isnt a practical distro right
> 
> It is a distro but it's main function is to provided the latest version of plasma. I don't see how this is relevant to the issue tho?

I know it's unrelated but Neon just is not good dude

1. It's on a dated LTS which will be EOL in 2.5 years
2. Reiterating that proprietary nvidia drivers arent supported
3. It's quite literally KDE testing ground and not a genuine practical distro
4. You're using bleeding edge KDE with a dated LTS...

This is coming from someone who used to use it

**Comment by SparklesReal** [comment]
> > > > > What distro are you using?
> > > > 
> > > > 
> > > > KDE Neon 6.0
> > > 
> > > 
> > > You are aware that Neon isnt a practical distro right
> > 
> > 
> > It is a distro but it's main function is to provided the latest version of plasma. I don't see how this is relevant to the issue tho?
> 
> I know it's unrelated but Neon just is not good dude
> 
> 1. It's on a dated LTS which will be EOL in 2.5 years
> 2. Reiterating that proprietary nvidia drivers arent supported
> 3. It's quite literally KDE testing ground and not a genuine practical distro
> 4. You're using bleeding edge KDE with a dated LTS, if everything else was bleeding edge then sure, but like it doesnt mix well
> 
> This is coming from someone who used to use it (who now uses the KDE spin for Fedora)
> 
> And also I do agree with @kirbix12 that you should get off neon

This is my school computer so I can't switch as I need to keep all my files. I used to use Kubuntu but after some update it got bricked idk how. At home Neon works fine with my RX 6700 XT. Either I stay on KDE Neon or I switch to windows which I have installed for dual boot.

**Comment by SparklesReal** [comment]
Problem solved, switched to Kubuntu.
