### ISSUE TITLE
Add `Keywords` key to desktop file

### ISSUE THREAD

**Issue by felipe19930** [vinegarhq/sober#285]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

My proposal is to make Sober more discoverable by introducing the `Keywords` key to the [desktop file](https://specifications.freedesktop.org/desktop-entry-spec/latest/recognized-keys.html).

I believe we should, at the very least, add `roblox` to the keywords list, because the current desktop file is very bare-bones and doesn't have other useful keys like `Comment` or `GenericName`, making it a bit slower to launch Roblox until you remember the app is called `Sober`. lol

### Describe the Solution you'd Like

Add `Keywords=roblox` to the desktop file.

### Describe Alternatives you've considered

N/A

**Comment by tunis4** [comment]
added in update
