### ISSUE TITLE
sober crashes if idle for to long

### ISSUE THREAD

**Issue by TheoW03** [vinegarhq/sober#288]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot from 2024-10-08 21-57-29](https://github.com/user-attachments/assets/91c0126d-f964-4603-a0ba-2721e2f98b82)

this started happening. I dont know how to send the logs. but
it happens when i leave sober idle for too long. 

sometimes it happens on startup
its very weird.

**Comment by guyguy124** [comment]
this same issue is happening iwht mine, except i play again for about less than 5 seconds, get an error message, then this screen pops up.

**Comment by TheoW03** [comment]
update: this is a roblox issue 
not a Sober issue 
(i was worried lol)

**Comment by TheoW03** [comment]
https://downdetector.com/status/roblox/
