### ISSUE TITLE
Roblox preferences don't save if the Sober window is not closed using Roblox's leave option

### ISSUE THREAD

**Issue by Macosaro** [vinegarhq/sober#29]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Pressing ESC + L + ENTER then closing Roblox Player - preferences saved
Window closed in-game - preferences not saved
I don't know what else to add

**Comment by tunis4** [comment]
fixed in latest update
