### ISSUE TITLE
Crash if ClientAppSettings.json is invalid JSON

### ISSUE THREAD

**Issue by Ash882** [vinegarhq/sober#290]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

If the ClientAppSettings.json file is invalid is crashes with this error:
```
Failed to parse "/home/username/.var/app/org.vinegarhq.Sober/data/sober/exe/ClientSettings/ClientAppSettings.json"
Failed to prepare filesystem for app launch.
Could not set up application files.
```

My ClientAppSettings.json was empty at the time, checked after I removed a random " and it crashes as well.

Doesn't happen if the file doesn't exist (it recreates it).

It would probably be better to check if the file is invalid and then show the error to the user or just recreate the file.

**Comment by tunis4** [comment]
this is intended. showing the error to the user is too much work and we used to just recreate the file previously but people complained that their changes were disappearing. just dont make the json file invalid
