### ISSUE TITLE
Provide other packages

### ISSUE THREAD

**Issue by HeitorAugustoLN** [vinegarhq/sober#294]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

I don't want to use flatpak to use this application.

### Describe the Solution you'd Like

AppImage and .deb packages being provided

### Describe Alternatives you've considered

Making the source code available (in the future), so I can compile it myself

**Comment by kirbix12** [comment]
> Making the source code available (in the future), so I can compile it myself

Sober is closed source for a reason. They say this may change in the future, but they want to keep this running for as long as possible.

**Comment by HeitorAugustoLN** [comment]
> > Making the source code available (in the future), so I can compile it myself
> 
> Sober is closed source for a reason. They say this may change in the future, but they want to keep this running for as long as possible.

Yeah ik, but it is the only alternative I could think about.

**Comment by apprehensions** [comment]
https://sober.vinegarhq.org:

> Sober is unfortunately closed-source. This could change in the future.
