### ISSUE TITLE
Problems with installing the app.

### ISSUE THREAD

**Issue by Ellish-idk** [vinegarhq/sober#295]
Hi, this probably isn't an issue with Sober itself, but maybe something like my ISP blocking the site? Idk, but I just wanted to ask if you guys have any idea what's happening.

So the thing is: the site doesn't load without a vpn, and when I try to install the app (with both methods) it just... Sits there, doing nothing. Not even an error pops up. The terminal is blank, and the software center doesn't load the app.

When I was trying to install it, I was using Fedora 40 KDE.
Why do I always have to suffer more, than anyone else...

**Comment by apprehensions** [comment]
What happens when you visit the website (https://sober.vinegarhq.org and/or https://vinegarhq.org)? Could you show the terminal output? Where are you from?

**Comment by Ellish-idk** [comment]
When I visit both of these, the site just doesn't load, and gives the timeout error. The terminal output stays blank, it doesn't even give errors,

**Comment by Ellish-idk** [comment]
Gotta specify: it isn't exclussive to my laptop (the device I was using to fail to install Sober), it doesn't work for all of my devices.

**Comment by apprehensions** [comment]
Could you try https://gitlab.com/users/sign_in ?

**Comment by Ellish-idk** [comment]
Okay, it actually might be my ISP problem. I turned on my mobile internet, and the site loads just fine. I will try sharing it to my laptop, and connect to it (mobile internet) from there (laptop). Will tell if it works, or not.

**Comment by Ellish-idk** [comment]
Okay, it is installing.
![image](https://github.com/user-attachments/assets/bade11a3-ea46-4f4a-b76b-563bb9eda998)

**Comment by Ellish-idk** [comment]
I will just close this issue for now, just to not leave it hanging.
