### ISSUE TITLE
roblox crashing when i enter a experience

### ISSUE THREAD

**Issue by KensukeKurosaki** [vinegarhq/sober#299]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so far  i was enjoying undertale adventures and the minute i leave and rejoin sober crashs. im trying to fix it and it does not work i was in a grind8 and now i cantplay any other games

**Comment by Endercass** [comment]
>  I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

have you checked the issue right before yours?

**Comment by KensukeKurosaki** [comment]
> > I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.
> 
> have you checked the issue right before yours?

yea i have and when i reboot steam deck it just crashs allnthe time idk what to do

**Comment by KensukeKurosaki** [comment]
well i wasted my time ungreatful or not ima just not bother anymore roblox

**Comment by MxsonnGithub** [comment]
Dupe of  #297

**Comment by dumbkoifish1** [comment]
why is sober failing on all of us all of a sudden. i dowloaded waydroid earlier today ( before i got on sober for roblox ) and i thought it was bc of waydroid maybe interfesring but no..

**Comment by dumbkoifish1** [comment]
interfearing*

**Comment by KensukeKurosaki** [comment]
as a roblox undertale dev and austim aside.  i been playing roblox undertale FOR awhile and this is the thanks i get i been making ut roblox content FOR awhile and i never had any problems cuz this is stressing me out CLOSING this end of thread:/

**Comment by pyxfluff** [comment]
> why is sober failing on all of us all of a sudden. i dowloaded waydroid earlier today ( before i got on sober for roblox ) and i thought it was bc of waydroid maybe interfesring but no..

making a github account to complain about a roblox compat layer is WILD

**Comment by dumbkoifish1** [comment]
..i made the acc for waydroid.. i was trying something out.. why are u mad.. i want it to work like everyone else

**Comment by KensukeKurosaki** [comment]
> ..i made the acc for waydroid.. i was trying something out.. why are u mad.. i want it to work like everyone else

same thing roblox flatpak sober user right hwre i really wanna PLAy a game rn
