### ISSUE TITLE
My game keeps crashing

### ISSUE THREAD

**Issue by Aqua2101** [vinegarhq/sober#300]
### Acknowledgement of checking existent issues

- [ ] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't know why but my game keeps crashing when I try to play a game please try to fix this I love to play roblox on my steam deck its more fun then normal please fix it

**Comment by Endercass** [comment]
reading comprehension...

**Comment by kirbix12** [comment]
#297

**Comment by shardofgl4ss** [comment]
This is the same issue as [297](https://github.com/vinegarhq/sober/issues/297). Roblox released an update today for their android version, breaking the version check hard coded into the APK and causing crashes, or maybe breaking something else. Let the devs fix it, but for now, there's no harm in playing something else, or using Waydroid/qemu KVM.
