### ISSUE TITLE
[GUIDE, NOT A BR] Sober crash workaround

### ISSUE THREAD

**Issue by kirbix12** [vinegarhq/sober#302]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

(ignore the checkbox)

Condolences to V3L0C1T13S for this, kudos. <3

Since the workaround is basically just buried in the original thread, I'm just going to make a brand new thread instead because why not.
This is going to be up as long until Sober gets a patch.

Before proceeding:
**This guide only covers Sober quitting abruptly without warning when joining a game. All other issues (ex. Out of Memory, Vulkan issues, Wayland closing Sober) is irrelevant to this situation and should be reported separately.**

---

# Instructions:
- Run `sudo nano ~/.var/app/org.vinegarhq.Sober/data/sober/exe/ClientSettings/ClientAppSettings.json` on your terminal
- Paste the following FFlag as a new entry 
```
"FFlagEnableGameJoinContext2": false
```
(please see attached images for more expanded info)
- Press CTRL + O then ENTER
- Run Sober and play a game :)

![image](https://github.com/user-attachments/assets/ebc91b57-73ee-49c6-8aa8-7aff6bb02166)
![image](https://github.com/user-attachments/assets/9c1f025e-f28a-41a8-8b74-579b70251ae5)

**Comment by kirbix12** [comment]
(ignore the label too)

**Comment by ydrk** [comment]
W

**Comment by kirbix12** [comment]
**If inputting this manually, please pay attention to the images. If Sober does not launch, you did not pay attention to the instructions as described in the images.**

**Comment by KensukeKurosaki** [comment]
it says i need a password

**Comment by kirbix12** [comment]
> it says i need a password

That's part of the sudo process: You are temporarily entering as root. To access root, you need to enter your password to continue.

**Comment by KensukeKurosaki** [comment]
> > it says i need a password
> 
> That's part of the sudo process: You are temporarily entering as root. To access root, you need to enter your password to continue.

OH

**Comment by kirbix12** [comment]
This is to be sure it is able to be written when you attempt to save the json file.

**Comment by cyrus01337** [comment]
Could this config path be used as a solution to be PRed or is it more a workaround than a true fix?

**Comment by KensukeKurosaki** [comment]
nvm might as well wait for the Patch bc someone doesnt wanna tell me the password for my steam deck

**Comment by kirbix12** [comment]
> Could this config path be used as a solution to be PRed or is it more a workaround than a true fix?

Unfortunately, with Sober being closed source, issuing a PR is not possible. By the time the developers are active, they should already be alerted with the situation at hand, so yeah it's kinda more of a workaround than a fix.

**Comment by kirbix12** [comment]
> nvm might as well wait for the Patch bc someone doesnt wanna tell me the password for my steam deck

![Screenshot 2024-10-10 at 23 24 57](https://github.com/user-attachments/assets/d9057939-8108-4de7-8f0f-dd4ba4a3e7bf)

**Comment by KensukeKurosaki** [comment]
> > nvm might as well wait for the Patch bc someone doesnt wanna tell me the password for my steam deck
> 
> ![Screenshot 2024-10-10 at 23 24 57](https://private-user-images.githubusercontent.com/80133246/375615397-d9057939-8108-4de7-8f0f-dd4ba4a3e7bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTc0MTYsIm5iZiI6MTcyODYxNzExNiwicGF0aCI6Ii84MDEzMzI0Ni8zNzU2MTUzOTctZDkwNTc5MzktODEwOC00ZGU3LThmMGYtZGQ0YmE0YTNlN2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAzMjUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDQwMjEyZTRmODM3NzM1NzZiYzA4MmM4Mjk1Njk1NTE1NjNmYjdmMGI3ZGJlZTIxZmQzN2U2ZjdlMmNjODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2i-K-jpy89FVyal70aKThZeX4OIqDPwqkpYFTXl_zyE) well its odd bc my steam deck has one

**Comment by FarmFamGaming** [comment]
Just  made an account to say, thank you so much!

(Here is a tip for people stuck on password. Open terminal, type in passwd, and then you can type in a new password of your liking. You may have to do this)

I have a feeling this is intentional by Roblox. They have been giving Sober some troubles, and they just updated today :/

**Comment by FarmFamGaming** [comment]
> nvm might as well wait for the Patch bc someone doesnt wanna tell me the password for my steam deck

You'll have to go into terminal and type "passwd" and you will then go through the process of making one so you can continue. Don't know how or why there wasn't one built in to the steam deck.

**Comment by KensukeKurosaki** [comment]
> > nvm might as well wait for the Patch bc someone doesnt wanna tell me the password for my steam deck
> 
> You'll have to go into terminal and type "passwd" and you will then go through the process of making one so you can continue. Don't know how or why there wasn't one built in to the steam deck.

i changed it thing is when i put in sudo nano ~/ .var/app/org.vinegarhq.Sober/data/sober/exeClientSettings/ClientAppSettings.json it just didnt show anything

**Comment by ilovedti** [comment]
i did it and it didnt work

**Comment by ilovedti** [comment]
sober wouldnt open

**Comment by wizenedatom5485** [comment]
thank you so much. im not the greatest at this and this really helped. thanks

**Comment by ilovedti** [comment]
sober wont open?

**Comment by FarmFamGaming** [comment]
> > > nvm might as well wait for the Patch bc someone doesnt wanna tell me the password for my steam deck
> 
> > 
> 
> > You'll have to go into terminal and type "passwd" and you will then go through the process of making one so you can continue. Don't know how or why there wasn't one built in to the steam deck.
> 
> 
> 
> i changed it thing is when i put in sudo nano ~/ .var/app/org.vinegarhq.Sober/data/sober/exeClientSettings/ClientAppSettings.json it just didnt show anything
> 
> 

You put in exactly that? If so, there is a slash between exe and ClientSettings. If you did it right though, then something else is up. I'm not the best person to ask for stuff like this.

**Comment by ilovedti** [comment]
guys idk why but sober wont open after i reinstalled

**Comment by quuinnn** [comment]
> guys idk why but sober wont open after i reinstalled

add a comma on the line above
![image](https://github.com/user-attachments/assets/9f1dbf53-ce96-4bd8-abe9-25b208840b36)

**Comment by ilovedti** [comment]
i did

**Comment by ilovedti** [comment]
if i press sober it wont open at all

**Comment by quuinnn** [comment]
> i did
run "cat ~/.var/app/org.vinegarhq.Sober/data/sober/exe/ClientSettings/ClientAppSettings.json" in the terminal and paste the result here please

**Comment by ilovedti** [comment]
alright

**Comment by ilovedti** [comment]
![image](https://github.com/user-attachments/assets/42fa1070-daaf-40c3-a053-0263b40ec4dd)

**Comment by quuinnn** [comment]
> ![image](https://private-user-images.githubusercontent.com/184573451/375623852-42fa1070-daaf-40c3-a053-0263b40ec4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjA0OTQsIm5iZiI6MTcyODYyMDE5NCwicGF0aCI6Ii8xODQ1NzM0NTEvMzc1NjIzODUyLTQyZmExMDcwLWRhYWYtNDBjMy1hMDUzLTAyNjNiNDBlYzRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNDE2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTZiYjQ2YjExZmUyNGZjMWUxMjAxZjRmZmIzOGNlY2JiODIyNWYyNDFhODFhMWM4NmFjOGQwMzU5MTViYTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-OJw7IWSmyagsVGTdK8Hp8wN81L99i2IUKj0JLiSINA)

delete the line at the top

**Comment by ilovedti** [comment]
the fflagenablegamejoin thing?

**Comment by quuinnn** [comment]
yeah that thing

**Comment by ilovedti** [comment]
done then? it shows as txt its not editable

**Comment by quuinnn** [comment]
what do you mean by that? wait are you able to run the cat command again? btw the file is supposed to look like this.

``` json
{
    "DFFlagDisableDPIScale": true,
    "DFIntTaskSchedulerTargetFps": 0,
    "FFlagAdServiceEnabled": false,
    "FFlagDebugDisableTelemetryEphemeralCounter": true,
    "FFlagDebugDisableTelemetryEphemeralStat": true,
    "FFlagDebugDisableTelemetryEventIngest": true,
    "FFlagDebugDisableTelemetryPoint": true,
    "FFlagDebugDisableTelemetryV2Counter": true,
    "FFlagDebugDisableTelemetryV2Event": true,
    "FFlagDebugDisableTelemetryV2Stat": true,
    "FFlagEnableGameJoinContext2": false,
    "FFlagFixGraphicsQuality": true,
    "FFlagFutureIsBrightPhase3Vulkan": true,
    "FFlagGameBasicSettingsFramerateCap5": true,
    "FFlagHighlightOutlinesOnMobile": true,
    "FFlagHighlightsIntegratedWithGFX": false,
    "FFlagTextureDeduplicationByHash4": false,
    "FFlagUserHandleChatHotKeyWithContextActionService": true
}
```

**Comment by ilovedti** [comment]
it shows as normal txt when i put the cat command

**Comment by ilovedti** [comment]
if i put the sudo command it shows as tht then i follow the steps then i do ctrl o enter then wht do i do nxt

**Comment by ilovedti** [comment]
![image](https://github.com/user-attachments/assets/0a897d0f-a132-41fa-b7fe-75604e1fcb70)
wht do i press now?

**Comment by ilovedti** [comment]
thts after i press ctrl o enter

**Comment by quuinnn** [comment]
overwrite your file with my file here
[ClientAppSettings.json](https://github.com/user-attachments/files/17337736/ClientAppSettings.json)

**Comment by ilovedti** [comment]
wdym

**Comment by ilovedti** [comment]
i alr tried tht didnt work shuld i js wait for the devs to fix it?

**Comment by quuinnn** [comment]
download that file, then run the command `sudo rm ~/.var/app/org.vinegarhq.Sober/data/sober/exe/ClientSettings/ClientAppSettings.json` then after that, run `sudo cp ~/Downloads/ClientAppSettings.json ~/.var/app/org.vinegarhq.Sober/data/sober/exe/ClientSettings/`

**Comment by ilovedti** [comment]
IT WORKED TYSMMM

**Comment by ilovedti** [comment]
ILY I ALSO GOT IT TO WORK ON MY SIBLINGS LAPTOP

**Comment by quuinnn** [comment]
you're welcome :D

**Comment by ForestCranked** [comment]
can you get banned for doing this and playing games

**Comment by tunis4** [comment]
workaround automatically applied in new sober update

**Comment by kirbix12** [comment]
> you dont need to use sudo to edit that file as it isnt in the root directory or locked to only administrators. also this worked for me tysm

Well I wanted to be sure that users are able to write into the json regardless because who knows if it may be actually locked at any point.

**Comment by ilovedti** [comment]
guys my sober isnt opening again it said sober updated then its not opening what do i do?

**Comment by ilovedti** [comment]
guys my sober isnt opening again it said sober updated then its not opening what do i do?

**Comment by ilovedti** [comment]
guys my sober isnt opening again it said sober updated then its not opening what do i do?

**Comment by kirbix12** [comment]
> guys my sober isnt opening again it said sober updated then its not opening what do i do?

Repeat the instructions on the top of this thread. If it still doesn't open, either you have to go through reinstallation or you might have a different problem.

**Comment by kirbix12** [comment]
> is there a way to make this happen recursively? it seems like the new line is deleted every reboot.

No, and that is not true. The changes do happen, it's just every time Sober it booted, it will reorder the FFlags on the file.

**Comment by AccountWithoutALogic** [comment]
~~basically its roblox only quitting when joining a game? my roblox crashes after a few minutes of joining a server, even after inputting the fflag in the sober config~~ solved by using opengl in the config file
