### ISSUE TITLE
crashes when try play a game

### ISSUE THREAD

**Issue by Nickng1233** [vinegarhq/sober#303]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

ever time i try to play a game using sober it crashes
i don't no what i'm do in wrong

**Comment by TheoW03** [comment]
I have this same issue Idk T-T

**Comment by Nickng1233** [comment]
don"t mind my bad grammer

**Comment by Nickng1233** [comment]
don't mind my bad grammer
i don't know much english

**Comment by TheoW03** [comment]
https://github.com/vinegarhq/sober/issues/302

im going to give attention to this thread btw

**Comment by Nickng1233** [comment]
okay

**Comment by quuinnn** [comment]
same issue here

**Comment by quuinnn** [comment]
fixed it using this https://github.com/vinegarhq/sober/issues/302

**Comment by akshath197** [comment]
I also have same issue. I dont know what to do.

**Comment by zverxy** [comment]
+

**Comment by zverxy** [comment]
as well

**Comment by OstapTelychko** [comment]
Solution is in #302

**Comment by apprehensions** [comment]
Duplicate of #297
