### ISSUE TITLE
roblox crushing in starting game

### ISSUE THREAD

**Issue by druemae** [vinegarhq/sober#305]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

help please roblox crashes when i launch the game what to do?

**Comment by skoove** [comment]
why did you make another issue, check for duplicates next time, it even tells you to

**Comment by apprehensions** [comment]
No logs, no details given. Most likely a duplicate of #302
