### ISSUE TITLE
Sober doesn't start without logs

### ISSUE THREAD

**Issue by MakingPanorama** [vinegarhq/sober#306]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Used to run sober with flatpak command with `flatpak run org.vinegarhq.sober && sudo dmesg | grep sober`
No any output.
No logs in ~/.var/app/org.vinegarhq.Sober/

Sober doesn't starts itself indeed

CPU: Intel(R) Core(TM)2 Quad    Q9400 (4) @ 2.66 GHz
GPU: AMD Radeon R5 340 [Discrete]
DE: KDE Plasma 6.2

On Arch Linux

Tested on xorg and wayland

**Comment by ant-7802** [comment]
same issue

**Comment by k1yrix** [comment]
> same issue

Specifications? Verbose logs?

**Comment by tunis4** [comment]
you already made an issue about this in #280 and it was answered, your cpu is too old and doesn't support sse 4.2 which is necessary to run android roblox

**Comment by MakingPanorama** [comment]
so why sober doesn't run itself then? or it also has the same requirements?

**Comment by tunis4** [comment]
sober runs android roblox so it has the same requirements

**Comment by CourteousGeek** [comment]
```
cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping	: 10
microcode	: 0xa0e
cpu MHz		: 3996.952
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 7997.98
clflush size	: 64
cache_alignment	: 64
address sizes	: 38 bits physical, 48 bits virtual
power management:

```
Would like to see support for cpus without SSE4.2

**Comment by tunis4** [comment]
it is not possible. [the android x86_64 ABI requires SSE 4.2](https://developer.android.com/ndk/guides/abis#sa), which means it is also required by roblox's android x86_64 build, which means it is also required by sober.

**Comment by CourteousGeek** [comment]
x86 Build is an option right?

**Comment by ant-7802** [comment]
My cpu does have SSE 4.2, I have an i3-8130U laptop, cannot run vinegar.
