### ISSUE TITLE
Why does sober need access to Discord?

### ISSUE THREAD

**Issue by JustLad34534** [vinegarhq/sober#310]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/ccc46e94-48c7-45b5-9cc5-f8660981d161)
I am not entirely sure what the directories /run/user/XXXX/discord-ipc-0 and /run/user/XXXX/app/com.discordapp.Discord (yours may vary, run `echo $XDG_RUNTIME_DIR`)represent, but I sure don't see any need to access discord folders. Why are these permissions set?

**Comment by apprehensions** [comment]
If you searched up what they are, you would have known.

It is for Discord Rich Presence.
