### ISSUE TITLE
"Could not set up application files." error

### ISSUE THREAD

**Issue by Markolll** [vinegarhq/sober#314]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So basically I did "flatpak run org.vinegarhq.Sober" in terminal and this is what it showed.

Roblox installation is required, starting onboarding flow UI...
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 20:39:24.010: Error 71 (Protocol error) dispatching to Wayland display.
Roblox installation was not completed. This may be an issue with the UI service.
Roblox installation was not completed.
Could not set up application files.

my specs:

OS: Arch Linux x86_64
Kernel: 6.11.3-arch1-1
DE: Plasma 6.2.0
WM: kwin
CPU: 12th Gen Intel i5-12450H
GPU: NVIDIA GeForce RTX 4050 Mobile
RAM: DDR4 24gb 3200mhz

im currently on wayland

edit: I have tried reinstalling a bunch of times, and restarting pc, it no work.
edit 2: I have tried updating flatpak, and sober itself. The issue is not gone.

**Comment by s7ti** [comment]
will you teach me how to switch to x11? "linux beginner"
