### ISSUE TITLE
Add questions to the github

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#32]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

its not really for sober but i just wanted to ask a question but theres no question issue request or whatever

### Describe the Solution you'd Like

add a question issue request

### Describe Alternatives you've considered

use bug report to ask questions

### Additional context

btw, is there a way to check the changelog?

**Comment by apprehensions** [comment]
Discussions tab.

**Comment by Amgsdfyhadfgybi** [comment]
damn!!!!

**Comment by Amgsdfyhadfgybi** [comment]
wait where the fuck is the discussions tab bro

**Comment by apprehensions** [comment]
![20240805_200436](https://github.com/user-attachments/assets/94e998a1-2ae9-41fc-92f4-af4f3bfb74cc)

**Comment by Amgsdfyhadfgybi** [comment]
> ![20240805_200436](https://private-user-images.githubusercontent.com/47404953/355184852-94e998a1-2ae9-41fc-92f4-af4f3bfb74cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzg4NTAsIm5iZiI6MTcyMjg3ODU1MCwicGF0aCI6Ii80NzQwNDk1My8zNTUxODQ4NTItOTRlOTk4YTEtMmFlOS00MWZjLTkyZjQtYWY0ZjNiZmI3NGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE3MjIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjIwY2Y4Y2U0YTMwYTU1NjE4MzRhZmZmN2EzMmEyZmY2NmU1Zjg4MWJmYzhiMjI2MjlmNmViM2VkMTM0YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6nkcsjPa8sNu2zd4WZxCKODDsq4qfjK_gcECNUU0Ps0)

dont see it

**Comment by apprehensions** [comment]
It's there.

**Comment by Amgsdfyhadfgybi** [comment]
> It's there.
alright
