### ISSUE TITLE
Add ability to toggle textures on and off through config option.

### ISSUE THREAD

**Issue by Pierceisgone** [vinegarhq/sober#321]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

No issues, this is just a QoL feature request.

### Describe the Solution you'd Like

I would like to be able to toggle (E.g. through my Sober config) whether or not Roblox will have any textures/materials. Some Roblox FPS players like to disable any and all textures. Being able to easily do this with a config option would be nice.

### Describe Alternatives you've considered

It might be possible to just delete the textures from Roblox's files (Not sure if this is doable with an APK of Roblox) like people would do on Windows. However, I think they might be reinstalled per Roblox update, requiring them to be removed again.

Being able to toggle it once in your Sober config would be very convenient.

### Additional context

People may disable textures likely to try to get a performance boost, although some people might just like the look for some reason.

It should be noted, I am specifically talking about just default Roblox textures and the roblox default textures only. And not game specific textures/decals.

**Comment by apprehensions** [comment]
Sober has no configuration, only FFlags.
