### ISSUE TITLE
Cannot install Sober though Discover or Flatpak

### ISSUE THREAD

**Issue by UncleLabsTV** [vinegarhq/sober#322]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Upon trying to download, I am given the message "Aborted due to failure (While pulling app/org.vinegarhq.Sober/x86_64/master from remote sober: Server returned HTTP 404)".
And attempting to download from the flatpak though console gives the same 404 error. The reference file simply won't open.

**Comment by kirbix12** [comment]
Sober was recently been updated. It will take some time for the server to catch up.

I would just wait for a few more minutes before proceeding.

**Comment by UncleLabsTV** [comment]
> Sober recently had its GH pages branch updated. It will take some time for the web server to catch up.
> 
> I would just wait for a few more minutes before proceeding.

Ah, alright. Thank you for responding.
