### ISSUE TITLE
[Chrash] Attemptting to join to "Alone" quits silently

### ISSUE THREAD

**Issue by alejandro-alzate** [vinegarhq/sober#323]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It just chrases when you click the join button.
[2.639.0.688_20241013T175122Z_Player_d0c09_last.log](https://github.com/user-attachments/files/17356580/2.639.0.688_20241013T175122Z_Player_d0c09_last.log)

### Roblox Experience link

https://www.roblox.com/games/15595452055/Alone-A-Singleplayer-Adventure

**Comment by kirbix12** [comment]
> It just chrases when you click the join button.

Please update Sober. (`flatpak update` or `flatpak update org.vinegarhq.Sober`)

**Comment by alejandro-alzate** [comment]
Weird that `mintupdate` didn't told me about updates, it generally does (flatpaks included)
But yeah it's solved.
