### ISSUE TITLE
Random crash in Flee the Facility

### ISSUE THREAD

**Issue by totaltommygun** [vinegarhq/sober#325]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Just randomly crashed while playing, no idea what happened

[sysinfo.txt](https://github.com/user-attachments/files/17358123/sysinfo.txt)
[sober logs.log](https://github.com/user-attachments/files/17358132/sober.logs.log)

### Roblox Experience link

https://www.roblox.com/games/893973440/Flee-the-Facility

**Comment by tunis4** [comment]
see #183
