### ISSUE TITLE
crash out of memory on large map game

### ISSUE THREAD

**Issue by MidnightTale** [vinegarhq/sober#33]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Log: [2.636.0.626_20240805T151725Z_Player_c3c52_last.log](https://github.com/user-attachments/files/16499647/2.636.0.626_20240805T151725Z_Player_c3c52_last.log)

Video: https://file.hynse.net/public/media/rblx/2024-08-05%2022-16-36.mp4

Still have memory left but crash out of memory and small map is didn't crash out of memory seem like it happen after update before update didn't crash

### Roblox Experience link

https://www.roblox.com/games/9520328730

**Comment by ajd07** [comment]
Duplicate post
Same type of error happened with a similar card and was boiled down to a lack of VRAM. This is a GPU issue and not an issue with Sober itself.

**Comment by MidnightTale** [comment]
okay

**Comment by MidnightTale** [comment]
i got workaround remove  `nvidia`, `nvidia_modeset`, `nvidia_uvm`, and `nvidia_drm` from the MODULES /etc/mkinitcpio.conf didnt crash anymore.

**Comment by apprehensions** [comment]
Duplicate of #21
