### ISSUE TITLE
Sober does not open (Arch linux)

### ISSUE THREAD

**Issue by MunFaill** [vinegarhq/sober#334]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The app won't open even though it's reinstalled.

**Comment by kirbix12** [comment]
Can you provide any logs?

**Comment by GAbriel0123698** [comment]
Unfortunately I can't, because the application doesn't want to run, but I can provide details of my system:
 OS: Arch Linux - Rolling release GNOME: 47 Wayland Kernel: Linux 6.11.3-arch1-1 Nvidia drivers: 560.35.03 Cuda: 12.6

**Comment by kirbix12** [comment]
> Unfortunately I can't, because the application doesn't want to run, but I can provide details of my system: OS: Arch Linux - Rolling release GNOME: 47 Wayland Kernel: Linux 6.11.3-arch1-1 Nvidia drivers: 560.35.03 Cuda: 12.6

Have you tried deleting user data after reinstalling?

**Comment by GAbriel0123698** [comment]
Yes, i remove all the user data from Sober, and still wont working

**Comment by MunFaill** [comment]
> > Unfortunately I can't, because the application doesn't want to run, but I can provide details of my system: OS: Arch Linux - Rolling release GNOME: 47 Wayland Kernel: Linux 6.11.3-arch1-1 Nvidia drivers: 560.35.03 Cuda: 12.6
> 
> Have you tried deleting user data after reinstalling?

Yes, i remove all the user data from Sober, and still wont working

I recently updated the Arch Linux, I believe some package to work is more up to date than the application uses, or corrupted, but I don't believe it is corrupted because I re-installed the entire system and the problem remains.

**Comment by MunFaill** [comment]
> > Unfortunately I can't, because the application doesn't want to run, but I can provide details of my system: OS: Arch Linux - Rolling release GNOME: 47 Wayland Kernel: Linux 6.11.3-arch1-1 Nvidia drivers: 560.35.03 Cuda: 12.6
> 
> Have you tried deleting user data after reinstalling?

Yes, i remove all the user data from Sober, and still wont working

I recently updated the Arch Linux, I believe some package to work is more up to date than the application uses, or corrupted, but I don't believe it is corrupted because I re-installed the entire system and the problem remains.
