### ISSUE TITLE
Cannot exit out of whisper

### ISSUE THREAD

**Issue by ajd07** [vinegarhq/sober#34]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Attempting to backspace out of whisper in chat will result in nothing.
You're meant to be able to just backspace out of it!

**Comment by ryand56** [comment]
You can just click on the whisper name in the chat box to exit out of it, but still this needs a fix

**Comment by km9l** [comment]
https://github.com/vinegarhq/sober/issues/99#issuecomment-2293935804
