### ISSUE TITLE
How would one uninstall the current roblox APK assosiated?

### ISSUE THREAD

**Issue by fgjthecoder** [vinegarhq/sober#341]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

None.

### Describe the Solution you'd Like

A clear way of removing the current version that on Sober.

### Describe Alternatives you've considered

None, since there isn't one.

### Additional context

I have deleted all Sober files, vinegar files, it's still there.

**Comment by apprehensions** [comment]
Vinegar's files are not associated with Sober.

I [assume](https://xyproblem.info/) you want to uninstall the APK to install another one, and to do that, run this command:
```
flatpak run org.vinegarhq.Sober --bootstrap
```
Otherwise, to properly delete Sober's app data (which I assume you haven't, only uninstalled the Sober itself):
```
rm -rf ~/.var/app/org.vinegarhq.Sober
```

**Comment by fgjthecoder** [comment]
I was yeah, thanks for the help.

**Comment by apprehensions** [comment]
Because it seems you chose the option of fetching and installing Roblox.

**Comment by fgjthecoder** [comment]
is there anyway to force install a unsupported apk? without the x86_64 files

**Comment by apprehensions** [comment]
No. Downgrade Sober.

**Comment by tunis4** [comment]
no
