### ISSUE TITLE
Sober only launches first time, wont launch again until reboot

### ISSUE THREAD

**Issue by WindClan** [vinegarhq/sober#342]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober launches the first time of a boot just fine but crashes all other times with the log line `FATAL: 18576965271` and no other indication of problem. This happens right after it prints `Window size: 1440x900`

**Comment by WindClan** [comment]
Hm it tried to use OpenGL, I had to add a line to prefer vulkan to the fflags. weird

**Comment by tunis4** [comment]
what? sober doesnt try to use opengl by default, if you arent passing --opengl it will only use vulkan. can you send the entire log
