### ISSUE TITLE
[OpenGL] Menu windows rendering blank while menu renders partialy on main screen

### ISSUE THREAD

**Issue by stalkernaut** [vinegarhq/sober#344]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When using OpenGL certain menus do not render. on its own window this includes the "Save to Roblox" menu (renders as a black screen), "Save to Roblox as" menu (also renders as a black screen), & the starting menu (renders as a white screen). this might include even more, these are just the ones i have noticed. no errors are given to the console when this happens

the save to file menus work fine though

I am running on arch linux with nvidia proprietary GPU drivers. if that helps narrow down what it might be
![image](https://github.com/user-attachments/assets/4056eee8-9e92-4ceb-87b4-04ed45230039)

**Comment by reflexran** [comment]
Wrong repository, this is an issue to tracker for Sober, not Vinegar.

this is what you're looking for: https://github.com/vinegarhq/vinegar/

**Comment by reflexran** [comment]
Also, Roblox Studio no longer support OpenGL, use Vulkan if your gpu supports it.
