### ISSUE TITLE
low fps and lag spikes on sober

### ISSUE THREAD

**Issue by hdgetban** [vinegarhq/sober#35]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i installed sober and tested out some games and it has massive lag spikes and frame skips and averaging 40 fps
![image](https://github.com/user-attachments/assets/30ba265b-75b0-4510-a63e-d41a0dce7de7)

**Comment by Amgsdfyhadfgybi** [comment]
in the app's site, its very well described that this is in beta and that its performance is 1/3 of performance on windows

**Comment by hdgetban** [comment]
hm is there other way to fix it or no

**Comment by Amgsdfyhadfgybi** [comment]
it will probably be fixed in future updates, thats if roblox doesnt acknowledge this and blocks it

**Comment by Amgsdfyhadfgybi** [comment]
so i dont think its gonna be fixed anytime soon

**Comment by apprehensions** [comment]
> that its performance is 1/3 of performance on windows

This is now out of date. Sober has more performance than Windows. It is most likely issue OP has a bad computer.

**Comment by Amgsdfyhadfgybi** [comment]
oh alright

**Comment by Amgsdfyhadfgybi** [comment]
well its still kind of weird, when i used to use windows. i ran games on 140-240 fps.
and now when a lot of things are happening in the game, it lags a bit

**Comment by hdgetban** [comment]
well does that mean i cant fix this issue ? and i have to wait for them to improve it

**Comment by Amgsdfyhadfgybi** [comment]
i dont know, its probably just a issue with your pc

**Comment by hdgetban** [comment]
i fixed it since cachyos was not good i used linux mint 22 and it fixed everything i am getting 240 fps on arsenal

**Comment by Amgsdfyhadfgybi** [comment]
oh alright

**Comment by Amgsdfyhadfgybi** [comment]
> i fixed it since cachyos was not good i used linux mint 22 and it fixed everything i am getting 240 fps on arsenal

also did u do anything extra, or did u JUST install linux mint 22

**Comment by hdgetban** [comment]
Nah I just installed it

**Comment by Laitinlok** [comment]
It's getting laggy because of the shaders being extremely large and needs to be downloaded from the server. After downloading the shaders it is fast.

**Comment by Amgsdfyhadfgybi** [comment]
> It's getting laggy because of the shaders being extremely large and needs to be downloaded from the server. After downloading the shaders it is fast.

what shaders

**Comment by Laitinlok** [comment]
> > It's getting laggy because of the shaders being extremely large and needs to be downloaded from the server. After downloading the shaders it is fast.
> 
> 
> 
> what shaders

Shaders and assets from Roblox.
