### ISSUE TITLE
Launching from browser doesn't do anything

### ISSUE THREAD

**Issue by Alum1n** [vinegarhq/sober#352]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober simply doesn't open and gives no logs.

https://github.com/user-attachments/assets/e99ba835-dc73-4c79-920e-576e9b7dac07

**Comment by Dunghun111** [comment]
May be try running sober from this path instead: `~/.local/share/flatpak/app/org.vinegarhq.Sober/current/active/export/bin/org.vinegarhq.Sober`

**Comment by Alum1n** [comment]
> May be try running sober from this path instead: `~/.local/share/flatpak/app/org.vinegarhq.Sober/current/active/export/bin/org.vinegarhq.Sober`

Solved it
