### ISSUE TITLE
Update client to include modern GUI/UI features

### ISSUE THREAD

**Issue by ERROR2401** [vinegarhq/sober#355]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

When The Haunt event started, I had no idea how I would take captures. I found out that this was because the GUI and such of the in-game and out-of-game menus and such were actually outdated. Chat is now called something different, there's a whole new menu section called "captures" in the in-game roblox menu, the "open chat" Icon is different, and is connected to a "burger menu icon", and potentially more. All these differences additionally apply to the mobile client as well. 

### Describe the Solution you'd Like

Update the UI and such of the client to match that of the current Windows version of the client, in and outside of experiences.

### Describe Alternatives you've considered

I have not considered any alternatives, as there isn't really alternative solutions to this if something were to be done about this.

### Additional context

The reason I could compare the two clients is because I do in fact have a windows laptop, however the laptop is terribly weak, at least for running the roblox client, so I prefer to use my steam deck, as it runs quite literally many times better on it, but the haunt event requiring the capture feature is what made me try joining games on the official windows client again.

**Comment by tunis4** [comment]
client is up to date now
