### ISSUE TITLE
Triggers not working on deck

### ISSUE THREAD

**Issue by Taboulet** [vinegarhq/sober#356]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

On gaming mode my triggers (the upper ones too) just don't work. This seems to be an issue related to steam input and sober cause even if i map "right trigger" or any other controller trigger to any other button it doesn't work at all. 
So what i mean is : "Right controller trigger" "Left controller trigger" "Upper Right controller trigger" and "Upper Left controller trigger" doesn't do anything in Sober

**Comment by Taboulet** [comment]
Nvm the normal trigger works, only the upper trigger don't

**Comment by ERROR2401** [comment]
I'm on steam deck, too, and the triggers and the bumpers both work for me

**Comment by Taboulet** [comment]
Strange, even if i set the high triggers to anything like the A button it would still don't work

**Comment by Taboulet** [comment]
Nvm they do work; it's an issue with a specific game. Ps 99 (https://www.roblox.com/games/8737899170) and pets go (https://www.roblox.com/games/18901165922)

**Comment by tunis4** [comment]
if it only happens in those specific games it's probably not sober's fault and those games just don't properly support controller input
