### ISSUE TITLE
Multiple rendering options

### ISSUE THREAD

**Issue by NetherGonnaGiveUp** [vinegarhq/sober#357]
I really wish Sober could at least support OpenGL 4.2 because I don't have vulkan driver and it's pain in the ass to run on Windows, hence Linux is my only option. 

I know that adding OpenGL support is pain in the ass, but it would be great since that means almost anyone can run Roblox without compatibility issues.

If you can't or refuse to add this feature, it's allright, but can you guide me on how to use GrapeJuice? I can't make it to work for some reason (yes maybe because my GPU can't Vulkan).

**Comment by tunis4** [comment]
`flatpak run org.vinegarhq.Sober --opengl`
