### ISSUE TITLE
error 502 api 0 internal server error

### ISSUE THREAD

**Issue by KensukeKurosaki** [vinegarhq/sober#362]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

for some reason i got this error once after my steam deck had a heat crash 

### Roblox Experience link

https://www.roblox.com/games/5951002734/Project-Baki-3

**Comment by KensukeKurosaki** [comment]
for now im just gonna gtg

**Comment by lunarlattice0** [comment]
There was an outage on Roblox servers 2 days ago, unrelated to sober.
