### ISSUE TITLE
Random, erratic crashes (Fedora 40, nVidia)

### ISSUE THREAD

**Issue by IcicleTheWeavile** [vinegarhq/sober#363]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

nVidia 1070ti GPU, AMD Ryzen 7 2700X CPU, Fedora 40, Wayland

At completely random intervals, Sober crashes, or occasionally only the window crashes while the audio and the process continue until killed via system monitor.

Any logs of this happening all show the following -

```
--- Running report_uReport ---
Error: Unable to open './coredump': No such file or directory

--- Skipping collect_GConf ---
No matching actions found for this event.

--- Skipping collect_vimrc_system ---
No matching actions found for this event.

--- Skipping collect_vimrc_user ---
No matching actions found for this event.

--- Skipping collect_xsession_errors ---
No matching actions found for this event.

--- Running analyze_CCpp ---
Generating backtrace
Backtrace is generated and saved, 66720 bytes
Can't open file 'component' for reading: No such file or directory

--- Running analyze_BodhiUpdates ---
Looking for similar problems in bugzilla
```

**Comment by IcicleTheWeavile** [comment]
UPDATE: The crashes occur only while my controller's plugged in! An "XBox Wireless Controller".

**Comment by IcicleTheWeavile** [comment]
UPDATE:  Apparently, the crashes don't _only_ occur when my controller's plugged in, it just seems that they happen more often when it is.

**Comment by IcicleTheWeavile** [comment]
UPDATE:

**Comment by IcicleTheWeavile** [comment]
nvm lol

**Comment by tunis4** [comment]
where did you get that log from? it doesnt look like a log at all. can you find one with the crash in `~/.var/app/org.vinegarhq.Sober/data/sober/sober_logs/` instead

**Comment by IcicleTheWeavile** [comment]
The log was from Gnome's dedicated crash handler, let me run an instance, wait for the crash and send the log from where you pointed out.

**Comment by IcicleTheWeavile** [comment]
[2024-10-28_22-32-26.log](https://github.com/user-attachments/files/17549107/2024-10-28_22-32-26.log) is a log detailing an occurrence of the "half crash" where the window closes but the process still continues, while
[2024-10-28_22-41-28.log](https://github.com/user-attachments/files/17549134/2024-10-28_22-41-28.log) is from a process that crashes along with the window closing.
I thought with my limited knowledge that the crash handler would be a bridge between the app and the logs, serving to be of some use at least, but that wasn't so
I'm guessing the problem has to do with those abundant Vulkan Errors I'm reading toward the end of each log?

**Comment by tunis4** [comment]
try running `flatpak override --user --socket=x11 org.vinegarhq.Sober`

**Comment by IcicleTheWeavile** [comment]
It worked, at least for now, but do you mind telling me (vaguely) what the fix is?

**Comment by reflexran** [comment]
> It worked, at least for now, but do you mind telling me (vaguely) what the fix entails?

It forces Sober to use Xwayland

**Comment by IcicleTheWeavile** [comment]
[2024-10-29_19-21-55.log](https://github.com/user-attachments/files/17561594/2024-10-29_19-21-55.log)
It crashed again, but this time it doesn't seem to be the same kind of Vulkan error. And also, it crashed after an impressive few hours of gameplay.

**Comment by IcicleTheWeavile** [comment]
It is late, your suggested fix seems to be working so far, I'll come back likely tomorrow with more info to relay about any occurring crashes.

**Comment by IcicleTheWeavile** [comment]
MY LE FRAMES.... THEY'RE LE GONE /J
