### ISSUE TITLE
Sober 'unsupported GPU'

### ISSUE THREAD

**Issue by pawxed** [vinegarhq/sober#367]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober having issue to render (AKA Not able to render vulkan, or find the iGPU)
It managed to run vkcube, maybe theres i did wrong? This is fresh install of sober, and i installed fedora a couple days ago
Does sober does not support iGPU? Thats what i assume is the case

![Screenshot from 2024-10-29 04-17-12](https://github.com/user-attachments/assets/98939a66-3b49-4aae-8b7f-20b47ae6c0ee)

**Expected behavior: Launching the game, and managed to find the GPU**

Specs: intel core i5 m430 (with iGPU)
6gb of ddr3 ram
500gb hdd

**Comment by Nikoiogy** [comment]
Try running `flatpak update`

**Comment by JII060** [comment]
Your GPU does not support Vulkan, the vkcube terminal shows it is running on the CPU.

As the error suggests you should look for a driver that adds support.

**Comment by AceVR12** [comment]
You have a bad driver, or gpu. Open source drivers do that to me. Make sure you are running the latest official driver and if that doesnt work then you should get a older one.

**Comment by pawxed** [comment]
> Try running `flatpak update`

Have tried that also 

> You have a bad driver, or gpu. Open source drivers do that to me. Make sure you are running the latest official driver and if that doesnt work then you should get a older one.

Already using open source driver too

> Your GPU does not support Vulkan, the vkcube terminal shows it is running on the CPU.
> 
> As the error suggests you should look for a driver that adds support.

Yes i know, so my question was correct that sober doesn't support iGPU (integrated GPU)

**Comment by Nikoiogy** [comment]
This doesn't help, but I know it works on iGPU because my laptop is able to run sober just fine. You can also try disabling Wayland windowing system as it has reduced crashes (Install Flatseal).
![image](https://github.com/user-attachments/assets/db1e513d-dd05-45bb-8f95-31944a6d2e95)

**Comment by pawxed** [comment]
> This doesn't help, but I know it works on iGPU because my laptop is able to run sober just fine. You can also try disabling Wayland windowing system as it has reduced crashes (Install Flatseal). ![image](https://private-user-images.githubusercontent.com/59452769/380972915-db1e513d-dd05-45bb-8f95-31944a6d2e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNzk4MTgsIm5iZiI6MTczMDE3OTUxOCwicGF0aCI6Ii81OTQ1Mjc2OS8zODA5NzI5MTUtZGIxZTUxM2QtZGQwNS00NWJiLThmOTUtMzE5NDRhNmQyZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA1MjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZjUxYmNlMWE3YzM5NjZjMGUyYWNhOTg5ODYxMzFmZGNmNTA0Nzg5NGQwZTgxNmIwYjlmY2FkMjViZGEzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JRaHu7d5HRykdQmcScvobgHyIvPs-CZe3Wf8cubqwXw)

Forgot to mention i was using xorg this whole time, i managed to run roblox fine in waydroid (with weston because waydroid doesn't support xorg) this possibly means it's sober itself having some kind of weird issue, not sure how i should be able to fix it but running waydroid is definitely enough for me

![Screenshot from 2024-10-29 12-28-22](https://github.com/user-attachments/assets/049736e6-cf30-472d-9654-ab5809ea18f4)

**Comment by Nikoiogy** [comment]
You can try running it with `flatpak run org.vinegarhq.Sober --opengl` you will probably run into performance issues but if Waydroid is working fine then that's great.

**Comment by pawxed** [comment]
> You can try running it with `flatpak run org.vinegarhq.Sober --opengl` you will probably run into performance issues but if Waydroid is working fine then that's great.

Didn't knew sober could run with opengl, it launched perfectly fine! Performance appears to be the same as the one i did with waydroid,, i figured that waydroid was probably using the opengl engine instead of vulkan judging by it's performance,, I appreciate your help alot !! 

![Screenshot from 2024-10-29 20-27-34](https://github.com/user-attachments/assets/b0bc3671-d9a0-4257-8f65-50013788e4c6)

**Comment by pawxed** [comment]
I'm going to close this issue, thank you for the people who helped me out! !

**Comment by Nikoiogy** [comment]
Lul, no problem. They added OpenGL ES support like literally 3-4 hours ago.

**Comment by pawxed** [comment]
> Lul, no problem. They added OpenGL ES support like literally 3-4 hours ago.

OH,, i guess they did see my reports
