### ISSUE TITLE
Error code 280 when trying to play a game

### ISSUE THREAD

**Issue by theodedecker9** [vinegarhq/sober#368]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to play a Roblox game, I get the error code 280 saying that my client is out of date. I have already ran `flatpak update`, but it does not fix the error.

**Comment by ilovedti** [comment]
dy guys know how to fix this?

**Comment by MiningTcup** [comment]
Sober is currently broken and will probably be fixed tomorrow. Try Waydroid. Please check other issues and the Discord server before posting.
