### ISSUE TITLE
segfault in certain Roblox games

### ISSUE THREAD

**Issue by Macosaro** [vinegarhq/sober#37]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober segfaults upon loading into certain games (links below)

### Roblox Experience link

https://www.roblox.com/games/5032892136/An-Infinite-Road-Trip
https://www.roblox.com/games/2091563160/Bus-Simulator

**Comment by apprehensions** [comment]
Please supply logs.

**Comment by Vlad55432** [comment]
same here
https://github.com/vinegarhq/sober/issues/22#issuecomment-2267651352

**Comment by tunis4** [comment]
fixed
