### ISSUE TITLE
how to update sober?

### ISSUE THREAD

**Issue by druemae** [vinegarhq/sober#379]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

There’s something wrong with my Roblox, it says update Roblox and try again, I updated it, the same thing pops up, what should I do?

**Comment by kirbix12** [comment]
Run `flatpak update` on your terminal or check for updates in your software store

**Comment by druemae** [comment]
THANK YOU SO MUCH))))

**Comment by TrainzMarcel** [comment]
so sorry im posting on a closed issue, but im having the same problem and when i run flatpak update it simply says "nothing to do" yet sober is still saying its outdated
![image](https://github.com/user-attachments/assets/f6e4f718-28d7-4a07-8c0b-867a7f557278)

**Comment by tunis4** [comment]
try uninstalling and reinstalling sober

**Comment by TrainzMarcel** [comment]
i have of course tried that even with deleting the stuff in the home directory and it still does not work

**Comment by TrainzMarcel** [comment]
i tried again and it has worked this time!! thanks for everything

**Comment by LeoTheGuuy** [comment]
I tried every method on this page and it still does not work, is there another way to update Sober?
