### ISSUE TITLE
[BRO I ACCIDENTALLY SUBMITTED IT] [IGNORE]

### ISSUE THREAD

**Issue by osceyconWT** [vinegarhq/sober#384]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i tried it in several games and all of them crashed when escape menu was opened. 
here's my console:

**Comment by Clyde6790pGIT** [comment]
close the issue??

**Comment by IcicleTheWeavile** [comment]
this one made me laugh
