### ISSUE TITLE
Crash: OutOfMemoryGraphics

### ISSUE THREAD

**Issue by r4sso** [vinegarhq/sober#387]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't know if this was intended behaviour, it will crash when i join certain experience. It's say `OutOfMemoryGraphics`. 

### Solution 
The only solution i can find is restarting my window manager.  It should free the video memory, and don't launch other applications beside sober in the background (e.g. browser).

Logs:
```
2024-10-30T02:57:10.755Z,20.755884,2ea006c0,6 [LOGCHANNELS + 1] RBXCRASH: OutOfMemoryGraphics (Failed to allocate memory. size = 3918336, alignment = 1024)
RBXCRASH: OutOfMemoryGraphics (Failed to allocate memory. size = 3918336, alignment = 1024)
```

**Comment by tunis4** [comment]
https://github.com/vinegarhq/sober/issues/175#issuecomment-2313673355

**Comment by r4sso** [comment]
Fixed, thanks.
