### ISSUE TITLE
Roblox won't launch in experiences on the version Sober is supposed to be on a old version to run, and it doesn't run

### ISSUE THREAD

**Issue by Tyler990** [vinegarhq/sober#388]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it keeps saying roblox may be out of date on Sober linux

**Comment by tunis4** [comment]
run `flatpak update`

**Comment by ArchUser02** [comment]
Use `flatpak update`

If doesn't work, reinstall sober.
