### ISSUE TITLE
Add support for multiple session at once

### ISSUE THREAD

**Issue by Taboulet** [vinegarhq/sober#390]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Kinda, i need multiple session to use multiple alts but i can't on sober

### Describe the Solution you'd Like

Being able to choose which account to launch (like an alt manager) and being able to launch multiple session of sober at once

### Describe Alternatives you've considered

I tried using android emulators to have multiple alt but just launch a second session is hard and a third one don't work

### Additional context

I don't think this will be added but i'm posting it anyway, thanks for reading :D

**Comment by tunis4** [comment]
won't be supported since roblox considers it to be malicious usage

**Comment by Taboulet** [comment]
Okay thanks anyway
