### ISSUE TITLE
Just started sober on Kubuntu 24.10 KDE Plasma 6.1 X11. The window frame is there but the app is not?

### ISSUE THREAD

**Issue by zleeepy** [vinegarhq/sober#395]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I started sober and the frame of the app was there, but  the app isnt there.

System

Kubuntu 24.10
KDE Plasma 6.1
X11

I have my Nividia Drivers installed aswell.

**Comment by sheepdotcom** [comment]
Currently having the exact same issue, I also updated my nvidia drivers today, and I have noticed a few other problems so it could be driver related.

**Comment by zleeepy** [comment]
I fixed it

**Comment by zleeepy** [comment]
I just reinstalled Sober

**Comment by sheepdotcom** [comment]
Reinstalling also worked for me.
