### ISSUE TITLE
Can't open two sober windows in same or different workspace.

### ISSUE THREAD

**Issue by SomeRandomRobloxPLayer** [vinegarhq/sober#396]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't know if this feature is added but I would really like to be able to play twice my accounts at same time
If i try to, it just doesn't open :( .

( i have Debian btw :)  )

**Comment by adverbialsatz** [comment]
That doesn't matter. Roblox considers it to be malicious, so we have to listen. There's no point in bargaining.
