### ISSUE TITLE
Sober runs at low resolution

### ISSUE THREAD

**Issue by JecasFrank** [vinegarhq/sober#397]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Good evening. Several days ago I installed Sober on Nobara os (Kde edition) and for some reason it runs in much lower resolution, than my monitor. Is there any way to fix it?

**Comment by zleeepy** [comment]
Same thing happens for me, i put it in full screen at it seemed to be a bit better?

**Comment by JecasFrank** [comment]
Nope, it still looks bad

> Same thing happens for me, i put it in full screen at it seemed to be a bit better?

Unfortunately it still looks bad

**Comment by any444v** [comment]
This is because of HIDPI, same problem on android devices. Not a sober issue

**Comment by JecasFrank** [comment]
> This is because of HIDPI, same problem on android devices. Not a sober issue

Great, but how to fix it?

**Comment by JecasFrank** [comment]
Never mind, problem fixed itself
