### ISSUE TITLE
Can't Join Private Server In Server Page

### ISSUE THREAD

**Issue by MChocoCreep** [vinegarhq/sober#398]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

In All games i want join in my private server, i can't join. I need to join my friends to join private server and Blox Fruit, if i want to join my friend. He can't and show me the Code Error : 773
![2024-10-25_05-25](https://github.com/user-attachments/assets/37ecba3d-172f-4185-be1c-70b51e8e9bc7)

**Comment by tunis4** [comment]
join from the roblox website instead

**Comment by MChocoCreep** [comment]
> join from the roblox website instead

i try but it doesn't launch sober. How i can ? i'm on Steam Deck

**Comment by MChocoCreep** [comment]
I try it, and nothing -_-

**Comment by MChocoCreep** [comment]
Okay, it's good now. I install Edge for that

**Comment by akeboshi1210** [comment]
I have same problem. What did u do? Sorry for bad english

**Comment by MChocoCreep** [comment]
> I have same problem. What did u do? Sorry for bad english

For join private server, you need to close Sober, go to Roblox Website, join your private server with Roblox Website and if sober is the only roblox app. He launch it in the private server you select but if he doesn't launch Sober. You need to use an other app like Chrome, Edge etc because, it say you choose an app when you launch Roblox with Website which doesn't Sober. Sorry, i don't have a good english

**Comment by malkavianicjr** [comment]
For me it doesnt even launch if i use the browser it doesnt recognize Sober

**Comment by StarLion5854** [comment]
set the default roblox app to start as sober when launching through the website
