### ISSUE TITLE
Sober on the arm64/arm architecture 

### ISSUE THREAD

**Issue by awesomefroggy29** [vinegarhq/sober#399]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

When I attempted to do this on something like a raspberry pi (I was using an orange pi because it is faster), when I try to install it, the software app says file not supported. 

### Describe the Solution you'd Like

I would love it if the people making this project could give support for the arm architecture because it would open up way more opportunities for people using single board computers, or any computer with the arm architecture. And I do not know how hard it would be to integrate this, but I do know that Roblox natively supports android and apple phones, which almost all use the arm architecture. 

Thank you.

### Describe Alternatives you've considered

Software on arm does not support the flatpak provided.

### Additional context

I have tested on a Chromebook with arm processor and orange pi 5 plus

**Comment by tunis4** [comment]
https://github.com/vinegarhq/sober/issues/346#issuecomment-2442454805
