### ISSUE TITLE
Low game resolution when using fractional scaling under Wayland

### ISSUE THREAD

**Issue by kichirouhoshino** [vinegarhq/sober#4]
OS: EndeavourOS (Arch Linux)
DE: KDE Plasma 6.1.3

Running the game under X11 fixes this by using flatseal to disable Wayland.

**Comment by km9l** [comment]
SDL2 doesn't handle fractional scaling well.. we have stumbled on this problem before the public release, and our fix didn't work
i assume SDL3 properly handles fractional scaling, but the first stable release (3.2.0) isn't out yet

**Comment by km9l** [comment]
relevant issue: https://github.com/libsdl-org/SDL/issues/6438

**Comment by km9l** [comment]
and the relevant pr: https://github.com/libsdl-org/SDL/pull/5906
looks like it was added in SDL3, so we do need SDL3
closed until SDL 3.2.0 release

**Comment by km9l** [comment]
trolled, we just ported sober to sdl3, it will now support fractional scaling in the next update
having displays with different scales or changing the scale while sober is running might not be stable

**Comment by km9l** [comment]
KDE should work now however i am getting reports that GNOME has slight blur
this mutter bug is probably relevant
https://gitlab.gnome.org/GNOME/mutter/-/issues/3517

**Comment by kichirouhoshino** [comment]
Still seems to be blurry here in KDE Plasma. But at least HiDPI is working, even in X11.

**Comment by km9l** [comment]
> Still seems to be blurry here in KDE Plasma. But at least HiDPI is working, even in X11.

may you run `flatpak update` just to make sure you're on the latest, and send a screenshot of the blur

> On KDE Plasma, known workaround is forcing Sober to use X11, and making sure you have set "Apply scaling themselves" in System Settings > Display and Monitor > Display Configuration, though there's nothing you can do on GNOME as of the time of writing.

is the blur also in X11? doesnt that disable scaling?

**Comment by Jayden295** [comment]
Not the same person but...

> may you run `flatpak update` just to make sure you're on the latest, and send a screenshot of the blur also send your resolution and your scaling

Using Sober 0.0.0-1e0cc40

My screen resolution: 1920x1080 with 125% scaling

On Wayland

![Bildschirmfoto_20241205_201142](https://github.com/user-attachments/assets/a9f2ece6-c691-4ec6-82a3-270be621292e)

> > On KDE Plasma, known workaround is forcing Sober to use X11, and making sure you have set "Apply scaling themselves" in System Settings > Display and Monitor > Display Configuration, though there's nothing you can do on GNOME as of the time of writing.
> 
> is the blur also in X11? doesnt that disable scaling?

When using the workaround, it seems to disable scaling since my Roblox looks smaller, but it doesn't look blurry.

If System Settings > Display and Monitor > Display Configuration is set to "Scaled by the system" (not using workaround), it gets the same blurriness as in Wayland.

![Bildschirmfoto_20241205_202522](https://github.com/user-attachments/assets/c2ecbb15-10ab-4d35-a992-3377226dd172)
On X11 without workaround.

**Comment by tunis4** [comment]
@Jayden295 this is a very old issue, we removed scaling again at some point because it was quite broken. it will be added back in the next update, but disabled by default since it still has some issues so you will have to set a config option to enable it

**Comment by rfl890** [comment]
maybe try https://github.com/libsdl-org/sdl2-compat?

**Comment by Syntist** [comment]
SDL 3.2 has been released, Is there way to disable scaling? so I can get 1:1 resolution, Like my display is 2560x1440 (125% Scale) and sober resolution is 2048x1152. I want it to display as 2560x1440.
