### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by johron** [vinegarhq/sober#403]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm on Fedora 41 KDE Plasma 6.2.2 Wayland. RTX 3060 Ti, AMD Ryzen 5 3600 and i get random crashes every time i play. I have not tested any other games than Lumber Tycoon 2 i have tried unplugging my microphone (as this was a possible fix for normal roblox client), lowering graphics quality. This is the first time i have encountered these problems, but this is the first time in a while i have been using Sober, last time was around release of Sober. I recently changed desktop environment from Gnome to KDE, but i do not know if this is significant.

https://gist.github.com/johron/fadf053fa3692b28387624f25d576554

### Roblox Experience link

https://www.roblox.com/games/13822889/Lumber-Tycoon-2

**Comment by reflexran** [comment]
Using Xwayland should fix this,

install flatseal then open it and select sober and then disable `wayland windowing system`

**Comment by johron** [comment]
Thank you very much!
