### ISSUE TITLE
New audio api not working through Sober

### ISSUE THREAD

**Issue by goober0013** [vinegarhq/sober#404]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The new [Audio API](https://devforum.roblox.com/t/new-audio-api-beta-elevate-sound-and-voice-in-your-experiences/2848873) does not work.

This issue is occurring in the linked game (my game) to all sounds produced with the new Audio API. In my game I am using `AudioPlayer`, `AudioEmitter`, `AudioReverb`, `AudioEcho`, and `Wire` so these may be the instances causing my issue.

[rbx.zip](https://github.com/user-attachments/files/17612517/rbx.zip)
(Zip file containing place file)

Other players who join the game using a Windows client are actually hearing the sounds, confirming it is a Sober issue.

### Roblox Experience link

https://www.roblox.com/games/17700991469/goobs-driving-sim

**Comment by tunis4** [comment]
check if it works after updating

**Comment by goober0013** [comment]
Roblox no longer deaf
Resolved, thank you!
