### ISSUE TITLE
Occasionally Displaying Mobile UI

### ISSUE THREAD

**Issue by IcicleTheWeavile** [vinegarhq/sober#405]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

On occasion, while playing Untitled Boxing Game, the mobile UI will be displayed rather than the computer UI (when you equip a style or go to fight, the large, distracting on-screen buttons are displayed, as well as the general UI being larger than usual).

Using Fedora 41, nVidia 1070ti, Wayland (though using X11 to run the Sober window itself).

### Roblox Experience link

https://www.roblox.com/games/13621938427/untitled-boxing-game

**Comment by IcicleTheWeavile** [comment]
The same issue seems to somewhat persist in Rivals where it manifests as the on-screen buttons appearing, though that experience is coded in such a way to disable them as soon as keyboard & mouse input is detected, so it's a non-issue.

**Comment by Coolindeed** [comment]
if i launch an roblox game on the website it will display mobile ui
