### ISSUE TITLE
Roblox Crashes at Random Point (Garuda)

### ISSUE THREAD

**Issue by BoatTv7** [vinegarhq/sober#411]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So it has been happening more frequently but sometimes I am able to play a game for a solid 30 minutes before crashing but as of recently I cannot even join certain games without crashing instantly. 

I did make one change to the ClientAppSettings.json file a while back to fix instant game crashing as I was not able to play at all. what I typed into it was basically

"FFlagEnableGameJoinContext2": false

It was fine after that and gave me the ability to play for a couple hours before crashing in the middle of something, or 10 minutes it kind of fluctuated. Now it has gotten worse but this time I actually have an error message instead of being left in the dark.

2024-11-09T10:28:01.357Z,15.357631,23a006c0,6 [LOGCHANNELS + 1] RBXCRASH: OutOfMemoryGraphics (Failed to allocate memory. size = 1399808, alignment = 1024)
RBXCRASH: OutOfMemoryGraphics (Failed to allocate memory. size = 1399808, alignment = 1024)

Another piece of background information is that I currently have 32 Gigs of Ram (four 8gb Cards), and a Nvidia RTX 2080 Super. I am also under the Wayland desktop environment and I have attempted to try running Sober through XWayland but that did not fix things either. 

Any fixes or advice would be helpful since I am currently unable to play roblox right now.

**Comment by reflexran** [comment]
This is an issue with the nvidia driver, try adding these fflags:
```
"DFIntTextureQualityOverride": "2",
"DFFlagTextureQualityOverrideEnabled": "True"
```

**Comment by BoatTv7** [comment]
It, worked thanks. I am going to close the issue now.
