### ISSUE TITLE
How to update roblox?

### ISSUE THREAD

**Issue by mamalubitlal** [vinegarhq/sober#417]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

How to updte roblox in sober?how to do this

**Comment by reflexran** [comment]
You can't, you need to wait for the sober developers to update the apk for you.

**Comment by mamalubitlal** [comment]
then can i fully

> You can't, you need to wait for the sober developers to update the apk for you.

then can i someway delete sober all data and runtime to start roblox install progress and install manualy?

**Comment by reflexran** [comment]
> then can i fully
> 
> > You can't, you need to wait for the sober developers to update the apk for you.
> 
> then can i someway delete sober all data and runtime to start roblox install progress and install manualy?

You can but Sober will not let you install a newer roblox apk, the max is 2.645.665
