### ISSUE TITLE
Add opengl fallback when vulkan is not present

### ISSUE THREAD

**Issue by flafmg** [vinegarhq/sober#421]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

i cant play since my pc is old and dont have vulkan

### Describe the Solution you'd Like

add support to opengl so older pcs can still run sober

### Describe Alternatives you've considered

q

### Additional context

i have a pretty old computer with an igpu that doesnt support vulkan sadly

**Comment by flafmg** [comment]
(sorry the random "q" lol)

**Comment by tunis4** [comment]
`flatpak run org.vinegarhq.Sober --opengl`

**Comment by apprehensions** [comment]
An automatic fallback not to be manually selected by the user.

**Comment by flafmg** [comment]
> `flatpak run org.vinegarhq.Sober --opengl`

oooooh, i didnt know about that

but an automatic fallback would be nice tho

**Comment by flafmg** [comment]
thanks anyway :D
