### ISSUE TITLE
security window just crashes without results

### ISSUE THREAD

**Issue by mamalubitlal** [vinegarhq/sober#423]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im trying to log into my account,but security window chrashes
![Снимок экрана от 2024-11-14 21-29-43](https://github.com/user-attachments/assets/4d08831d-a812-44f5-a094-af9541f9cd00)
![Снимок экрана от 2024-11-14 21-29-56](https://github.com/user-attachments/assets/76c36f36-abc3-4366-ab04-d96df8b36bdd)
![Снимок экрана от 2024-11-14 21-30-16](https://github.com/user-attachments/assets/efff1b52-9141-40a8-85ac-e994971335b4)

what did i do wrong?

**Comment by k1yrix** [comment]
You did nothing wrong, but it tends to do this for reasons I have no idea about. You should use the "Quick Sign-In" button instead.

**Comment by mamalubitlal** [comment]
> You did nothing wrong, but it tends to do this for reasons I have no idea about. You should use the "Quick Sign-In" button instead.

ok,thanks
