### ISSUE TITLE
Unable to Enter Fullscreen on X11

### ISSUE THREAD

**Issue by IcicleTheWeavile** [vinegarhq/sober#427]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Fedora 41, nVidia 1070ti, GNOME, Wayland, forcing X11 windowing system via flatseal to avoid crashes.

I can maximise, resize etc the window just fine, but am unable to enter fullscreen without the app's graphical output freezing... _Most of the time?_ It's strange - it'll work on occasion, but scarcely nontheless.

**Comment by Tuxuis** [comment]
I've had this issue first time when trying out sober. I have no idea why this issue happens or what the cause of it is. All I know is that when I reinstalled my entire OS, it somehow fixed it.

**Comment by IcicleTheWeavile** [comment]
Further inspection, the newest update _might_ have fixed this. Waiting a few days to confirm.

**Comment by tunis4** [comment]
yea we fixed this

**Comment by IcicleTheWeavile** [comment]
y'all are amazing holy shit

**Comment by MichMich** [comment]
Just out of curiosity: is there a way to put the game on fullscreen under ubuntu without showing any menubar or similar?
