### ISSUE TITLE
Shift lock

### ISSUE THREAD

**Issue by JumpIn-Git** [vinegarhq/sober#430]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

When playing roblox on pc, you can press shift to go in a camera state that is 3d person but lets you move the camera without holding the right mouse button, i think its not in sober since its based of the apk

### Describe the Solution you'd Like

I want this feature to be added

### Describe Alternatives you've considered

I geuss going in 1st person but shift lock is better

**Comment by reflexran** [comment]
Shift lock is in Sober

**Comment by JumpIn-Git** [comment]
> Shift lock is in Sober, if you don't see an option to enable it try to rejoin the game or restart Sober.

I dont see it in settings, and shift does nothing, i updated sober too

**Comment by tunis4** [comment]
no it was always there you just got unlucky
