### ISSUE TITLE
Some games dont have shift lock working at all

### ISSUE THREAD

**Issue by M1ke82** [vinegarhq/sober#432]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I play a lot of roblox battleground games and only some of the games I play actually have shift lock working and I need shift lock since it's the main way many people play

**Comment by M1ke82** [comment]
https://www.roblox.com/games/10449761463/The-Strongest-Battlegrounds

**Comment by tunis4** [comment]
check if the update fixed the issue for you

**Comment by Harut793** [comment]
After update this game also have a problem https://www.roblox.com/games/3016661674/Rogue-Lineage

**Comment by tinetik** [comment]
After update I can't find a game where shift lock is working.
This game is the specific one where I need it: https://www.roblox.com/games/4111023553/Deepwoken-SALE

**Comment by KensukeKurosaki** [comment]
https://www.roblox.com/games/5130598377/A-Universal-Time-4-0 also happened here

**Comment by tinetik** [comment]
Shift lock is now working for me after taking another sober update! Thank you devs :D

**Comment by Xtuber14** [comment]
For me too

Il mar 3 dic 2024, 17:32 Will ***@***.***> ha scritto:
