### ISSUE TITLE
Error 280

### ISSUE THREAD

**Issue by IcicleTheWeavile** [vinegarhq/sober#437]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm getting the following error when joining an experience, suddenly during a long sesh:
"Your version of Roblox may be out of date. Please update Roblox and try again. (Error Code: 280)"
is it possible that Sober was blocked by Roblox? or is this an issue that necessitates an update of Sober itself? is it an issue only I am having, or is any of you guys getting it as well?
Fedora 41, nVidia 1070ti, Wayland (XWayland), GNOME

**Comment by 1Arnoo** [comment]
damn bruh i wish i never found someone commenting 4 mins ago about the same problem now you know some people gonna have it too. i think sober is cooked for now

**Comment by TheCreatorGrey** [comment]
I've just had the same problem...

**Comment by 1Arnoo** [comment]
> I've just had the same problem...

ggs sober is cooked for now

**Comment by TheCreatorGrey** [comment]
> > I've just had the same problem...
> 
> ggs sober is cooked for now

Hopefully not

**Comment by Nuhhuh** [comment]
we gotta wait they update sadly

**Comment by 1Arnoo** [comment]
i was getting the error in only 1 game i was playing and could join different games but now im getting the error in all games i try to join

**Comment by Arieltechz** [comment]
es verdad sober no esta b loqueado por roblox esto a pasado como 2 oh 3 veses en el pasado sober no es como el roblox original no puede proporcion arnos actualizaciones al momento son unos pocos desarrolladores tenemos que esperar hastta que actualizen sober pa que sea compatible con las nuevas versiones de roblox

**Comment by IcicleTheWeavile** [comment]
> > > I've just had the same problem...
> > 
> > 
> > ggs sober is cooked for now
> 
> Hopefully not

with no notice from the devs i doubt it, they probably updated the android version in a way that the sober devs need some time to adapt to linux x64. if it was cooked, the devs would probably say it.

**Comment by Arieltechz** [comment]
> Solo me aparecía el error en un juego al que estaba jugando y podía unirme a diferentes juegos, pero ahora me aparece el error en todos los juegos a los que intento unirme.

por lo mismo roblox esta desactualizado tiene como 2 semanas sin actualizaciones 
de parte de sober aunque cuando pasa esto lo arreglan alos 2 oh en un dia

**Comment by Nuhhuh** [comment]
> i was getting the error in only 1 game i was playing and could join different games but now im getting the error in all games i try to join

same before with tsb i restarted system and it worked but now it all game

**Comment by Arieltechz** [comment]
> > Solo me aparecía el error en un juego al que estaba jugando y podía unirme a diferentes juegos, pero ahora me aparece el error en todos los juegos a los que intento unirme.
> 
> Lo mismo antes con tsb reinicié el sistema y funcionó, pero ahora todo es juego.

roblos esta desactualizado tocar esperar a que los esquipos de sober actualizen su app
