### ISSUE TITLE
How do i update Sober?

### ISSUE THREAD

**Issue by LeoTheGuuy** [vinegarhq/sober#438]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried a lot of methods and they didn't work, anyone know how to fix this? 

### Roblox Experience link

https://sober.vinegarhq.org/

**Comment by Nuhhuh** [comment]
you gotta wait rn they update

**Comment by Arieltechz** [comment]
si toca esperar a que los dessarolladores trabnajen en la update

**Comment by LeoTheGuuy** [comment]
Ok, do i have to do anything else after they update it?

**Comment by Arieltechz** [comment]
> Vale, ¿tengo que hacer algo más después de que lo actualicen?

no solo esperar y despues irte atu tienda de aplicaciones buscar sober y actualizarlo y ya estaria todo
tenemos que recordar que puede tandar los desarrolladores de sober no son muchos por lo que tengo entendido asi que solo nos queda esperar

**Comment by LeoTheGuuy** [comment]
OK, i will do that when they update it, thank you!

**Comment by Arieltechz** [comment]
> Ok, lo haré cuando lo actualicen, ¡gracias!

denada puede tardar a 2 dias como maximo no saves bien cuando lo vayan a actualizar pero no se van a tardar espero te aya ayudado por ahora solo queda jugar en las plataformas mobile oh wimdows pa mientras se actualiza

**Comment by LeoTheGuuy** [comment]
OK, i will wait.

**Comment by BrycensRanch** [comment]
good decision to reopen! how am I gonna play jailbreak

**Comment by Arieltechz** [comment]
> ¡Buena decisión reabrir! ¿Cómo voy a jugar al jailbreak?

como asi ???

**Comment by Arieltechz** [comment]
I understand

**Comment by Arieltechz** [comment]
> > > ¡Buena decisión reabrir! ¿Cómo voy a jugar al jailbreak?
> > 
> > 
> > in that way ???
> 
> Bueno, el tema anterior se cerró como off-topic sin ningún comentario de los desarrolladores

He came looking for support and some users gave it to him and it is not an error, it will be solved soon, it is a matter of waiting.

**Comment by LeoTheGuuy** [comment]
Sorry for closing, i didn't mean to.

**Comment by omegadreamer** [comment]
same issue, hope sober will be alive btw

**Comment by k1yrix** [comment]
> same issue, hope sober will be alive btw

the devs are awake and is trying to get things fixed rn

**Comment by LeoTheGuuy** [comment]
OK, thanks! I will keep checking each day and see if it has updated.

**Comment by k1yrix** [comment]
> OK, thanks! I will keep checking each day and see if it has updated.

it's probably going to get fixed within the next hour, so it's going to be relatively quick (after it gets through testing)

**Comment by k1yrix** [comment]
build has been published

go ahead and run `flatpak update` now

**Comment by LeoTheGuuy** [comment]
Thanks! I did it and i can finally play again!
