### ISSUE TITLE
nose preocupen si su roblox no esta actualizado 

### ISSUE THREAD

**Issue by Arieltechz** [vinegarhq/sober#439]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

los desarrolladores de sober son pocos entiendo que estan preocupados por no poder jugar roblox oh que ayan pensado que roblox  bloqueo a sober no nada de eso pronto los desarrolladores lo van a actualizar por ahora solo toca esperar antes avia pasado lo mismo y lo mas que se tardaron fueron 2 dias solo toca esperar

**Comment by alejandro-alzate** [comment]
For non bilingual people:
> Sober developers are few, I understand that you guys are worried about not being able to play Roblox, or what have they thought about Roblox blocking Sober? No, nothing like that, soon the developers will update it. For now, just wait. The same thing happened before and the longest it took was 2 days. Just wait.

**Comment by alejandro-alzate** [comment]
Same vibe as #440
