### ISSUE TITLE
Do not freak out over these things.

### ISSUE THREAD

**Issue by guyguy124** [vinegarhq/sober#440]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

If you see a message, "your roblox version may be out of date" no, roblox has not destroyed sober, roblox has updated and the sober mods need time to add that updaate to sober, please stop freaking out over these things.

**Comment by omegadreamer** [comment]
same lol

**Comment by Bugsbane** [comment]
Eventually, and no I'm not asking when or pushing devs to do volunteer work, but eventually it would be cool for Sober to detect when the Roblox runtime has updated and to auto update to the new one.

**Comment by FiremasterGR** [comment]
One day... One day, they may do it

**Comment by mrhoomanwastaken** [comment]
BUT ITS THE END OF THE WORLD!!!!

**Comment by Bikoil** [comment]
> One day... One day, they may do it

the fall is inevitable, thou shall expect it 

jk, but if they ever do it roblox on linux may be fully cooked

**Comment by ultradev-coder** [comment]
i already knew this was going to happen

**Comment by k1yrix** [comment]
build has been published

go ahead and run `flatpak update` now

**Comment by mrhoomanwastaken** [comment]
> build has been published
> 
> go ahead and run `flatpak update` now

epic sauce

**Comment by jcvm-dev** [comment]
What am I going to do with my life without my "Child's game"?

**Comment by Bugsbane** [comment]
How disappointing! I was so looking forward to freaking out and the devs went and fixed the issue before ever giving me the chance... How rude! ;P

**Comment by jcvm-dev** [comment]
`$ flatpak install --user https://sober.vinegarhq.org/sober.flatpakref
error: Non-existent ref “app/org.vinegarhq.Sober/x86_64/master” on sober remote`

**Comment by jcvm-dev** [comment]
Error details:
File "/usr/lib/python3/dist-packages/repoman/flatpak_helper.py", line 386, in run transaction.run(None)
