### ISSUE TITLE
Can't install on steam deck

### ISSUE THREAD

**Issue by sanscoolGUY** [vinegarhq/sober#441]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was trying to update sober but it did not show so i uninstall sober and i can't download it

**Comment by k1yrix** [comment]
Sober was recently updated. It will take time for Cloudflare to fully propagate the update into their servers.

**Comment by sanscoolGUY** [comment]
Your right lol thanks for letting me know
