### ISSUE TITLE
Sober thinks my system is outdated when attempting to launch

### ISSUE THREAD

**Issue by LordZintick** [vinegarhq/sober#445]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I downloaded the `sober.flatpakref` file from the official Sober page, and I ran it using the command line.
On the first run, Sober started up fine, installing Roblox completely OK with no errors.
Upon attempting to launch Roblox, Sober said my linux kernel was outdated, and that I needed to update it.
The required version/architecture that it said I needed was x86_64 5.11 and above.

This is the version/architecture information from the `uname` command:
![soberuname](https://github.com/user-attachments/assets/9b99d0d0-81ea-40c3-853c-74d2aa23dea7)

This is the version/architecture information provided by the `neofetch` command:
![image](https://github.com/user-attachments/assets/86c55634-6381-41f2-8e32-96a4250381e1)

For completeness, this is the error provided by Sober when attempting to launch Sober:
![image](https://github.com/user-attachments/assets/fecd3b45-d74f-472c-a1be-3025f633fb73)

It recommends doing a linux clean boot, I have done that already to no avail.

### Roblox Experience link

N/A

**Comment by LordZintick** [comment]
I attempted to install Linux Mint 21, but it didn't work either.
I don't really know what is wrong with my computer, as I have had problems installing almost every program I've tried to install.
(wine, sober, vinegar, genymotion, gnome boxes, etc.)
Thanks for the help anyway! :smile:

**Comment by tunis4** [comment]
not a sober issue, figure out how to update your system
