### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#45]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

we need changelogs for the github or the site

### Describe the Solution you'd Like

add changelogs for the github or the site

### Describe Alternatives you've considered

i dont think theres any alternatives

### Additional context

i just wanna know whats new

**Comment by apprehensions** [comment]
We do not have stable releases at this time.
