### ISSUE TITLE
can't install at all

### ISSUE THREAD

**Issue by dbk17** [vinegarhq/sober#454]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When attempting to install through terminal I get the error: Can't load uri https://sober.vinegarhq.org/sober.flatpakref: Server returned status 403

when attempting to install through software manager I get the error: No such ref 'app/org.vinegarhq.Sober/x86_64/master' in remote sober

**Comment by k1yrix** [comment]
Use a VPN

> Server returned status 403

**Comment by dbk17** [comment]
that worked
