### ISSUE TITLE
Crashing while playing

### ISSUE THREAD

**Issue by yosoyluc** [vinegarhq/sober#456]
https://pastebin.com/UCtZeyET
I have tried to play Roblox on sober but it always ends up crashing after playing for a while, I decided to open Sober with the terminal to see the error that generates the crash and this error is. 

I use arch linux with Kde Plasma 6.2.3 and Wayland.

**Comment by tunis4** [comment]
`flatpak override --user --socket=x11 --nosocket=wayland org.vinegarhq.Sober`
