### ISSUE TITLE
i don t know how to disable wayland to stop crashes

### ISSUE THREAD

**Issue by spuntik1205** [vinegarhq/sober#459]
i don t know where the wayland files are so i dont know how to disable

**Comment by WindClan** [comment]
wayland is a display system, you shouldnt change it unless you want to rely on half broken archaic technology (x11)

**Comment by reflexran** [comment]
> wayland is a display system, you shouldnt change it unless you want to rely on half broken archaic technology (x11)

that's not what he meant, he wants to force xwayland

**Comment by reflexran** [comment]
> i don t know where the wayland files are so i dont know how to disable

install flatseal, then click on sober and disable `wayland windowing system`
