### ISSUE TITLE
Default Wayland logo in title bar for KDE

### ISSUE THREAD

**Issue by Vlad55432** [vinegarhq/sober#46]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Fedora KDE 40, if you mind
To reproduce: Simply launch sober and look at title bar and alt tabing.

![зображення](https://github.com/user-attachments/assets/8ffc683f-5598-46cd-a258-4e76d8eb0971)
![зображення](https://github.com/user-attachments/assets/5d251d04-9b39-44da-8ef2-ffbdc52b8e07)

**Comment by Weather-OS** [comment]
This happens when the .desktop files gets modified.
Reinstalling fixes this issue.
