### ISSUE TITLE
VRAM leak issues

### ISSUE THREAD

**Issue by Fabito02** [vinegarhq/sober#465]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The application works normally, but in games that require a larger amount of graphics memory (for example Frontlines), on dedicated cards with little memory (as is my case, with only 2GB), when presenting a high usage, the application closes instantly, showing in the logs that the memory to be allocated is greater than the available one. In addition, the use of graphics memory does not present a stable graph, with high variations.

![Captura de tela de 2024-12-02 15-18-53](https://github.com/user-attachments/assets/8ddf3144-57c9-4da9-87c9-c2805d598bb6)
![image](https://github.com/user-attachments/assets/2b737606-423c-415a-8b0b-9369611d4247)

**Comment by Fabito02** [comment]
Changing a few things in my nvidia.conf, it seems like magic, but the usage decreased drastically! (I had help from our great friend GPT). The VRAM usage was extremely low and stable.

![image](https://github.com/user-attachments/assets/97ec1b54-e88a-47a2-a725-f9655f33b743)

**Comment by ChickenRest67** [comment]
i wanna ask what did you change on your nvidia.conf
i might want to use it myself

**Comment by Fabito02** [comment]
> i wanna ask what did you change on your nvidia.conf i might want to use it myself

This is my current nvidia.conf:

```
options nvidia-drm modeset=1
options nvidia NVreg_InitializeSystemMemoryAllocations=1
#options nvidia NVreg_RegistryDwords="OGL_DefaultSwapInterval=0x0"
options nvidia NVreg_EnableStreamMemOPs=1
```
