### ISSUE TITLE
(Error Code 280)

### ISSUE THREAD

**Issue by auskes** [vinegarhq/sober#466]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I receive the following error message when attempting to join any game:

Your version of Roblox may be out of date. Please update Roblox and try again. (Error Code 280)

I've already tried to resolve the issue by running "flatpak update", problem still persists.

**Comment by reflexran** [comment]
The apk Sober is using just became outdated, wait for a Sober update to come out, should take a few hours.

**Comment by Tarvey** [comment]
the duck walks up to the lemonade st- oh wait i was supposed to say that i can confirm, anyway, im gonna wait

**Comment by rosebytee** [comment]
> The apk Sober is using just became outdated, wait for a Sober update to come out, should take a few hours.

usually it's self updating though isn't it? would be tedious to have to update _every_ roblox client update

**Comment by reflexran** [comment]
Funny that you say that because that's exactly what the sober devs are doing.

**Comment by Setsuwaa** [comment]
> > The apk Sober is using just became outdated, wait for a Sober update to come out, should take a few hours.
> 
> usually it's self updating though isn't it? would be tedious to have to update _every_ roblox client update

Executor devs had to update every wednesday, compared to that i don't think this is that bad

**Comment by willbohrer** [comment]
> would be tedious to have to update _every_ roblox client update

Sober verifies the signature of every APK (makes sure it's Roblox and the correct architecture). They just need to add the new signature. They also make sure it's compatible, but that's rarely an issue.

**Comment by NoDreamsRemain** [comment]
Does it update automatically? Or you gotta go to the site to install it again?

**Comment by Tarvey** [comment]
> Does it update automatically? Or you gotta go to the site to install it again?

i think you just need to update using your software manager (or just run flatpak update)

**Comment by NoDreamsRemain** [comment]
Or i could just use sudo apt update?
and *sudo apt upgrade*

**Comment by Setsuwaa** [comment]
> Or i could just use sudo apt update? and _sudo apt upgrade_

Sober is a flatpak...

**Comment by reflexran** [comment]
> Or i could just use sudo apt update? and _sudo apt upgrade_

No, Sober is a flatpak app not a system one.

**Comment by NoDreamsRemain** [comment]
Got it. Thanks

**Comment by Dinky-AyuIo** [comment]
Happens all the time, I expect this one will be shorter than the last as the developers have made a system that's quite used to this by now. For now though, I recommend you play a different game like For Honor or Minecraft.

**Comment by KensukeKurosaki** [comment]
im having the same issue

**Comment by rosebytee** [comment]
> Happens all the time, I expect this one will be shorter than the last as the developers have made a system that's quite used to this by now. For now though, I recommend you play a different game like For Honor or Minecraft.

tf2 is free, go play that

**Comment by JimBimBum** [comment]
i could've just downloaded and used the updated apk by now.

**Comment by NoDreamsRemain** [comment]
Quick question, when do i know if the update is out?

**Comment by k1yrix** [comment]
> Quick question, when do i know if the update is out?

we will let you know

if you want to know right away, you could join vinegarhq's discord server

**Comment by NoDreamsRemain** [comment]
Can you send me the link? I have been trying to find the server for a long time.

**Comment by BMP989** [comment]
> Can you send me the link? I have been trying to find the server for a long time.

Literally just look up vinegarhq discord

But here:
https://discord.com/invite/vinegarhq-1069506340973707304

**Comment by tunis4** [comment]
update was released, if updating fails for you wait for cloudflare caches to propagate
