### ISSUE TITLE
Sober down again.

### ISSUE THREAD

**Issue by guyguy124** [vinegarhq/sober#467]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Im just saying this so people dont freak out, roblox made a new version so sober needs to add that. No sober is not destroyed permanetly.

**Comment by Setsuwaa** [comment]
dawg did you not read what you checked off

**Comment by Dinky-AyuIo** [comment]
![image](https://github.com/user-attachments/assets/49fe284b-2cf5-469a-b870-e33519728ea3)
This is a lie lol

**Comment by Cube9214** [comment]
please read what your checking off

**Comment by mroshan5722** [comment]
Hi im new to using sober, and have just realised it doesnt work anymore because its outdated. Any idea on when the new version of Roblox can be incorporated?

**Comment by batatinha-espacial** [comment]
how to update it then? it still says that it is outdated after `flatpak update` and `flatpak run org.vinegarhq.Sober --bootstrap`

**Comment by k1yrix** [comment]
> how to update it then? it still says that it is outdated after `flatpak update` and `flatpak run org.vinegarhq.Sober --bootstrap`

you have to wait until sober is update.
it is yet to update as of right now.

**Comment by batatinha-espacial** [comment]
what if I have the roblox apk?

**Comment by k1yrix** [comment]
> what if I have the roblox apk?

it will not work regardless. Sober uses a fixed-point release system, which only supports one build every time Sober updates (and I mean **ONLY** one build per Sober update)

**Comment by BMP989** [comment]
In the meantime, anyone know any good linux servers?

**Comment by Sinnx3x** [comment]
Thank you for working on it! 🖤

**Comment by tunis4** [comment]
update was released, if updating fails for you wait for cloudflare caches to propagate
