### ISSUE TITLE
add instructions

### ISSUE THREAD

**Issue by rdp** [vinegarhq/sober#470]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Some ideas from a new user:

When installing sober in ubuntu, it seems that there's no new "app" for it added...I guess the only way to run it is `$flatpak run org.vinegarhq.Sober` twould  be nice to add this to the instructions somehow, like a 2b.  It is not quite clear how to "Open your favorite Roblox experience", was Roblox supposed to start?

Also, might be nice to link "Sober is a labor of love, and we'd love for you to try it out! We hope you enjoy your time." to the github so people know how to report stuff after trying it out...

Cheers and thanks!

### Describe the Solution you'd Like

Better instructions.

### Describe Alternatives you've considered

Better console output at install time?

**Comment by newor0599** [comment]
Sober should appear on the start menu, the app is named "Sober" not "Roblox". 

You can also create a shortcut to sober too
Create a `.desktop` file in `~/.local/share/applications/`, paste this into the file
```
[Desktop Entry]
Type=Application
Name=Sober
Keywords=sober,roblox
Exec=flatpak run org.vinegarhq.Sober
Icon=/path/to/icon.png
```
The icon is optional
You should be able to see sober on the start menu

**Comment by YoshiRulz** [comment]
Can confirm it auto-installed a `.desktop` on my Ubuntu system.

**Comment by tunis4** [comment]
we already have a .desktop file, instructions for launching arent needed

**Comment by rdp** [comment]
OK I see it in the start menu, thanks.  Perhaps installation instruction 2b should be added "open the sober app"...? :)
Cheers :)
