### ISSUE TITLE
Unable to start with old laptop

### ISSUE THREAD

**Issue by rdp** [vinegarhq/sober#471]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

```
```
```$ flatpak run org.vinegarhq.Sober

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/dad/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

```
Does nothing.

```
$ sudo dmesg | grep sober
[ 2595.093684] traps: sober[9440] trap invalid opcode ip:62bd6fd8d486 sp:7ffca0ec06b0 error:0 in sober[62bd6fd8b000+428000]
```
Macbook 2009 running Ubuntu 20.04

Thank you for your time.

**Comment by KonoKore** [comment]
mfw sober is down, give it time

**Comment by Cube9214** [comment]
> mfw sober is down, give it time

dude this is a different error

**Comment by KonoKore** [comment]
> > mfw sober is down, give it time
> 
> dude this is a different error

dog no one can play roblox right now

**Comment by tunis4** [comment]
> sober[9440] trap invalid opcode

your cpu is too outdated. it needs to support SSE 4.2 in order to run sober
