### ISSUE TITLE
When entering a game error 280 appears (outdated client)

### ISSUE THREAD

**Issue by Hikarijarjar** [vinegarhq/sober#472]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sober seems to be outdated :(

**Comment by k1yrix** [comment]
> Sober seems to be outdated :(

It is getting resolved as soon as the developers can. There is nothing much we can do however.

**Comment by Hikarijarjar** [comment]
thanks!

**Comment by kikoferrer** [comment]
Is this the issue where the app supports a certain version and then when you play it asks you to update the version?

**Comment by 0hStormy** [comment]
> Is this the issue where the app supports a certain version and then when you play it asks you to update the version?

Yes, just wait a bit for the devs to work on an update

**Comment by BMP989** [comment]
Same problem, just got to wait for the awesome devs to fix it!

**Comment by WhatHomework** [comment]
Same problem. Guess we wait now.

**Comment by leduxsonicpeli** [comment]
yes i guess

**Comment by Golem-0** [comment]
Same problem, can't wait for the update

**Comment by leduxsonicpeli** [comment]
me too

**Comment by tunis4** [comment]
update was released, if updating fails for you wait for cloudflare caches to propagate
