### ISSUE TITLE
Sober verson is out of date again

### ISSUE THREAD

**Issue by Nickng1233** [vinegarhq/sober#473]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I made a post about this problem before so i think this nothing new

**Comment by MORTIS213** [comment]
same here just wait for the developers to update sober

**Comment by tunis4** [comment]
update was released, if updating fails for you wait for cloudflare caches to propagate
