### ISSUE TITLE
Can someone help me on what to do? 

### ISSUE THREAD

**Issue by AnDumbo** [vinegarhq/sober#474]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

That error is coming on sober. I'm not sure if the devs are done fixing it but if and when they are done, what do I do?

**Comment by 0hStormy** [comment]
![image](https://github.com/user-attachments/assets/8e8e675c-4089-43a3-b2cb-6fceceaf29cc)
A nightly release was posted for tester, so it should be out by tomorrow

**Comment by tunis4** [comment]
update was released, if updating fails for you wait for cloudflare caches to propagate
