### ISSUE TITLE
Sober is Outdated (Code 280)

### ISSUE THREAD

**Issue by ZigWantsSoda** [vinegarhq/sober#476]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i Join a game the client is showing outdated

**Comment by BMP989** [comment]
Not another

**Comment by zleeepy** [comment]
this is a dupe

**Comment by BlxCode** [comment]
Lies XD

**Comment by tunis4** [comment]
update was released, if updating fails for you wait for cloudflare caches to propagate
