### ISSUE TITLE
The command "flatpak run org.vinegarhq.Sober --opengl" tries to run on  GPU

### ISSUE THREAD

**Issue by INorthDev** [vinegarhq/sober#477]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hi! My Ubuntu version and the data about the problems are:

UBUNTU VERSIION:

PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

LOGS:

[2.652.0.765_20241203T082055Z_Player_0bc4f_last.log](https://github.com/user-attachments/files/17989617/2.652.0.765_20241203T082055Z_Player_0bc4f_last.log)

IMAGE:

![image](https://github.com/user-attachments/assets/041e1479-e352-4602-9a2d-b6c05119fbfd)

It used to work properly but after the last update it started to give this error.

**Comment by tunis4** [comment]
i added a new configuration system and accidentally broke the launch arguments, you can enable opengl in `~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

**Comment by INorthDev** [comment]
> i added a new configuration system and accidentally broke the launch arguments, you can enable opengl in `~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

Thanks bro now it's opening! If i  encounter further bugs i'll make you all notified!

**Comment by INorthDev** [comment]
> i added a new configuration system and accidentally broke the launch arguments, you can enable opengl in `~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

In the experience https://www.roblox.com/games/740581508/Entry-Point i can't use WASD. I think it happens in other games too but haven't tested yet

**Comment by INorthDev** [comment]
> i added a new configuration system and accidentally broke the launch arguments, you can enable opengl in `~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

Another bug is for some reason i can't see mouse cursor

**Comment by INorthDev** [comment]
> there was a regression that causes pc controls to break if a game teleports you to another place, we will release a hotfix update today

I'm  glad to hear that! Keep good work up guys. Btw i joined to another game but i can use WASD even with  teleport  https://www.roblox.com/games/2916899287/Blackhawk-Rescue-Mission-5 the issue might not be about  that but i'm not an expert so to make your jobs easier i'm going t o put link here too.

**Comment by tunis4** [comment]
a hotfix update has been released to fix the input issues, also --opengl option is now removed and will print an error message to use config.json instead

**Comment by NewToLinux123** [comment]
Wen I try to run that command, it says "permission denied" Do you know how to fix this?

**Comment by tunis4** [comment]
> Wen I try to run that command, it says "permission denied" Do you know how to fix this?

thats not a command, its a file. to actually edit it use something like `nano ~/.var/app/org.vinegarhq.Sober/config/sober/config.json`
