### ISSUE TITLE
xbox controls for shiftlock not working properly on steam deck

### ISSUE THREAD

**Issue by KensukeKurosaki** [vinegarhq/sober#478]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

just noticed my controls for shiftlock arent working right

**Comment by danieltomi123** [comment]
#WENEEDSHIFTLOCK

**Comment by KensukeKurosaki** [comment]
> #WENEEDSHIFTLOCK

FR

**Comment by tinetik** [comment]
Possibly related to #432

**Comment by tunis4** [comment]
fixed in update
