### ISSUE TITLE
Middle mouse click not detected

### ISSUE THREAD

**Issue by cwillsey06** [vinegarhq/sober#48]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

As far as I can tell middle mouse input is not detected at all.

I think a good way to test this is to play [PARKOUR](https://www.roblox.com/games/445664957/PARKOUR) and try hitting middle mouse and seeing if it works.

### Roblox Experience link

https://www.roblox.com/games/11639495622
https://www.roblox.com/games/445664957

**Comment by BurntRanch** [comment]
Same issue happens on Rivals, you can't ping using Mouse 3.

**Comment by tunis4** [comment]
fixed in update
