### ISSUE TITLE
How to Update Sober?

### ISSUE THREAD

**Issue by mroshan5722** [vinegarhq/sober#480]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/63164e36-26ff-42c6-87f3-748df544a8b7)

Can someone assist me on updating Sober. I read thru the website and the GitHub, but couldn't find any instructions on how to do this

**Comment by BMP989** [comment]
Since they only release it as a flatpak, all you have to do is run the command `flatpak update`.

**Comment by tunis4** [comment]
`flatpak update`

if it fails you need to wait since the cloudflare caches take time to propagate
