### ISSUE TITLE
sober crashes when i try joining my favoirite game: Twisted. issue on steamdeck

### ISSUE THREAD

**Issue by coleisbad01** [vinegarhq/sober#484]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

cant join twisted at all, worked before the new update.

### Roblox Experience link

https://www.roblox.com/games/6161235818/Twisted-BETA

**Comment by coleisbad01** [comment]
https://github.com/user-attachments/assets/8421ff5c-e815-48f9-b31b-06e2f8ae7701

here is a video for more detailed info.

**Comment by tunis4** [comment]
send the log file (`~/.var/app/org.vinegarhq.Sober/data/sober/sober_logs/latest.log`)

**Comment by coleisbad01** [comment]
[2024-12-03_17-40-24.log](https://github.com/user-attachments/files/18003793/2024-12-03_17-40-24.log)

**Comment by VaiTheCatto** [comment]
@coleisbad01 I've reported this issue on the discord server. I'm facing the same issue with other games.. The devs are (hopefully) trying to find the issue and fix it. All we gotta do now is be patient.

**Comment by coleisbad01** [comment]
@VaiTheCatto where do you find the discord server? can you send a invite link?

**Comment by tunis4** [comment]
> @VaiTheCatto where do you find the discord server? can you send a invite link?

https://discord.gg/dzdzZ6Pps2
