### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by NewToLinux123** [vinegarhq/sober#485]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I tried to use the command "~/.var/app/org.vinegarhq.Sober/config/sober/config.json" to turn on opengl to true, It said permission denied. Can someone help! Im new to Linux.

**Comment by Kiiena** [comment]
try: sudo nano ~/.var/app/org.vinegarhq.Sober/config/sober/config.json

**Comment by tunis4** [comment]
do not use `sudo nano` just do `nano ~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

the permission denied is because you put the path in the terminal without a command

**Comment by Kiiena** [comment]
> do not use `sudo nano` just do `nano ~/.var/app/org.vinegarhq.Sober/config/sober/config.json`
> 
> the permission denied is because you put the path in the terminal without a command

Thanks for the correction

**Comment by NewToLinux123** [comment]
But then what do I do. Like how do I turn opengl back on. when i ran that command it brings me to a page on the terminal 
and I saw "use_openg:" and i put true, but how do i save.

**Comment by NewToLinux123** [comment]
very sorry, Im new to linux so i don't really know what to do

**Comment by NewToLinux123** [comment]
How do I open it on notepad

**Comment by NewToLinux123** [comment]
How do I save once I turned it to true
