### ISSUE TITLE
Sober doesnt start when i applie fastflags

### ISSUE THREAD

**Issue by mxscel** [vinegarhq/sober#486]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i save some fastflags in /.var/app/org.vinegarhq.Sober/config/sober sober doesnt starting anymore

**Comment by tunis4** [comment]
send the log file (`~/.var/app/org.vinegarhq.Sober/data/sober/sober_logs/latest.log`) and send which fflags you added

**Comment by mxscel** [comment]
> send the log file (`~/.var/app/org.vinegarhq.Sober/data/sober/sober_logs/latest.log`) and send which fflags you added

for fastflags it doesnt matter, it doesnt want to start after just editing the file i added "," at the end of ""FFlagExample": true" and it doesnt want to turn on after that
