### ISSUE TITLE
Alt+F4 closes sober instead of asking if you wish to exit the game, or Roblox

### ISSUE THREAD

**Issue by patrlim** [vinegarhq/sober#489]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Alt+F4 closes sober instead of asking if you wish to exit the game, or Roblox.

**Comment by tunis4** [comment]
alt+f4 is your desktop environment or window manager's shortcut for killing the focused window, it's not in sober's control

**Comment by Dinky-AyuIo** [comment]
I'd say this is an upgrade

**Comment by patrlim** [comment]
> I'd say this is an upgrade

my sister doesn't seem to think so.

**Comment by tunis4** [comment]
ok you are right sorry, but i dont think roblox even has a prompt like that on android

**Comment by AshtakaOOf** [comment]
> ok you are right sorry, but i dont think roblox even has a prompt like that on android and idk if we should bother making a custom prompt

The Android version likely has it, I believe it's the same (or similar) prompt as when you're leaving a game.

**Comment by tunis4** [comment]
which prompt do you mean? and how would we trigger it

**Comment by AshtakaOOf** [comment]
> which prompt do you mean? and how would we trigger it

Nevermind I remembered wrong, it's different from the leave game prompt it's this one.
![image](https://github.com/user-attachments/assets/f3deb11e-b9a9-4ca1-b02c-7f7a5e76730f)

**Comment by tunis4** [comment]
won't be implemented
