### ISSUE TITLE
Sober 'config.json' file not existing in the Sober directory.

### ISSUE THREAD

**Issue by fundipp0** [vinegarhq/sober#490]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I am on a pretty old PC so when i use Sober i use the '--opengl' argument. But in the newest update it said I had to add it in the config.json file in "/home/fundipp0/.var/app/org.vinegarhq.Sober/config/sober"... but it's not there. I have searched using the file explorer and cant find the directory or config.json, just some other json files with config in the name. Please fix this fast because i want to carry  on playing roblox on my only PC.

Thanks,

fundipp0
also i will link a photo of what happens when I try to load sober with the original command. :)
![Selection_001](https://github.com/user-attachments/assets/ba081a3a-1435-47ed-b2d3-4d7d144bcb75)

**Comment by tunis4** [comment]
looks like the file doesn't get created if you try to launch with --opengl, oops

just launch once without arguments to let the file be created

**Comment by fundipp0** [comment]
ok thanks:)

**Comment by fundipp0** [comment]
Thank you, it works great! I can now launch it from the desktop icon!

**Comment by NewToLinux123** [comment]
how did you do it?

**Comment by NewToLinux123** [comment]
> looks like the file doesn't get created if you try to launch with --opengl, oops
> 
> just launch once without arguments to let the file be created

What does launch once without arguments to let the file be created mean?? please tell me, i have the same issue

**Comment by Tarvey** [comment]
> > > > looks like the file doesn't get created if you try to launch with --opengl, oops
> > > > just launch once without arguments to let the file be created
> > > 
> > > 
> > > What does launch once without arguments to let the file be created mean?? please tell me, i have the same issue
> > 
> > 
> > literally just run it normally once... `flatpak run org.vinegarhq.Sober`
> 
> I can't, it says "Failed to parse JSON file. Check if there are any misplaced commas.

send your config.json, from ~/.var/app/org.vinegar.Sober/config/sober/

**Comment by NewToLinux123** [comment]
> > > > > looks like the file doesn't get created if you try to launch with --opengl, oops
> > > > > just launch once without arguments to let the file be created
> > > > 
> > > > 
> > > > What does launch once without arguments to let the file be created mean?? please tell me, i have the same issue
> > > 
> > > 
> > > literally just run it normally once... `flatpak run org.vinegarhq.Sober`
> > 
> > 
> > I can't, it says "Failed to parse JSON file. Check if there are any misplaced commas.
> 
> send your config.json, from ~/.var/app/org.vinegar.Sober/config/sober/

What?

**Comment by NewToLinux123** [comment]
> > > > > looks like the file doesn't get created if you try to launch with --opengl, oops
> > > > > just launch once without arguments to let the file be created
> > > > 
> > > > 
> > > > What does launch once without arguments to let the file be created mean?? please tell me, i have the same issue
> > > 
> > > 
> > > literally just run it normally once... `flatpak run org.vinegarhq.Sober`
> > 
> > 
> > I can't, it says "Failed to parse JSON file. Check if there are any misplaced commas.
> 
> send your config.json, from ~/.var/app/org.vinegar.Sober/config/sober/

I don't get it

**Comment by NewToLinux123** [comment]
> > > > > > looks like the file doesn't get created if you try to launch with --opengl, oops
> > > > > > just launch once without arguments to let the file be created
> > > > > 
> > > > > 
> > > > > What does launch once without arguments to let the file be created mean?? please tell me, i have the same issue
> > > > 
> > > > 
> > > > literally just run it normally once... `flatpak run org.vinegarhq.Sober`
> > > 
> > > 
> > > I can't, it says "Failed to parse JSON file. Check if there are any misplaced commas.
> > 
> > 
> > send your config.json, from ~/.var/app/org.vinegar.Sober/config/sober/
> 
> What?

U want a ss?

**Comment by NewToLinux123** [comment]
![Screenshot from 2024-12-07 19-33-47](https://github.com/user-attachments/assets/5657df63-aece-43a8-93eb-8f5f59186123)
