### ISSUE TITLE
Sober 'config.json' file not existing in the Sober directory

### ISSUE THREAD

**Issue by NewToLinux123** [vinegarhq/sober#494]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i use Sober i use the '--opengl' argument. But in the newest update it said I had to add it in the config.json file in "/home/fundipp0/.var/app/org.vinegarhq.Sober/config/sober"... but it's not there. I have searched using the file explorer and cant find the directory or config.json, just some other json files with config in the name. Please fix this fast because i want to carry on playing roblox on my only PC. When I try without argument to let the file be created, It says "Failed to parse config JSON file. Check if there are any misplaced commas or other formatting errors" Pls help

**Comment by Tarvey** [comment]
>     * [x]  I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.


maybe if you did then you would find #490, you said that you didnt know what "launch without arguments mean", just type in the terminal `flatpak run org.vinegarhq.Sober`, that will create the config file, dont add the --opengl right now, because that doesnt create the config file (for some reason)

also, i just realized that the file path in this issue and #490 is the same... this could be the same person

**Comment by NewToLinux123** [comment]
I have the same problem but no one answers me on problem #490 so I made an issue myself. But When I try to launch without arguments, it says could not parse json file, check if there are any misplaced commas.

**Comment by NewToLinux123** [comment]
> > ```
> > * [x]  I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.
> > ```
> 
> maybe if you did then you would find #490, you said that you didnt know what "launch without arguments mean", just type in the terminal `flatpak run org.vinegarhq.Sober`, that will create the config file, dont add the --opengl right now, because that doesnt create the config file (for some reason)
> 
> also, i just realized that the file path in this issue and #490 is the same... this could be the same person

I just checked, problem #490 and yes they did answer but it didn't help. Im very sorry
