### ISSUE TITLE
Sober requesting an unavailable version at launch

### ISSUE THREAD

**Issue by MrLepoischiche** [vinegarhq/sober#504]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello,

I never had any issue with Sober when I first installed it last week. (Except the bot verification failing on login page. I just used my phone.)
But today, after several attempts at launching the game like the usual, I receive nothing.

I tried uninstalling and reinstalling it (thus forgetting to check the log files...), and now here I am with a fresh new Sober that requires a version that has not come out yet, even on the Play Store :
![Screenshot from 2024-12-09 15-56-21](https://github.com/user-attachments/assets/3df567da-a5c7-4978-8523-42d854a46c0a)

Is it really a bug? Or is it a legit beta version of the game that is about to, or has, come out?

Thank you for your time.

EDIT : I checked again on the Play Store : it is a stable version in there. It's just not out on APKMirror yet.

**Comment by MrLepoischiche** [comment]
False alarm : I thought the automatic download was actually getting stuck trying to reach the Google Play servers, from what little my terminal was saying.
It turns out it does go through, and my Roblox was updated mere seconds ago. Now it launches again, as usual.

I apologize for my ignorance.

**Comment by youssefdesy** [comment]
i have the same issue and its failing to reach update services unlike you
