### ISSUE TITLE
failing to install roblox through update services

### ISSUE THREAD

**Issue by youssefdesy** [vinegarhq/sober#505]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i usually update roblox from apkmirror but this time its request a bundle that isnt available on apkmirror, here is the log
(or what the terminal says)

`(sober_services:5): Gdk-WARNING **: 21:29:14.671: Vulkan: ../src/amd/vulkan/radv_physical_device.c:1984: Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:752: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:783: FINISHME: support more multi-planar formats with DRM modifiers
ERROR: install_bundle: Could not copy file to target: /home/youssefdes/.var/app/org.vinegarhq.Sober/data/sober/assets/base.apk
Couldn't install Roblox using update service, retrying...
ERROR: install_bundle: Could not copy file to target: /home/youssefdes/.var/app/org.vinegarhq.Sober/data/sober/assets/base.apk
Couldn't install Roblox using update service, falling back to manual install.
`

**Comment by tunis4** [comment]
fixed, run `flatpak update`
