### ISSUE TITLE
Failed to conparse json file

### ISSUE THREAD

**Issue by NewToLinux123** [vinegarhq/sober#507]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I want to turn opengl to true, I go to my fflags to turn it to true but it says file does not exist in directory. So I need to run flatpak run org.vinegarq.Sober to let the file be created. When I do that, it says "Failed to conparse JSON file." Can someone help.

thank you

![Screenshot from 2024-12-09 18-46-13](https://github.com/user-attachments/assets/9a65e457-e7f7-4a02-80af-5130f4fc5574)

**Comment by tunis4** [comment]
stop spamming the issue tracker. you have created 6 issues about this. you cant even remember that you already opened an exact copy of this one. the error is as simple and obvious as possible. you were already told what to do in a previous issue. if you cant even follow these simple instructions idk what to tell you.
