### ISSUE TITLE
In some games, the mouse isn't locked.

### ISSUE THREAD

**Issue by ManMar4254** [vinegarhq/sober#51]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

In some games, such as Welcome to Bloxburg and Greenville and Bedwars, the mouse isn't locked properly, which can cause it to move outside the game window.

### Workarounds

Press F11 to enter full screen mode. This will prevent the mouse from leaving the Roblox window, although it will still not be locked.

### Video

# Welcome to Bloxburg (The mouse is now fixed in Bloxburg with the latest Sober version)

# Before

https://github.com/user-attachments/assets/98fd1703-9476-4fd4-9837-3d0a3ce7fe58

# After

https://github.com/user-attachments/assets/2f3f3439-2e88-4506-9a41-50f3abeef163

# Greenville

https://github.com/user-attachments/assets/34e2262a-9cee-4b77-88e5-c1463627dbac

# Bedwars

https://github.com/user-attachments/assets/04ecdb54-1f01-4e69-bcff-50a50c1c6e31

### Roblox Experience link

https://www.roblox.com/games/185655149/Welcome-to-Bloxburg

https://www.roblox.com/games/891852901/Greenville

https://www.roblox.com/games/6872265039/BedWars-ARENA-LTM

**Comment by comdlg32** [comment]
Also happening in JTOH's legacy event.

https://github.com/user-attachments/assets/d1bc90de-2d31-47d8-975c-e9551b24379c

**Comment by sunglocto** [comment]
Happening in PHIGHTING! and Project Remix as well. A quick fix for this is pressing F11 to go into fullscreen.

**Comment by tunis4** [comment]
fixed
