### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by Igotnoidea42** [vinegarhq/sober#510]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This is a weird problem. For starters, I am using Mint, and I think I fucked up quite a bit. 
I tried, a few days ago, to update Sober, but since it didn't seem to work (the app simply didn't want to open), I tried to delete Sober in order to then reinstall it. My problem is that this didn't work: I can't seem to uninstall the app and, when I try to install it (either via a command line or via a flatpack document), it doesn't work, saying that the app is already installed. Of course, I still cannot open sober, there's no error message, it just doesn't do anything.
I did try the command "flatpack update", but it tells me that the command is not found. Can anyone help? Sorry if my explanation was confusing.

**Comment by lagerror101** [comment]
you are supposed to type "flatpak update" in terminal not flatpack update
