### ISSUE TITLE
Weird error I cannot fix.

### ISSUE THREAD

**Issue by TrashLinuxUser** [vinegarhq/sober#511]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The error says "ldconfig failed, exit status 256" And I cannot fix it, I am on ubuntu and using the Flathub app, in fact, I cannot use any Flathub app that was installed, Please help.

NOTE: I cannot find my error reported anywhere else, maybe I have bad eyes, but If I am reporting an error that has already been reported, I am very sorry.

**Comment by tunis4** [comment]
> I cannot use any Flathub app that was installed

then why are you reporting this here if its not a sober issue
