### ISSUE TITLE
Sober not launching

### ISSUE THREAD

**Issue by sam0622** [vinegarhq/sober#512]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Upon trying to open sober, nothing happens

sudo dmesg | grep sober returns: 
[  240.390519] x86/split lock detection: #AC: sober/4410 took a split_lock trap at address: 0x555ec0c767e3
[  240.415005] x86/split lock detection: #AC: sober/4434 took a split_lock trap at address: 0x555ec0c767ec
[  240.428495] x86/split lock detection: #AC: sober/4433 took a split_lock trap at address: 0x555ec0c767e3
[  240.781796] x86/split lock detection: #AC: sober/4436 took a split_lock trap at address: 0x555ec0c767ec
[  241.911966] sober[4331]: segfault at ffffffffffbffffe ip 00007f0ea9e9648d sp 00007fff8b0ce8a8 error 5 in libc.so.6[18448d,7f0ea9d3a000+175000] likely on CPU 8 (core 0, socket 0)
[  242.222054] sober[4433]: segfault at 180 ip 00007fb7fda3c6ce sp 00007fb7f8dfad40 error 4 in libnvidia-eglcore.so.565.57.01[c3c6ce,7fb7fd039000+c4b000] likely on CPU 0 (core 0, socket 0)
[  256.984884] x86/split lock detection: #AC: sober/4488 took a split_lock trap at address: 0x556512ba87e3
[  257.004519] x86/split lock detection: #AC: sober/4499 took a split_lock trap at address: 0x556512ba87ec
[  257.016946] x86/split lock detection: #AC: sober/4498 took a split_lock trap at address: 0x556512ba87e3
[  257.180888] x86/split lock detection: #AC: sober/4501 took a split_lock trap at address: 0x556512ba87ec
[  258.210388] sober[4498]: segfault at 180 ip 00007fd68d83c6ce sp 00007fd688bfad40 error 4 in libnvidia-eglcore.so.565.57.01[c3c6ce,7fd68ce39000+c4b000] likely on CPU 0 (core 0, socket 0)
[  278.847572] x86/split lock detection: #AC: sober/4639 took a split_lock trap at address: 0x55f0f4d2a7e3
[  278.867065] x86/split lock detection: #AC: sober/4650 took a split_lock trap at address: 0x55f0f4d2a7ec
[  278.880743] x86/split lock detection: #AC: sober/4649 took a split_lock trap at address: 0x55f0f4d2a7e3
[  279.045819] x86/split lock detection: #AC: sober/4652 took a split_lock trap at address: 0x55f0f4d2a7ec
[  279.510652] sober[4649]: segfault at 180 ip 00007f044583c6ce sp 00007f0440bfb190 error 4 in libnvidia-eglcore.so.565.57.01[c3c6ce,7f0444e39000+c4b000] likely on CPU 8 (core 0, socket 0)
[  292.125536] x86/split lock detection: #AC: sober/4747 took a split_lock trap at address: 0x563720a317e3
[  292.146655] x86/split lock detection: #AC: sober/4758 took a split_lock trap at address: 0x563720a317ec
[  292.158842] x86/split lock detection: #AC: sober/4757 took a split_lock trap at address: 0x563720a317e3
[  292.320353] x86/split lock detection: #AC: sober/4761 took a split_lock trap at address: 0x563720a317ec
[  292.603682] x86/split lock detection: #AC: sober/4760 took a split_lock trap at address: 0x563720a317e3
[  292.825581] sober[4757]: segfault at 180 ip 00007f242da3c6ce sp 00007f2428dfb190 error 4 in libnvidia-eglcore.so.565.57.01[c3c6ce,7f242d039000+c4b000] likely on CPU 8 (core 0, socket 0)
[11968.022371] x86/split lock detection: #AC: sober/5773 took a split_lock trap at address: 0x55f0c20617e3
[11968.041021] x86/split lock detection: #AC: sober/5785 took a split_lock trap at address: 0x55f0c20617ec
[11968.064576] x86/split lock detection: #AC: sober/5784 took a split_lock trap at address: 0x55f0c20617e3
[11968.219415] x86/split lock detection: #AC: sober/5789 took a split_lock trap at address: 0x55f0c20617ec
[11968.286667] x86/split lock detection: #AC: sober/5788 took a split_lock trap at address: 0x55f0c20617ec
[11968.720029] sober[5784]: segfault at 180 ip 00007fbecf03c6ce sp 00007fbeca3fb190 error 4 in libnvidia-eglcore.so.565.57.01[c3c6ce,7fbece639000+c4b000] likely on CPU 0 (core 0, socket 0)
[11988.004809] x86/split lock detection: #AC: sober/5852 took a split_lock trap at address: 0x55f58b6d07e3
[11988.024931] x86/split lock detection: #AC: sober/5870 took a split_lock trap at address: 0x55f58b6d07ec
[11988.049375] x86/split lock detection: #AC: sober/5869 took a split_lock trap at address: 0x55f58b6d07e3
[11988.240973] x86/split lock detection: #AC: sober/5873 took a split_lock trap at address: 0x55f58b6d07ec
[11988.462090] x86/split lock detection: #AC: sober/5874 took a split_lock trap at address: 0x55f58b6d07e3
[11988.717984] sober[5869]: segfault at 180 ip 00007f531563c6ce sp 00007f53109fb190 error 4 in libnvidia-eglcore.so.565.57.01[c3c6ce,7f5314c39000+c4b000] likely on CPU 7 (core 7, socket 0)

fastfetch output: 
OS: Fedora Linux 41 (KDE Plasma) x86_64
Host: GS76 Stealth 11UG (REV:1.0)
Kernel: Linux 6.11.10-300.fc41.x86_64
Uptime: 3 hours, 25 mins
Packages: 3175 (rpm), 19 (flatpak-system), 8 (flatpak-user)
Shell: fish 3.7.0
Display (BOE09F9): 2560x1440 @ 240 Hz (as 2048x1152) in 17" [Built-in]
DE: KDE Plasma 6.2.4
WM: KWin (Wayland)
WM Theme: Breeze
Theme: Breeze (Dark) [Qt], Breeze [GTK3]
Icons: breeze-dark [Qt], breeze-dark [GTK3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK3/4]
Cursor: breeze (24px)
Terminal: konsole 24.8.3
Terminal Font: MesloLGS NF (10pt)
CPU: 11th Gen Intel(R) Core(TM) i9-11900H (16) @ 4.90 GHz
GPU 1: NVIDIA GeForce RTX 3070 Mobile / Max-Q
GPU 2: Intel UHD Graphics @ 1.45 GHz [Integrated]
Memory: 5.34 GiB / 31.04 GiB (17%)
Swap: 0 B / 8.00 GiB (0%)
Disk (/): 940.93 GiB / 1.86 TiB (49%) - btrfs

Logs attatched:
[latest.log](https://github.com/user-attachments/files/18088337/latest.log)

**Comment by sam0622** [comment]
P.S. running flatpak update returns 
"Looking for updates...
Nothing to do."

**Comment by youma64** [comment]
Same here, but from the flatpak github, they said that if you are updating your nVidia driver before they update their reposit (~normally 1 week after the driver system update), you wouldn't be able to launch any application using your gpu because the flatpak nVidia driver is not the same as your os driver. The only way to fix this is to roll back your graphic driver version and wait the flatpak repot to update to the latest version.

**Comment by reflexran** [comment]
Considering he's using fedora and the rpmfusion repos update about every week this shouldn't be a problem for him, also I don't think that's true since I remember using nvidia drivers less than a week old and still being able to use flatpak apps using my gpu.

**Comment by reflexran** [comment]
also from the logs he provided this doesn't seem to be an issue with his gpu or his gpu drivers.

**Comment by sam0622** [comment]
I'm not exactly sure what happened but about a day later it fixed itself, the computer was not restarted as far as I know, but it did sleep.
