### ISSUE TITLE
Flathub publishing

### ISSUE THREAD

**Issue by mak448a** [vinegarhq/sober#516]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

I like to keep my Flatpak repositories clean with only a few repositories.

### Describe the Solution you'd Like

Could you publish the Sober flatpak to Flathub?

### Describe Alternatives you've considered

Just using the normal installation method.

**Comment by tunis4** [comment]
no

**Comment by mak448a** [comment]
Ok.

**Comment by Henry-Hiles** [comment]
> no

Why??

**Comment by Henry-Hiles** [comment]
> Propose a reason as to why to switch to Flathub.
> 
> Having a self-managed repository gives Sober more control over whats put out.

Discoverability: You could just search roblox on flathub and find it, leading more people to use sober.
Authenticity: Being on a central platform like Flathub gives Sober an air of authenticity
Graphical Installation: I've seen multiple helpdesk issues in the VinegarHQ server where people new to Linux (maybe using a Steam Deck) can't figure out how to open sober, or maybe don't even know how to open a terminal. Having a graphical installation route would simplify the installation process.


Also, you can still keep your remote as a backup, or a source with faster updates.

**Comment by apprehensions** [comment]
You make some valid points, but regarding graphic installation, it is just as easy as downloading the .flatpakref file, and having your DE automatically add it. Or, just one command. The rest of the issues afterwards arent a result of Flatpak, but simply the skill level of Sober usage.

**Comment by Henry-Hiles** [comment]
> You make some valid points, but regarding graphic installation, it is just as easy as downloading the .flatpakref file, and having your DE automatically add it. Or, just one command. The rest of the issues afterwards arent a result of Flatpak, but simply the skill level of Sober usage.

True, but its still easier to say to people: open software, search sober, hit install, rather than open your terminal emulator and paste this command (or manually type it out)

**Comment by Henry-Hiles** [comment]
Either way, I think being on flathub will add a lot of value, with minimal reprecussions. Can this be reopened, at least for discussion? 🙂️

**Comment by Henry-Hiles** [comment]
> Further discussion can be moved to Discord.

Why?

**Comment by apprehensions** [comment]
Because its easier to communicate there rather than on a issue tracker?

**Comment by Henry-Hiles** [comment]
> Because its easier to communicate there rather than on a issue tracker?

Hmm. I find this much more discoverable, as it's picked up by a search engine and can be read without an account for others to read the conversation and result. That's fine though. I'm @quadradical on discord.
