### ISSUE TITLE
Add a "please update" prompt.

### ISSUE THREAD

**Issue by alejandro-alzate** [vinegarhq/sober#517]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

When a update is available sober closes silently

### Describe the Solution you'd Like

A simple prompt saying that is necessary to update.
Bonus points if the terminal or the package manager can be invoked from within that prompt.

### Describe Alternatives you've considered

A toast notification would be a good option also

**Comment by tunis4** [comment]
we already have a prompt but it was broken, we fixed it in the latest update

**Comment by alejandro-alzate** [comment]
> we already have a prompt but it was broken, we fixed it in the latest update

Understood, now would you look at that? that there is rather ironic.
