### ISSUE TITLE
Keep flatpak commits/versions available after updates

### ISSUE THREAD

**Issue by GalaxyShard** [vinegarhq/sober#525]
Currently whenever a new version of Sober is released, the previous version is made completely unavailable. This can be a problem when the latest version has a regression, as it prevents users from falling back or checking previous versions to see if the issue still appears.

This could also potentially be the source of problems like #524; the old flatpak commit `a91bc842a980f22e1bbc025ee30d745f9bb6fb71bc712c61199e238aa801b23b`  was removed in favor of the current `cd5e3538887b7feb09ffae215ea7f6d27a9de9e1711ba3f2cb3bfd36e61c2581`, causing an error when installing Sober rather than downloading the previous version and updating.

Although Roblox will prompt old clients to update, requiring a update to Sober regardless of any new bugs, a client that is one or two releases out of date will typically not receive any errors. Keeping old flatpak commits/versions available shouldn't cause many issues.

The following two commands can be checked to see the flatpak commit/version history:

```
flatpak remote-info --log sober-origin org.vinegarhq.Sober
flatpak remote-info --log sober org.vinegarhq.Sober
```

**Comment by tunis4** [comment]
old versions not being available is intentional and will probably not be changed

idk whats causing #524 since its been 4 days since the latest update

**Comment by GalaxyShard** [comment]
I think it would be helpful to keep one or two versions back so that users are able to downgrade in case of a problem.

**Comment by apprehensions** [comment]
Downgrading is intentionally not supported.

**Comment by sammywammythewam** [comment]
i have no idea my mine wont download either ¯\_(ツ)_/¯
