### ISSUE TITLE
Failure to allocate memory

### ISSUE THREAD

**Issue by Temmie508** [vinegarhq/sober#526]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System specs: 
![image](https://github.com/user-attachments/assets/1e22f3f2-91bf-46ca-a5b0-c26636419dab)
I'm running Ubuntu 24.04.1 LTS and Sober crashed, saying "Failed to allocate memory". Here's the log:
[latest.log](https://github.com/user-attachments/files/18139215/latest.log) At the end, it says: "OutOfMemoryGraphics".

This issue happened with me multiple times, no matter the graphics settings. I'm not sure if this only happens in The Strongest Battlegrounds after attacking for a bit, it also occurred when I played Decaying Winter, but one of their recent updates where they've incorporated a hidden part of the map that was supposed load in when triggered, might've fixed it. I've also noticed when I play, the Memory's performance stats in Roblox is always below 2GBs of RAM, 1.5GBs of RAM to be exact, once it passes that number, Sober immediately crashes.

### Roblox Experience link

https://www.roblox.com/games/10449761463/The-Strongest-Battlegrounds

**Comment by tunis4** [comment]
https://github.com/vinegarhq/sober/issues/465#issuecomment-2512403311
