### ISSUE TITLE
Cannot open games using flatpak run org.vinegarhq.Sober [URI]

### ISSUE THREAD

**Issue by Xgameisdabest** [vinegarhq/sober#529]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

A small problem is that I can't not open games from terminal using this command:
flatpak run org.vinegarhq.Sober [URI]
for example:
flatpak run org.vinegarhq.Sober roblox://games/292439477/phantom-forces
It just open the app not launching the game from the URI
If i did something wrong here pls correct me

**Comment by k1yrix** [comment]
There is no parameters to launch games through the launch URL. The only valid parameters after the normal run command are `--opengl`, `--bootstrap`, and `--touch-mode`

**Comment by Xgameisdabest** [comment]
cuz when i run the help option it gave me this output:
flatpak run org.vinegarhq.Sober -h 
Usage: sober [--bootstrap] [URI]
I wonder what the URI does

**Comment by k1yrix** [comment]
actually I was told that that is a valid parameter, it's just you're inputting it wrong

one moment while I get clarification

**Comment by k1yrix** [comment]
so the correct launch parameter is: `flatpak run org.vinegarhq.Sober placelauncherurl:https://www.roblox.com/Game/PlaceLauncher.ashx?request=RequestGame&placeId=[game-id]` where `[game-id]` is as it suggests.

**Comment by k1yrix** [comment]
lmk if it doesn't work so I can get further clarification

**Comment by Xgameisdabest** [comment]
i ran:
flatpak run org.vinegarhq.Sober placelauncherurl:https://www.roblox.com/Game/PlaceLauncher.ashx?request=RequestGame&placeId=292439477  

and it gave me this output:
zsh: no matches found: placelauncherurl:https://www.roblox.com/Game/PlaceLauncher.ashx?request=RequestGame

probably something is wrong in the command

**Comment by tunis4** [comment]
`flatpak run org.vinegarhq.Sober "roblox://experience?placeId=1818"`

make sure the uri is in quotes

**Comment by Xgameisdabest** [comment]
how do you guys know and get those information

**Comment by tunis4** [comment]
i am one of the devs

**Comment by Xgameisdabest** [comment]
oh ok, cool, can close this now. Thanks for you guys help
