### ISSUE TITLE
Camera control settings: Shift lock

### ISSUE THREAD

**Issue by wisheth** [vinegarhq/sober#53]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

The first game I tried booting when testing Sober was Juke's Towers of Hell, which many jumps in require use of shift lock as implemented in Roblox to make.

### Describe the Solution you'd Like

It's possible to lock the mouse on the system with first person mode, but that is the only method; I'd like to be able to use shift lock as is present in the Windows client as well. I imagine the feature would have parity with the Windows client in the settings menu if possible.

### Describe Alternatives you've considered

First person mode is similar, but not the same, especially in Roblox obbies where the body needs to be seen. Games like Phighting implement and force these camera settings, so it may be implemented already, but there is no toggle. It may be possible to activate and toggle it externally, but that might have unintended interactions with some games that changes the key shift lock is activated on where something else is bound to shift instead.

**Comment by apprehensions** [comment]
Shift lock is in Sober, you need to enable it in settings.
