### ISSUE TITLE
Sober gets frozen on "Roblox installation is required, starting onboarding flow UI..."

### ISSUE THREAD

**Issue by SaveliiLisnichenko** [vinegarhq/sober#540]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I just switched to MX Linux today, and I installed flatpak and then Sober, everything is going as planned so far. Then, I try launching it, and nothing happens. When I launch it with `flatpak run org.vinegarhq.Sober`, I get the following:
```
$ flatpak run org.vinegarhq.Sober
Roblox installation is required, starting onboarding flow UI...
```
and it doesn't crash or anything, it just stays like that until I stop it.

If anyone can explain how to fix this or link to a github issue similar/same to mine that has a fix, please do. Thanks in advance!

**Comment by Sweeistaken** [comment]
If you're using MX Linux, what Desktop Environment are you using, and is it X11 or Wayland?

**Comment by Sweeistaken** [comment]
I'm trying to reproduce this on Debian Testing on XFCE, the following logs should also show a LibAdwaita window:
![image](https://github.com/user-attachments/assets/36965d7b-01bb-49f5-83d0-7ba8f599b45a)
![image](https://github.com/user-attachments/assets/a511572a-bed7-41fd-bcbf-ec1e6b36439f)

**Comment by SaveliiLisnichenko** [comment]
> If you're using MX Linux, what Desktop Environment are you using, and is it X11 or Wayland?

I am using Xfce and X11

**Comment by SaveliiLisnichenko** [comment]
> I'm trying to reproduce this on Debian Testing with XFCE, the following logs should also show a LibAdwaita window: ![image](https://private-user-images.githubusercontent.com/120145778/397898909-36965d7b-01bb-49f5-83d0-7ba8f599b45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDc1MzcsIm5iZiI6MTczNDc0NzIzNywicGF0aCI6Ii8xMjAxNDU3NzgvMzk3ODk4OTA5LTM2OTY1ZDdiLTAxYmItNDlmNS04M2QwLTdiYThmNTk5YjQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTc1MGNmMjU0NWI5MzIyMWExMWFlODM3YmZkZTQyYjFiYjYwM2M2ZjVlM2NmZjY5MmRiMTFkZTY3NDQ3Y2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AJOY7w1QfX6CdbrgOWn2FCPr77-av4AMTfA3t_PtiHg) ![image](https://private-user-images.githubusercontent.com/120145778/397898920-a511572a-bed7-41fd-bcbf-ec1e6b36439f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDc1MzcsIm5iZiI6MTczNDc0NzIzNywicGF0aCI6Ii8xMjAxNDU3NzgvMzk3ODk4OTIwLWE1MTE1NzJhLWJlZDctNDFmZC1iY2JmLWVjMWU2YjM2NDM5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwMjEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTNlYWRhNTk1MmY4NDEzMDQ0NzRmZjJhYWNmOTcyYjY1MWQzYWY0N2E0YzBmMTRjNWM1M2FhM2MxYWM0YjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BfD0UMQbFDIaCZpjxhwO8uaxxaxrOLfUpriC93PvrHk)

Yes the window does not appear

**Comment by SaveliiLisnichenko** [comment]
I switched over to EndeavourOS with Xfce4 just now as numerous other flatpak apps were broken on MX Linux, and the issue is fixed now. I'm guessing this is most likely a flatpak issue and not a Sober issue.
