### ISSUE TITLE
Add UI scaling for 4K

### ISSUE THREAD

**Issue by Yarix812** [vinegarhq/sober#550]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

On my 4K monitor Sober's UI is very small

### Describe the Solution you'd Like

Add UI scaling based on monitor resolution

### Describe Alternatives you've considered

The alternative is adding settings for UI scale

### Additional context

I'm using Linux Mint 22 Cinnamon

**Comment by tunis4** [comment]
we have experimental ui scaling but its disabled by default since it might be broken. if you want to try it add `"enable_hidpi": true` to `~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

**Comment by Yarix812** [comment]
Thanks, it worked!

**Comment by Yarix812** [comment]
> we have experimental ui scaling but its disabled by default since it might be broken. if you want to try it add `"enable_hidpi": true` to `~/.var/app/org.vinegarhq.Sober/config/sober/config.json`

Thanks, it worked!
