### ISSUE TITLE
It does not open.

### ISSUE THREAD

**Issue by Paritopa** [vinegarhq/sober#551]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The lights in my house shut and now when I'm trying to open Sober it doesn't.
When I'm trying to run Sober in the terminal it shows this.
```
:~$ flatpak run org.vinegarhq.Sober

FATAL: Failed to parse state JSON file.
```
What I do????????????
I tried uninstalling and installing again but this keeps happening
I even removed the remote. It is the "fsck" command fault?

**Comment by reflexran** [comment]
try to run `flatpak uninstall --delete-data org.vinegarhq.Sober -y && flatpak install --user https://sober.vinegarhq.org/sober.flatpakref -y` (try uninstalling using the delete-data flag)

**Comment by Paritopa** [comment]
> try to run `flatpak uninstall --delete-data org.vinegarhq.Sober -y && flatpak install --user https://sober.vinegarhq.org/sober.flatpakref -y` (try uninstalling using the delete-data flag)

It works.
Thanks

**Comment by apprehensions** [comment]
If it works, close the issue...
