### ISSUE TITLE
issue(please reply)

### ISSUE THREAD

**Issue by gopuatop100** [vinegarhq/sober#557]
![Screenshot at 2024-12-28 09-25-30](https://github.com/user-attachments/assets/409e58c4-81df-4745-8bcc-b8b1dc65d080)
from 5 days i am playing roblox on sober it is running very well today morning i decided to play this thing comes how to update please day (please reply)

**Comment by marvin1099** [comment]
Run this in the teminal:
```
flatpak update -y
```

**Comment by gopuatop100** [comment]
> Run this in the teminal:
> 
> ```
> flatpak update -y
> ```

ok thank u

**Comment by Vlad55432** [comment]
can you literally read, what it says
