### ISSUE TITLE
Incredibly fast camera speed. Game only playable when in FP/shiftlock

### ISSUE THREAD

**Issue by pkhaxor** [vinegarhq/sober#56]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello there! I'm experiencing insanely fast camera rotation when the game in not in fullscreen. When it is fullscreen, the camera tends to be inverted or just overall janky. Basically the only 2 playable options I'm left with is first person or shiftlock. Video attached for clearer understanding. I

https://github.com/user-attachments/assets/b6c71a8a-5336-4472-9628-a2805f122191

**Comment by apprehensions** [comment]
Update the Flatpak.

Mouse lock is only functional in games that ask for it in fullscreen.

**Comment by pkhaxor** [comment]
> Update the Flatpak.
> 
> Mouse lock is only functional in games that ask for it in fullscreen.

This has solved the issue. Thank you!
