### ISSUE TITLE
Custom game chat has no input; textbox doesnt clear on game request

### ISSUE THREAD

**Issue by apprehensions** [vinegarhq/sober#57]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

* The in-game custom chat has no input
* The in-game source-like terminal engine's textbox input doesn't clear and glitches upon command enter

### Roblox Experience link

https://www.roblox.com/games/2746687316/Games-Unite-Testing-Place

**Comment by DazorPlasma** [comment]
UserInputService.InputBegan seems to not fire at all when typing in a TextBox.

**Comment by km9l** [comment]
https://github.com/vinegarhq/sober/issues/99#issuecomment-2293935804
