### ISSUE TITLE
Pressing F1 again doesn't relock mouse

### ISSUE THREAD

**Issue by phonetic112** [vinegarhq/sober#58]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

On Wayland, pressing F1 initially removes the pointer constraint, but pressing F1 again does nothing. Tested on Hyprland and Sway.

**Comment by apprehensions** [comment]
Cannot reproduce on Sway, River, and dwl

**Comment by km9l** [comment]
can you send the game you're experiencing this?

**Comment by phonetic112** [comment]
https://www.roblox.com/games/5315066937/surf

**Comment by Endyrm** [comment]
I experience this on Plasma 6.1.2 (Wayland)

Repeating it with logs in the terminal does not seem to produce relevant information when trying to relock the mouse, unfortunately.

**Comment by JimBimBum** [comment]
Some games use F1 as a help menu bind, i do not know why.

**Comment by Red6785** [comment]
Can reproduce on Plasma 6.1.4 in Pressure.

**Comment by phonetic112** [comment]
seems to be fixed for me after the latest update

**Comment by Endyrm** [comment]
Yup, seems fixed for me too when undergoing testing after the update
