### ISSUE TITLE
Effects stop working once i open sober

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#59]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

for some reason when you open sober, all effects literally explode and stop working
im not sure if this is sober's problem or just me being a goobie snoobert

**Comment by TheShovel** [comment]
are you talking about desktop effects?
sober disables the compositor to improve framerates. If you are on KDE, you can disable that in the system settings
this is not a bug. Once you close sober everything goes back to normal

**Comment by km9l** [comment]
> sober disables the compositor to improve framerates

this is supposed to happen when you go fullscreen btw

**Comment by Amgsdfyhadfgybi** [comment]
> are you talking about desktop effects? sober disables the compositor to improve framerates. If you are on KDE, you can disable that in the system settings this is not a bug. Once you close sober everything goes back to normal

ty
