### ISSUE TITLE
Mouse inputs get captured if the game is unfocused but the player has first person mode/shift lock enabled

### ISSUE THREAD

**Issue by unexp** [vinegarhq/sober#6]
https://github.com/user-attachments/assets/46f184e7-7fe3-44bb-83fc-f8f54d313902

**Comment by apprehensions** [comment]
Does this still occur in up to date versions of Sober?

**Comment by unexp** [comment]
> Does this still occur in up to date versions of Sober?

seems to be fixed

**Comment by Vlad55432** [comment]
yay
