### ISSUE TITLE
Robot 64 camera behaves incorrectly

### ISSUE THREAD

**Issue by lucasmz-dev** [vinegarhq/sober#60]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The camera in Robot 64 can not be moved freely, instead moving in a very broken, stutter-y way. Makes playing very hard.

[2.636.0.626_20240807T232657Z_Player_db012_last.log](https://github.com/user-attachments/files/16535644/2.636.0.626_20240807T232657Z_Player_db012_last.log)

### Roblox Experience link

https://www.roblox.com/games/1111083356/Robot-64

**Comment by km9l** [comment]
i can reproduce this issue. we'll take a look at it.

(also robot64 is one of my favorite roblox games)

**Comment by tunis4** [comment]
same issue happens if you play it on android with a mouse connected to your phone, and the issue only happens on this specific game. the dev probably messed up their camera script. nothing we can do

**Comment by lucasmz-dev** [comment]
Reported to the dev via DevForum (probably the wrong channel though I'm not really aware of any channels to do that :P)
