### ISSUE TITLE
Memory leak on each teleport between places/exit to the menu

### ISSUE THREAD

**Issue by Macosaro** [vinegarhq/sober#64]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

On first launch, memory usage peaks at ~1400 MB depending on the game.
For every rejoin or teleport without Sober being relaunched memory usage rises by ~300 MB depending on the game's content.
This is not an issue in most games but it gradually becomes a problem on games which utilize teleporting between places, for example Entry Point, especially the Ironman challenge which teleports you through all missions in the game.

First join (through the website and not the roblox main menu)
![normal_usage](https://github.com/user-attachments/assets/f3c24f85-527a-4fce-a35d-62018ca152a2)
After getting teleported 10 times
![memory_leak](https://github.com/user-attachments/assets/6c80b40a-6734-4e11-82a1-fa8abb14d8fb)

**Comment by Vlad55432** [comment]
I tested out, and I can confirm this is true.
I tested in [Typical Colors 2](https://www.roblox.com/games/328028363/Typical-Colors-2-NEW-MOBILE-BETA), and there was memory leak. 
Before joining servers (teleporting to roblox logic), average memory use is 1472mb 
![зображення](https://github.com/user-attachments/assets/ddb4a13d-21d1-4740-9da0-0839f1796133)
And after, 2577 mb
![зображення](https://github.com/user-attachments/assets/d7fe30c8-6aa8-4666-83c0-20b27925bfbb)
Full video recording is [here](https://drive.google.com/file/d/18F4XzE7UL3qH9Ey_GYo2wPGZzXIP8_ZK/view?usp=sharing)
Roblox took average 2G of ram on 4th teleport.
So, logically, memory usage for me got higher by 1G.

**Comment by tunis4** [comment]
fixed
