### ISSUE TITLE
It's encountering the Vulkan 'out of memory' error on Intel HD Graphics 4600 Haswell.

### ISSUE THREAD

**Issue by ManMar4254** [vinegarhq/sober#66]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It's showing the 'out of memory' error on Intel HD Graphics 4600 Haswell, likely because Vulkan support is incomplete. The solution would be to add OpenGL support in Sober.

**Comment by ManMar4254** [comment]
It doesn't occur upon launching Sober; rather, it happens when starting certain demanding Roblox games, particularly RF 24. This issue occurs frequently.

**Comment by tunis4** [comment]
its not about vulkan or opengl, you are just running out of vram in those demanding games. as a workaround you can reduce the texture quality with these fflags:
```json
"DFIntTextureQualityOverride": "2",
"DFFlagTextureQualityOverrideEnabled": "True"
```

**Comment by ManMar4254** [comment]
I tested with these flags; it's not happening as frequently, but the 'out of memory' error still persists, causing Roblox to crash.

**Comment by ManMar4254** [comment]
When Sober was using ARM translation, this wasn't happening; it only started when it switched to x86_64.

**Comment by km9l** [comment]
> I tested with these flags; it's not happening as frequently, but the 'out of memory' error still persists, causing Roblox to crash.

if you have enough ram in your system, you should attempt to increase the allocated vram for the igpu

**Comment by ManMar4254** [comment]
I've increased the allocated VRAM to 1GB, the maximum supported by my motherboard, yet the issue persists.

**Comment by km9l** [comment]
> I've increased the allocated VRAM to 1GB, the maximum supported by my motherboard, yet the issue persists.

very odd, may you send the outofmemory error so that we're sure this is the vram bug?

**Comment by ManMar4254** [comment]
[logs.txt](https://github.com/user-attachments/files/16552142/logs.txt)

**Comment by ManMar4254** [comment]
![Captura de imagem_20240808_175521](https://github.com/user-attachments/assets/0b6fd624-06ce-49f8-b5ae-7e7b7dbc69e0)

It's not showing the VRAM usage.

**Comment by ManMar4254** [comment]
Instead of showing 'out of memory,' it now shows 'Fatal glibc error: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' in games with demanding VRAM usage.

**Comment by ManMar4254** [comment]
I managed to solve the VRAM issue, but now a fatal GLIBC error appears: tpp.c:83 (__pthread_tpp_change_priority): assertion failed: new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio). I was able to resolve this error by limiting the core usage with the command: taskset -c 0-1 flatpak run org.vinegarhq.Sober. Now Sober is using only 2 cores; my processor is an i5 4670.
