### ISSUE TITLE
Does not launch, hangs at "Setting default app policy file..."

### ISSUE THREAD

**Issue by ZiArgonX** [vinegarhq/sober#69]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

hangs on `[log @ JNIMain]: TelemetryProtocol::setProcessTimeOverride: 316
[log @ rbx.signalr_jni]: [JNI] OnLoad: ... Done
[log @ rbx.JNIRobloxSettings]: Setting default app policy file: /home/ziora/.var/app/org.vinegarhq.Sober/data/sober/assets/content/guac/defaultConfigs/GuacDefaultPolicy-GlobalDist.json
` and then it just stops with a blank screen it was working fine before 
OS=EndevourOS(Arch)
İt was working great and it stopped working 
logs are empty

**Comment by Macosaro** [comment]
Check your internet connection, this only happens when Sober can't connect to Roblox servers (though it would be preferable if it didn't just hang in this case)

**Comment by ZiArgonX** [comment]
> Check your internet connection, this happens when Sober can't connect to Roblox servers (though it would be preferable if it didn't just hang in this case)

thanks could be because ısp blocked roblox used dpi bypasser via proxychain work on firefox but not on sober is there any way to add a http proxy to the sober?
