### ISSUE TITLE
Joining a server directly does not send you to desired server

### ISSUE THREAD

**Issue by ajd07** [vinegarhq/sober#7]
Lets say you want to go to Server B, but you keep getting sent to Server A
You join Server B directly
For some reason it just goes to server A regardless...?????

**Comment by apprehensions** [comment]
Through the servers page in the app?

**Comment by ajd07** [comment]
Yep, through server page on site and app
You can join people directly though.

**Comment by wilsontulus** [comment]
I agree, currently it behaves like another big green play button.

Here's me trying to join a server with only one player in it.
https://github.com/user-attachments/assets/fee2132b-f457-4c21-8c40-726ad57752fd
Here's another, with green play button. Similar behavior, right?
https://github.com/user-attachments/assets/0804e6a2-7f35-4330-9c36-696e997ec827
However, if I tried an inspect element escape method to another game, it does teleport you to that specific game, but still it's the same green play button behavior.
https://github.com/user-attachments/assets/2993ff6d-564e-40f7-8f26-95c07f644c73

**Comment by qederal** [comment]
i tried running in terminal to see if it spits out anything bad when i try joining a server but it doesnt seem to, might be a bit trickier to solve it seems

**Comment by ajd07** [comment]
I brought it up in the Discord before and it seems like it could be some information that isn't registered by Sober right now? This among other things don't get sent/received if I remember, so it just defaults.

**Comment by Mircas001** [comment]
SAME ISSUE

**Comment by ajd07** [comment]
Apparently fixed upstream! Should be released in an update or two I'd assume.
