### ISSUE TITLE
unable to install flatpak through recommended methods

### ISSUE THREAD

**Issue by michaelBelsanti** [vinegarhq/sober#70]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I am unable to install the flatpak through either of the methods listed on the site. 

```
fsh ➜ flatpak install --user https://sober.vinegarhq.org/sober.flatpakref
error: Can't load uri https://sober.vinegarhq.org/sober.flatpakref: Server returned status 403

fsh ➜ flatpak install ./sober.flatpakref
The remote 'sober', referred to by 'org.vinegarhq.Sober' at location https://sober.vinegarhq.org/repo/ contains additional applications.
Should the remote be kept for future installations? [Y/n]: y
error: No such ref 'app/org.vinegarhq.Sober/x86_64/master' in remote sober
```

**Comment by apprehensions** [comment]
Most likely Cloudflare detected your IP as a Bot, please try again later.

**Comment by WingsnDings** [comment]
im experiencing this issue as well after i uninstalled it when roblox updated. You just wait?

**Comment by WingsnDings** [comment]
im experiencing this issue as well after i uninstalled it when roblox updated. You just wait?

**Comment by iamse7en** [comment]
I'm getting a slightly different error: `No such ref 'app/org.vinegarhq.Sober/aarch64/master' in remote sober`
Is there an aarch64 build? Trying to install on Switch running L4T Ubuntu Jammy. Didn't think it'd work but wanted to try. The Android LineageOS version of Roblox on the Switch is too slow.

**Comment by tunis4** [comment]
> I'm getting a slightly different error: `No such ref 'app/org.vinegarhq.Sober/aarch64/master' in remote sober` Is there an aarch64 build? Trying to install on Switch running L4T Ubuntu Jammy. Didn't think it'd work but wanted to try. The Android LineageOS version of Roblox on the Switch is too slow.

aarch64 isnt supported

**Comment by awesomefroggy29** [comment]
> For some bizarre reason, I was able to install it using a distrobox container. I created a basic fedora one with `distrobox create --init`, installed flatpak in it, then installed the package. Since distrobox containers share your home directory, it still gets installed on your primary OS.

wait, in arm64? because if so, how? and can it be done in ubuntu? i am running on an orange pi 5

**Comment by michaelBelsanti** [comment]
no, this was on x86, its just a way to get around the 403 error. You could try installing the package with the `--arch x86_64` flag and running it using Box64.

**Comment by awesomefroggy29** [comment]
ok ill try

**Comment by awesomefroggy29** [comment]
it didnt word with box64... is there anything else i can try?

**Comment by michaelBelsanti** [comment]
you can try fex-emu, that's the only other option I know of.

-------- Original Message --------

**Comment by shunoni** [comment]
> you can try fex-emu, that's the only other option I know of.
> […](#)

does this work?

**Comment by awesomefroggy29** [comment]
@SC-MC-Mod-Dev no, because fex cant really get into flatpak unfortunately. however, sober is working on an arm version, you can find the progress here: https://github.com/vinegarhq/sober/issues/1221

however, arm64 is not their top priority. so, I decided to have a go at it myself. you can see my progress here: https://github.com/awesomefroggy29/purified
