### ISSUE TITLE
Broken pthread calls in certain games

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#74]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

sakura stand keeps crashing for some reason

### Roblox Experience link

https://www.roblox.com/games/8534845015/KAIJU-RED-MIST-Sakura-Stand

**Comment by Amgsdfyhadfgybi** [comment]
?

**Comment by apprehensions** [comment]
Duplicate of #103
