### ISSUE TITLE
Cursor is not unlocked when game is paused.

### ISSUE THREAD

**Issue by Scubder** [vinegarhq/sober#75]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When in first person, the cursor is supposed to be unlocked when you pause. It stayed locked for me.
I've made sure Sober is up to date.
Also, scrolling through the UI is fast and jumpy.
I am experiencing these issues on Ubuntu 24.04, KDE Plasma (Wayland), AMD64.
APK source is apkmirror.com

**Comment by TTVTheCats** [comment]
Same here on EndeavourOS KDE Plasma X11

**Comment by TheShovel** [comment]
press F1

**Comment by Scubder** [comment]
> press F1

Works, thx
