### ISSUE TITLE
Automatically download a Roblox APK from a trusted source

### ISSUE THREAD

**Issue by ghost** [vinegarhq/sober#76]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

No.

### Describe the Solution you'd Like

When opening Sober for the first time, it should ask if you would like it to automatically download the APK for you, or if you wanted to select it yourself.

### Describe Alternatives you've considered

One of alternatives i thought of for this could be that once clicking the Download button, Sober just opens APKmirror or another trusted site on your web browser, and then its going to ask for the apk

**Comment by CrimsonXMC** [comment]
The last response to a request like this was that it won't happen because Sober doesn't want to do anything that could lead to roblox getting mad at the project. The chance of this getting implemented is approximately 0% unless roblox ever starts distributing the apk through their website.

**Comment by CapnRyna** [comment]
This feature has been requested before (i.e: #11) and has been answered with a strict "no." It raises legal concerns and Sober is legally not allowed to distribute an APK like that. Please read previous issues before creating a issue of your own.
