### ISSUE TITLE
Controller not working on steam deck.

### ISSUE THREAD

**Issue by TheOneAndOnly-Loup** [vinegarhq/sober#78]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The steam decks controller isn’t detected by sober. I have to use a controller profile where the left stick is wasd and right stick is mouse. This isn’t ideal.

**Comment by tunis4** [comment]
try `flatpak override --user --device=all org.vinegarhq.Sober`

**Comment by TheOneAndOnly-Loup** [comment]
@tunis4 Thx this worked
