### ISSUE TITLE
Fix UserInputService:GetStringForKeyCode() on KeyCode numbers returning the KeyCode for the Numbers

### ISSUE THREAD

**Issue by RelicalFire** [vinegarhq/sober#79]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When testing some code, `game:GetService("UserInputService"):GetStringForKeyCode(Enum.KeyCode.One)` will return "Enum.KeyCode.One" instead of "1", this is for all Enum.KeyCodes which are numbers, no clue if this is a bug related to Android or a Sober bug. But, this does work fine in Vinegar's Studio.

**Comment by tunis4** [comment]
android bug, cant fix
