### ISSUE TITLE
Sometimes, games get confused if you're on mobile or not

### ISSUE THREAD

**Issue by ajd07** [vinegarhq/sober#8]
This is likely an issue with just using an APK but I'm not sure.
This was happening on [Dungeon Delver, which has support for both mobile and PC.](https://www.roblox.com/games/2982639429/Dungeon-Delver-ANNUAL-UPDATE) For the record, [this is for a check related to if it should use mobile controls or PC controls.](https://cdn.discordapp.com/attachments/1268755260072267888/1269251436752142367/image.png?ex=66af6204&is=66ae1084&hm=2677249d5c524b382887d79829cce2c91bd3212a9cf37b48a2703a5ef25179c4&)
Does not happen on waydroid, but it usually just defaults to mobile controls on there.
This feels like an issue with it not detecting mouse properly? I'm confused.
If this is an issue with the game provided itself, then I'll forward it to the dev with the reason so this can be patched on their end.

**Comment by ajd07** [comment]
update
x86 patches this issue

**Comment by apprehensions** [comment]
ypie
