### ISSUE TITLE
Mouse Lock Indicator Feature

### ISSUE THREAD

**Issue by KutaG59** [vinegarhq/sober#80]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Yes, its related to the "Mouse Locking" issue within Sober.

### Describe the Solution you'd Like

An indicator / Overlay of some sort that lets me know when ive toggled/untoggled F1. 

### Describe Alternatives you've considered

Common sense and remembering to just click F1 regardless.

### Additional context

As I can just click F1 anyways to unlock/lock my mouse, I've seen multiple users want to know when its being used/not being used. I feel like adding an optional arg to enable an overlay for a "Mouse Lock" indicator would be a nice QOL feature to those who would use it.

**Comment by tunis4** [comment]
no longer necessary
