### ISSUE TITLE
Mouse not locked in forced first person games

### ISSUE THREAD

**Issue by sunryze-git** [vinegarhq/sober#81]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It may be related to other mouse issues?

Workaround I have used is to run in gamescope, as fullscreen:
```gamescope -f -- org.vinegarhq.Sober```

Though there still is an issue where the mouse will move around within the window, but invisible. Workaround just prevents it from leaving the window.

https://github.com/user-attachments/assets/bd45aeee-886a-49ae-bbcf-5e8fdd3c06a5

**Comment by sunryze-git** [comment]
Seems to be somewhat related to #51

**Comment by 32bitx64bit** [comment]
Try pressing f1.

If that doesn't work, full screen probably will fix this.

**Comment by sunryze-git** [comment]
F1 didn't make a difference. As mentioned, fullscreen prevents it from exiting the window but the mouse is still not locked to the crosshair.

**Comment by tunis4** [comment]
please check if it has been fixed in the new update

**Comment by ManMar4254** [comment]
In Bloxburg, the unblocked mouse issue has been fixed in the new Sober version. In Greenville, the issue has not been fixed, and the same goes for BedWars.

### Bloxburg

https://github.com/user-attachments/assets/4c556b60-3ea4-4578-9007-bc97342eb35c

### Greenville

https://github.com/user-attachments/assets/69088855-6599-438c-849a-4a1ceffb88ae

### Bedwars

https://github.com/user-attachments/assets/54cc9ef4-8d61-40c0-a3aa-eee80d3ac0f9

**Comment by 32bitx64bit** [comment]
> please check if it has been fixed in the new update

Also still not fixed in "The red lake"
https://www.roblox.com/games/5766084948/SCP-The-Red-Lake-EVENT

**Comment by sunryze-git** [comment]
> please check if it has been fixed in the new update

Seems like now F1 does make a difference. by default its locked to center in games that force first person and now the mouse will stay in the window and at center. Though when pressing escape you have to press F1 to be able to move the mouse around the settings menu, seems to be a known issue though

**Comment by tunis4** [comment]
fixed
