### ISSUE TITLE
Invalid bundle

### ISSUE THREAD

**Issue by Laitinlok** [vinegarhq/sober#82]
Invalid bundle even though I downloaded the right apk file.

**Comment by Laitinlok** [comment]
Fixed

**Comment by KwiatekMiki** [comment]
> Fixed

can you at least share the solution with others who have the same problem?

**Comment by apprehensions** [comment]
You must unsure that your sober is up to date and the roblox version is the latest, x86_64.

**Comment by KwiatekMiki** [comment]
> You must unsure that your sober is up to date and the roblox version is the latest, x86_64.

it's up to date, roblox version is the latest, universal (arm64-v8a + armeabi-v7a + x86_64)

**Comment by Laitinlok** [comment]
> > Fixed
> 
> 
> 
> can you at least share the solution with others who have the same problem?

openSUSE specific issue with fusermount3 not executable when using their secure file permissions.
