### ISSUE TITLE
Give the chance to download sober from github

### ISSUE THREAD

**Issue by totolgueimer** [vinegarhq/sober#83]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

i don't like flatpaks, they're slow af and heavy for my 20GB root partition

### Describe the Solution you'd Like

maybe compiling it for x86_64 and sharing it on this git, or sharing the source code for compiling it ourselves

### Describe Alternatives you've considered

appimages would be great i think

**Comment by K4NK4N** [comment]
20GB root??? Gang what are you using :sob:

**Comment by K4NK4N** [comment]
They have made it clear it's closed-source, they likely won't change that for a while.

Also, uh; Flatpaks aren't normally slow or heavy. Don't really get that

20GB root partition is insane bro

**Comment by tunis4** [comment]
no

**Comment by K4NK4N** [comment]
> no

LMAOOO
