### ISSUE TITLE
How do I reconfigure Sober with a new apk?

### ISSUE THREAD

**Issue by pkhaxor** [vinegarhq/sober#84]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I got Sober set up with the wrong apk and I want to reconfigure / set it up again. I'm guessing I would have to do this in the future once Roblox comes out with a new apk aswell. A simple redownload doesn't bring up the setup screen. How do I access it and reconfigure the app?

**Comment by apprehensions** [comment]
`flatpak run org.vinegarhq.Sober --bootstrap`
