### ISSUE TITLE
Graphics Ultra garbage (solved)

### ISSUE THREAD

**Issue by AceVR12** [vinegarhq/sober#87]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Shadows, outlines, and pretty much all reflections/antialiasing is broken to a degree. my lighting and shadows are as blocky and filtered as ever.

**Comment by Vlad55432** [comment]
I think it's because of roblox's vulkan engine/renderer (whatever).
Like. it's meant for mobile users, but we use it in desktop, so maybe that's why

**Comment by AceVR12** [comment]
> I think it's because of roblox's vulkan engine/renderer (whatever). Like. it's meant for mobile users, but we use it in desktop, so maybe that's why
> 
> > antialiasing
> 
> you can set this fflag to override multi sample anti-aliasing, higher than 4 may cause graphical problems `"FIntDebugForceMSAASamples": 4`

How do i change fflags? New to sober.

**Comment by AceVR12** [comment]
> I think it's because of roblox's vulkan engine/renderer (whatever). Like. it's meant for mobile users, but we use it in desktop, so maybe that's why
> 
> > antialiasing
> 
> you can set this fflag to override multi sample anti-aliasing, higher than 4 may cause graphical problems `"FIntDebugForceMSAASamples": 4`

Nevermind, Found it.
