### ISSUE TITLE
Fallback to OpenGL when lacking Vulkan GPU support

### ISSUE THREAD

**Issue by Twig6943** [vinegarhq/sober#9]
not sure if sober does this automatically

**Comment by km9l** [comment]
sober does not support the opengles engine of roblox. reasons include:
- pain to get it work in wayland, actually we didnt get it to work at all
- maintenance burden of 2 different codepaths
- the opengles engine 2.0 got discontinued, and any opengl3.0+ hardware likely has core vulkan 1.0 (which is enough btw, intel sandy bridge-haswell vulkan support will work) (if there is any significant hardware contrary to this, i will reopen the issue)
- the opengles engine is really worse than vulkan visual wise
- we dont know whats happening in roblox internally, usage of opengles in android market share is really low, if they discontinue 3.0-3.1 our support will become pointless

so im concluding this issue by closing it

**Comment by km9l** [comment]
seems like sandy bridge igpus dont have vulkan, they just have opengles 3.1
if there appears to be a significant demand for it we may consider

**Comment by enigma9o7** [comment]
I have old nvidia with openGL 3.3 but no Vulkan.  I suspect this is why Sober doesn't work for me.

```
$ inxi -G
Graphics:
  Device-1: NVIDIA GT216M [GeForce GT 330M] driver: nvidia v: 340.108
   Display: x11 server: X.Org v: 1.20.8 driver: X: loaded: nvidia gpu: nvidia resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.4 drivers: nvidia platforms: x11
  API: OpenGL v: 3.3.0 vendor: nvidia v: 340.108 renderer: GeForce GT  330M/PCIe/SSE2
```

**Comment by km9l** [comment]
> I have old nvidia with openGL 3.3 but no Vulkan. I suspect this is why Sober doesn't work for me.
that is older than i would have anticipated.............................
can you send `glxinfo`? i need to know the opengl es api its capable of

**Comment by enigma9o7** [comment]
It's probably too old.  GLES 2.0 with nvidia-340, GLES 3.1 with nouveau.  
[glxinfo-nouveau.txt](https://github.com/user-attachments/files/16531827/glxinfo-nouveau.txt)
[glxinfo-nvidia340.txt](https://github.com/user-attachments/files/16531828/glxinfo-nvidia340.txt)

**Comment by km9l** [comment]
> It's probably too old. GLES 2.0 with nvidia-340, GLES 3.1 with nouveau. [glxinfo-nouveau.txt](https://github.com/user-attachments/files/16531827/glxinfo-nouveau.txt) [glxinfo-nvidia340.txt](https://github.com/user-attachments/files/16531828/glxinfo-nvidia340.txt)

only nouveau will work here. roblox discontinued the gles 2.0 engine a few months ago.
there is a opengles translator called ANGLE meant for desktop gl, but its meant for chromium's webgl support rather than end user usage so you cant set that up. (i think)
is nouveau's performance bearable?

**Comment by enigma9o7** [comment]
Performance is bearable, but I dunno how good (or bad) it'll be in roblox/sober!  Example [webgl aqaurium test](https://webglsamples.org/aquarium/aquarium.html) (default 500 fish/1024x1024 resolution) is around 40fps.

**Comment by hussainabidi1** [comment]
quadro nvs 4200m supports opengl 4.6 but not vulkan 
```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 1024 MB
    Currently available dedicated video memory: 742 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVS 4200M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 390.157
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 390.157
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.157
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by ColleagueRiley** [comment]
AMD ATI Radeon HD 6650M supports 4.5 but not vulkan.
