### ISSUE TITLE
sober crashing and dont load a roblox

### ISSUE THREAD

**Issue by BotTele2** [vinegarhq/sober#90]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[log @ JNIMain]: TelemetryProtocol::setProcessTimeOverride: 589
[log @ rbx.signalr_jni]: [JNI] OnLoad: ... Done
[log @ rbx.JNIRobloxSettings]: Setting default app policy file: /home/bazzite/.var/app/org.vinegarhq.Sober/data/sober/assets/content/guac/defaultConfigs/GuacDefaultPolicy-GlobalDist.json
[log @ Roblox]: 2024-08-11T07:08:42.303Z,1.303804,57c8c300,6 [FLog::AndroidGLView] nativeInitClientSettings
[log @ Roblox]: 2024-08-11T07:08:42.327Z,1.327948,57c8c300,6,Debug [DFLog::DebugSimpleJSON] readFromCdnStream: FixExtraParserMapEntries enabled
[log @ Roblox]: 2024-08-11T07:08:42.328Z,1.328038,57c8c300,6,Debug [DFLog::DebugSimpleJSON] readFromCdnStream: OptimizeFlagProcessing enabled
[log @ Roblox]: 2024-08-11T07:08:42.349Z,1.349673,57c8c300,6 [FLog::Output] LoadClientSettingsFromLocal: "{
    "DFFlagDisableDPIScale": true,
    "DFIntTaskSchedulerTargetFps": 0,
    "FFlagAdServiceEnabled": false,
    "FFlagDebugDisableTelemetryEphemeralCounter": true,
    "FFlagDebugDisableTelemetryEphemeralStat": true,
    "FFlagDebugDisableTelemetryEventIngest": true,
    "FFlagDebugDisableTelemetryPoint": true,
    "FFlagDebugDisableTelemetryV2Counter": true,
    "FFlagDebugDisableTelemetryV2Event": true,
    "FFlagDebugDisableTelemetryV2Stat": true,
    "FFlagFutureIsBrightPhase3Vulkan": true,
    "FFlagGameBasicSettingsFramerateCap5": true,
    "FFlagUserHandleChatHotKeyWithContextActionService": true
}
"
[log @ Roblox]: 2024-08-11T07:08:42.349Z,1.349725,57c8c300,6,Debug [DFLog::DebugSimpleJSON] readFromLocalStream: FixExtraParserMapEntries enabled
[log @ Roblox]: 2024-08-11T07:08:42.349Z,1.349735,57c8c300,6,Debug [DFLog::DebugSimpleJSON] readFromLocalStream: OptimizeFlagProcessing enabled
[log @ Roblox]: 2024-08-11T07:08:42.350Z,1.350832,57c8c300,6 [FLog::AndroidGLView] nativePostClientSettingsLoadedInitialization3
[log @ Roblox]: 2024-08-11T07:08:42.350Z,1.350928,57c8c300,6 [FLog::ClientRunInfo] RobloxGitHash: 0f51aad203ea89ce9a76583c558df7909ce1ed71
[log @ Roblox]: 2024-08-11T07:08:42.350Z,1.350940,57c8c300,6 [FLog::ClientRunInfo] The base url is https://www.roblox.com/
[log @ Roblox]: 2024-08-11T07:08:42.350Z,1.350947,57c8c300,6 [FLog::ClientRunInfo] The channel is production
[log @ rbx.AppBridgeV2]: nativeAppBridgeAppStart_original:
[log @ rbx.AppBridgeV2]: nativeAppBridgeV2Init:
[log @ Roblox]: 2024-08-11T07:08:42.410Z,1.410062,b7e006c0,6 [FLog::SingleSurfaceApp] initializeWithAppStarter
[log @ Roblox]: 2024-08-11T07:08:42.410Z,1.410100,b7e006c0,6 [FLog::SingleSurfaceApp] initializeSingleton
[log @ Roblox]: 2024-08-11T07:08:42.410Z,1.410252,b7e006c0,6 [FLog::Output] setAssetFolder /home/bazzite/.var/app/org.vinegarhq.Sober/data/sober/assets/content/
[log @ Roblox]: 2024-08-11T07:08:42.410Z,1.410458,b7e006c0,6 [FLog::Output] setExtraAssetFolder /var/home/bazzite/.var/app/org.vinegarhq.Sober/data/sober/assets/ExtraContent
[log @ Roblox]: 2024-08-11T07:08:42.410Z,1.410537,b7e006c0,6 [FLog::Output] Evaluating deferred inferred crashes
[log @ Roblox]: 2024-08-11T07:08:42.410Z,1.410782,b7e006c0,6 [FLog::SingleSurfaceApp] registerForForceOTAUpdateAvailableConnection stage = 0
[log @ Roblox]: 2024-08-11T07:08:42.411Z,1.411124,b7e006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Load configs for user key: app:8405001885291997395
[log @ Roblox]: 2024-08-11T07:08:42.412Z,1.412253,b7e006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:Native)
[log @ Roblox]: 2024-08-11T07:08:42.412Z,1.412284,b7e006c0,6 [FLog::SingleSurfaceApp] instantiate controllers
[log @ Roblox]: 2024-08-11T07:08:42.412Z,1.412296,b7e006c0,6 [FLog::SurfaceController] SurfaceController[_:1]::SurfaceController, count: 1
[log @ Roblox]: 2024-08-11T07:08:42.412Z,1.412420,b7e006c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:Native).
[log @ Roblox]: 2024-08-11T07:08:42.412Z,1.412439,b7e006c0,6 [FLog::SingleSurfaceApp] applyLocale
[log @ Roblox]: 2024-08-11T07:08:42.413Z,1.413377,b7e006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Retrieving patch
[log @ Roblox]: 2024-08-11T07:08:42.413Z,1.413404,b7e006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=5345954812, assetVersion=9443, maxAppVersion=636, localAssetURI=rbxasset://models/DataModelPatch/DataModelPatch.rbxm
[log @ Roblox]: 2024-08-11T07:08:42.413Z,1.413422,b7e006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : numAttempts=10
[log @ Roblox]: 2024-08-11T07:08:42.413Z,1.413489,b7e006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : contentId=rbxasset://models/DataModelPatch/DataModelPatch.rbxm
[log @ Roblox]: 2024-08-11T07:08:42.413Z,1.413503,b7e006c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : get patch from content provider for Model
[log @ Roblox]: 2024-08-11T07:08:42.413Z,1.413587,b7e006c0,6 [FLog::DataModelPatchConfigurer] deserializeAndVerifyPatch with blake3
[log @ rbx.AppBridgeV2]: nativeAppBridgeAppStart: StartupController finished starting: stage = 2, BTID = 0, upgradeStatus = 3.
[log @ Roblox]: 2024-08-11T07:08:42.795Z,1.795950,b7e006c0,6 [FLog::Output] Hello Earth
[log @ Roblox]: 2024-08-11T07:08:42.795Z,1.795983,b7e006c0,6 [FLog::Output] Hello from a friendly zombie.
[log @ Roblox]: 2024-08-11T07:08:42.796Z,1.796006,b7e006c0,6 [FLog::Output] Hello from a cozy home
[log @ Roblox]: 2024-08-11T07:08:43.079Z,2.079642,b7e006c0,6 [FLog::SingleSurfaceApp] setStage: (stage:InitializedLuaApp)
[log @ Roblox]: 2024-08-11T07:08:43.080Z,2.080576,19fff6c0,6 [FLog::Output] Info: DataModel Loading rbxasset://places/Mobile.rbxl
[log @ Roblox]: 2024-08-11T07:08:43.139Z,2.139456,19fff6c0,6 [FLog::DataModelPatchConfigurer] OTAPollingEnabled set to: false
[log @ Roblox]: 2024-08-11T07:08:43.167Z,2.167781,19fff6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config
[log @ Roblox]: 2024-08-11T07:08:43.327Z,2.327641,19fff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Load configs for user key: app:8405001885291997395
[log @ Roblox]: 2024-08-11T07:08:43.334Z,2.334516,19fff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Retrieving patch
[log @ Roblox]: 2024-08-11T07:08:43.334Z,2.334613,19fff6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=16639814581, assetVersion=685, maxAppVersion=636, localAssetURI=
[log @ Roblox]: 2024-08-11T07:08:43.382Z,2.382502,360006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
[log @ Roblox]: 2024-08-11T07:08:43.382Z,2.382566,360006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Update OTA config not deployed
[log @ Roblox]: 2024-08-11T07:08:43.436Z,2.436990,19fff6c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config
[log @ Roblox]: 2024-08-11T07:08:43.575Z,2.575234,360006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA succeeded: {"SchemaVersion":"1","CanaryUserIds":[],"CanaryPercentage":0}
[log @ Roblox]: 2024-08-11T07:08:43.575Z,2.575305,360006c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Update OTA config not deployed
[log @ Roblox]: 2024-08-11T07:08:43.576Z,2.576931,19fff6c0,6 [FLog::Warning] Warning: Unable to fetch completed survey ids from app storage  
[log @ rbx.AppBridgeV2]: nativeAppBridgeV2StartApp:
[log @ rbx.AppBridgeV2]: nativeAppBridgeV2StartApp: Created ANativeWindow 0x10 (ID:1)
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709145,b7e006c0,6 [FLog::SingleSurfaceApp] startLuaApp: (stage:InitializedLuaApp).
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709188,b7e006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: (stage:InitializedLuaApp).
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709200,b7e006c0,6 [FLog::SingleSurfaceApp] returnToLuaApp: ... disable videoRecorder.
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709223,b7e006c0,6 [FLog::SingleSurfaceApp] returnToLuaAppInternal: ... App has been initialized, returning from game.
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709248,b7e006c0,6 [FLog::SurfaceController] [_:1]::replaceDataModel: (stage:0, window = 0x10) [tid:0x7f7ea00500a0]
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709459,b7e006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_surface
[log @ Roblox]: 2024-08-11T07:08:43.709Z,2.709482,b7e006c0,6 [FLog::Graphics] Vulkan: Using extension: VK_KHR_android_surface
[log @ Roblox]: 2024-08-11T07:08:43.755Z,2.755122,b7e006c0,6 [FLog::Graphics] Vulkan: Device llvmpipe (LLVM 17.0.6, 256 bits) is emulated, skipping
[log @ Roblox]: 2024-08-11T07:08:43.755Z,2.755247,b7e006c0,6,Error [FLog::SurfaceController] Mode 6 failed: Unable to pick Vulkan device
[log @ Roblox]: 2024-08-11T07:08:43.755Z,2.755292,b7e006c0,6 [FLog::Graphics] Window size: 800x600

**Comment by Vlad55432** [comment]
> [FLog::Graphics] Vulkan: Device llvmpipe (LLVM 17.0.6, 256 bits) is emulated, skipping

maybe, just maybe you need to update your drivers for your linux distro

**Comment by tunis4** [comment]
fix your drivers
