### ISSUE TITLE
Locks cursor

### ISSUE THREAD

**Issue by HyperNfs** [vinegarhq/sober#91]
### Acknowledgement of checking existent issues

- [ ] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so my problem is when i play a game like arsenal/evade it locks the cursor so i cant vote map or go to the main menu thats the problem and when i press esc it still locked i hope you fix this soon, thank you

**Comment by tunis4** [comment]
press f1 to unlock

**Comment by Scubder** [comment]
I had the same problem with the esc menu, just press F1 and it should toggle cursor locking.
