### ISSUE TITLE
Sober Crashing

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [vinegarhq/sober#93]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[log @ JNIMain]: TelemetryProtocol::setProcessTimeOverride: 183
[log @ rbx.signalr_jni]: [JNI] OnLoad: ... Done
[log @ rbx.JNIRobloxSettings]: Setting default app policy file: /home/nychtaxd/.var/app/org.vinegarhq.Sober/data/sober/assets/content/guac/defaultConfigs/GuacDefaultPolicy-GlobalDist.json
[log @ Roblox]: 2024-08-11T16:30:31.422Z,0.422621,8008b300,6 [FLog::AndroidGLView] nativeInitClientSettings
[log @ Roblox]: 2024-08-11T16:30:31.426Z,0.426607,8008b300,6,Debug [DFLog::DebugSimpleJSON] readFromCdnStream: FixExtraParserMapEntries enabled
[log @ Roblox]: 2024-08-11T16:30:31.426Z,0.426634,8008b300,6,Debug [DFLog::DebugSimpleJSON] readFromCdnStream: OptimizeFlagProcessing enabled
[log @ Roblox]: 2024-08-11T16:30:31.436Z,0.436921,8008b300,6 [FLog::Output] LoadClientSettingsFromLocal: "{
    "DFFlagDisableDPIScale": true,
    "DFIntTaskSchedulerTargetFps": 0,
    "FFlagAdServiceEnabled": false,
    "FFlagDebugDisableTelemetryEphemeralCounter": true,
    "FFlagDebugDisableTelemetryEphemeralStat": true,
    "FFlagDebugDisableTelemetryEventIngest": true,
    "FFlagDebugDisableTelemetryPoint": true,
    "FFlagDebugDisableTelemetryV2Counter": true,
    "FFlagDebugDisableTelemetryV2Event": true,
    "FFlagDebugDisableTelemetryV2Stat": true,
    "FFlagFutureIsBrightPhase3Vulkan": true,
    "FFlagGameBasicSettingsFramerateCap5": true,
    "FFlagUserHandleChatHotKeyWithContextActionService": true
}
"
[log @ Roblox]: 2024-08-11T16:30:31.436Z,0.436974,8008b300,6,Debug [DFLog::DebugSimpleJSON] readFromLocalStream: FixExtraParserMapEntries enabled
[log @ Roblox]: 2024-08-11T16:30:31.436Z,0.436984,8008b300,6,Debug [DFLog::DebugSimpleJSON] readFromLocalStream: OptimizeFlagProcessing enabled
[log @ Roblox]: 2024-08-11T16:30:31.437Z,0.437680,8008b300,6 [FLog::AndroidGLView] nativePostClientSettingsLoadedInitialization3
[log @ Roblox]: 2024-08-11T16:30:31.437Z,0.437725,8008b300,6 [FLog::ClientRunInfo] RobloxGitHash: 0f51aad203ea89ce9a76583c558df7909ce1ed71
[log @ Roblox]: 2024-08-11T16:30:31.437Z,0.437736,8008b300,6 [FLog::ClientRunInfo] The base url is https://www.roblox.com/
[log @ Roblox]: 2024-08-11T16:30:31.437Z,0.437746,8008b300,6 [FLog::ClientRunInfo] The channel is production
[log @ rbx.AppBridgeV2]: nativeAppBridgeAppStart_original:
[log @ rbx.AppBridgeV2]: nativeAppBridgeV2Init:
[log @ Roblox]: 2024-08-11T16:30:31.441Z,0.441576,876006c0,6 [FLog::SingleSurfaceApp] initializeWithAppStarter
[log @ Roblox]: 2024-08-11T16:30:31.441Z,0.441596,876006c0,6 [FLog::SingleSurfaceApp] initializeSingleton
[log @ Roblox]: 2024-08-11T16:30:31.441Z,0.441676,876006c0,6 [FLog::Output] setAssetFolder /home/nychtaxd/.var/app/org.vinegarhq.Sober/data/sober/assets/content/
[log @ Roblox]: 2024-08-11T16:30:31.441Z,0.441806,876006c0,6 [FLog::Output] setExtraAssetFolder /home/nychtaxd/.var/app/org.vinegarhq.Sober/data/sober/assets/ExtraContent
[log @ Roblox]: 2024-08-11T16:30:31.441Z,0.441857,876006c0,6 [FLog::Output] Evaluating deferred inferred crashes
[log @ Roblox]: 2024-08-11T16:30:31.441Z,0.441983,876006c0,6 [FLog::SingleSurfaceApp] registerForForceOTAUpdateAvailableConnection stage = 0
[log @ Roblox]: 2024-08-11T16:30:31.442Z,0.442185,876006c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Load configs for user key: app:2941233491725903657
[log @ Roblox]: 2024-08-11T16:30:31.442Z,0.442618,876006c0,6 [FLog::Error] Error: collate_byname<char>::collate_byname failed to construct for 
[log @ Roblox]: 2024-08-11T16:30:31.442Z,0.442655,876006c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:None).
[log @ Roblox]: 2024-08-11T16:30:31.442Z,0.442666,876006c0,6 [FLog::SingleSurfaceApp] applyLocale

**Comment by tunis4** [comment]
`flatpak override --user --env=LC_ALL=en_US.UTF-8 org.vinegarhq.Sober`

**Comment by apprehensions** [comment]
Update the flatpak.

**Comment by Amgsdfyhadfgybi** [comment]
> Update the flatpak.

i did though

**Comment by apprehensions** [comment]
You have not. The bug fix sent above before my comment is now in the Flatpak itself, which solves your issue.
