### ISSUE TITLE
Missing Vulkan due to the amdgpu module not being in use

### ISSUE THREAD

**Issue by Animelove1105** [vinegarhq/sober#98]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Trying to run sober on my PC, but it won't really boot up, and will always show a "Couldn't find supported GPU" error.
I know it's probably obvious that the processor/GPU I'm running might be too old for this to run, but I want to figure out of there's anything else that's causing this (Like missing drivers needed to be installed or such), or it's just that my PC really isn't enough for it.

Logs (putting the file here instead because of formatting issues I can't figure out):
[2.637.0.730_20240812T204932Z_Player_82422_last.log](https://github.com/user-attachments/files/16591924/2.637.0.730_20240812T204932Z_Player_82422_last.log)

System info:
`System:
  Kernel: 5.15.0-117-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: HP product: 260-a129 v: N/A serial: <superuser required> Chassis: type: 4
    serial: <superuser required>
  Mobo: HP model: 81B3 v: 00 serial: <superuser required> UEFI: AMI v: F.17 date: 10/06/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard serial: <filter>
    charge: 55% (should be ignored) rechargeable: yes status: Discharging
CPU:
  Info: quad core model: AMD A8-7410 APU with AMD Radeon R5 Graphics bits: 64 type: MCP
    smt: <unsupported> arch: Puma rev: 1 cache: L1: 256 KiB L2: 2 MiB
  Speed (MHz): avg: 2409 high: 2436 min/max: 1000/2200 boost: enabled cores: 1: 2436 2: 2414
    3: 2394 4: 2395 bogomips: 17558
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Mullins [Radeon R4/R5 Graphics] vendor: Hewlett-Packard driver: radeon v: kernel
    ports: active: HDMI-A-1 empty: VGA-1 bus-ID: 00:01.0 chip-ID: 1002:9851 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: ati,radeon
    unloaded: fbdev,modesetting,vesa gpu: radeon display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1600x900 s-dpi: 96 s-size: 423x238mm (16.7x9.4") s-diag: 485mm (19.1")
  Monitor-1: HDMI-0 mapped: HDMI-A-1 model: VX200E serial: <filter> res: 1600x900 hz: 60 dpi: 92
    size: 443x249mm (17.4x9.8") diag: 508mm (20") modes: max: 1600x900 min: 720x400
  OpenGL: renderer: KABINI ( LLVM 15.0.7 DRM 2.50 5.15.0-117-generic)
    v: 4.5 Mesa 23.2.1-1ubuntu3.1~22.04.2 direct render: Yes
Audio:
  Device-1: AMD Kabini HDMI/DP Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel
    bus-ID: 00:01.1 chip-ID: 1002:9840 class-ID: 0403
  Device-2: AMD FCH Azalia vendor: Hewlett-Packard driver: snd_hda_intel v: kernel
    bus-ID: 00:14.2 chip-ID: 1022:780d class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-117-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Hewlett-Packard
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 01:00.0
    chip-ID: 10ec:8168 class-ID: 0200
  IF: enp1s0 state: down mac: <filter>
  Device-2: Realtek RTL8723BE PCIe Wireless Network Adapter vendor: Hewlett-Packard
    driver: rtl8723be v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: d000 bus-ID: 02:00.0
    chip-ID: 10ec:b723 class-ID: 0280
  IF: wlp2s0 state: up mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8 bus-ID: 2-1.2:4
    chip-ID: 0bda:b008 class-ID: e001 serial: <filter>
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 2.1 lmp-v: 4.0
    sub-v: 9f73 hci-v: 4.0 rev: e2f
Drives:
  Local Storage: total: 298.09 GiB used: 110.6 GiB (37.1%)
  ID-1: /dev/sda vendor: Seagate model: ST3320620AS size: 298.09 GiB speed: 1.5 Gb/s type: N/A
    serial: <filter> rev: E scheme: GPT
Partition:
  ID-1: / size: 291.86 GiB used: 110.6 GiB (37.9%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Full speed or root hub ports: 2 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002
    class-ID: 0900
  Hub-2: 1-1:2 info: Advanced Micro Devices Root Hub ports: 4 rev: 2.0 speed: 480 Mb/s
    power: 100mA chip-ID: 0438:7900 class-ID: 0900
  Device-1: 1-1.4:3 info: Logitech Unifying Receiver type: Keyboard,Mouse
    driver: logitech-djreceiver,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c534 class-ID: 0301
  Hub-3: 2-0:1 info: Full speed or root hub ports: 2 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002
    class-ID: 0900
  Hub-4: 2-1:2 info: Advanced Micro Devices Root Hub ports: 4 rev: 2.0 speed: 480 Mb/s
    power: 100mA chip-ID: 0438:7900 class-ID: 0900
  Device-1: 2-1.1:3 info: Realtek 3-in-1 (SD/SDHC/SDXC) Card Reader type: Mass Storage
    driver: ums-realtek interfaces: 1 rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 0bda:0153
    class-ID: 0806 serial: <filter>
  Device-2: 2-1.2:4 info: Realtek Bluetooth Radio type: Bluetooth driver: btusb interfaces: 2
    rev: 2.1 speed: 12 Mb/s power: 500mA chip-ID: 0bda:b008 class-ID: e001 serial: <filter>
  Hub-5: 3-0:1 info: Hi-speed hub with single TT ports: 2 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-6: 4-0:1 info: Super-speed hub ports: 2 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 61.9 C mobo: N/A gpu: radeon temp: 62.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 3075 apt: 3047 flatpak: 22 snap: 6
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
    1: deb https: //dl.winehq.org/wine-builds/ubuntu/ mint main
    2: deb https: //dl.winehq.org/wine-builds/ubuntu/ jammy main~
    3: deb https: //dl.winehq.org/wine-builds/ubuntu/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/alex-p-aegisub-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/alex-p-aegisub-jammy.gpg] https: //ppa.launchpadcontent.net/alex-p/aegisub/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/mono-official-stable.list
    1: deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https: //download.mono-project.com/repo/ubuntu stable-focal main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/protonvpn-stable.list
    1: deb [arch="all", signed-by=/usr/share/keyrings/protonvpn-stable-archive-keyring.gpg] https: //repo.protonvpn.com/debian stable main
  Active apt repos in: /etc/apt/sources.list.d/spotify.list
    1: deb http: //repository.spotify.com stable non-free
  Active apt repos in: /etc/apt/sources.list.d/waydroid.list
    1: deb [signed-by=/usr/share/keyrings/waydroid.gpg] https: //repo.waydro.id/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/yktooo-ppa-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/yktooo-ppa-jammy.gpg] https: //ppa.launchpadcontent.net/yktooo/ppa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/librewolf.sources
    1: deb [arch=amd64] https: //deb.librewolf.net focal main
  Active apt repos in: /etc/apt/sources.list.d/winehq-jammy.sources
    1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/ubuntu jammy main
Info:
  Processes: 251 Uptime: 32m wakeups: 2 Memory: 6.7 GiB used: 2.19 GiB (32.6%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 6.0.4 inxi: 3.3.13
`

### Roblox Experience link

N/A

**Comment by km9l** [comment]
send output of `lspci -k | grep -EA3 'VGA|3D|Display'`, that is hard to read...

**Comment by Animelove1105** [comment]
`00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 45)
	Subsystem: Hewlett-Packard Company Mullins [Radeon R4/R5 Graphics]
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu
`

**Comment by km9l** [comment]
> `00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 45)` `Subsystem: Hewlett-Packard Company Mullins [Radeon R4/R5 Graphics]` `Kernel driver in use: radeon` `Kernel modules: radeon, amdgpu`

you have to make the kernel prefer amdgpu
https://wiki.ubuntu.com/Kernel/KernelBootParameters#Permanently_Add_a_Kernel_Boot_Parameter
add `radeon.cik_support=0 amdgpu.cik_support=1` to your kernel boot parameters, instructions in the link

**Comment by Animelove1105** [comment]
It's working now!!! Thanks!!! :D

**Comment by km9l** [comment]
> > `00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 45)` `Subsystem: Hewlett-Packard Company Mullins [Radeon R4/R5 Graphics]` `Kernel driver in use: radeon` `Kernel modules: radeon, amdgpu`
> 
> you have to make the kernel prefer amdgpu https://wiki.ubuntu.com/Kernel/KernelBootParameters#Permanently_Add_a_Kernel_Boot_Parameter add `radeon.cik_support=0 amdgpu.cik_support=1` to your kernel boot parameters, instructions in the link

for future reference, GCN1 cards need `radeon.si_support=0 amdgpu.si_support=1` instead. you can use both if youre unsure about the generation of your card

> It's working now!!! Thanks!!! :D

np
