### ISSUE TITLE
Lua Sandbox is unplayable due to custom TextBoxes

### ISSUE THREAD

**Issue by ItsOktawian** [vinegarhq/sober#99]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The game uses custom TextBox input hooks, which are incompatible with sober, rendering the game unplayable.

There has been a thread on the VinegarHQ Discord started [here](https://canary.discord.com/channels/1069506340973707304/1270844246269759510), but no comments were made on it.

### Roblox Experience link

https://www.roblox.com/games/11510416200

**Comment by km9l** [comment]
this might be a potential android bug, we'll have to try with the actual android client later

**Comment by PanIntegralus** [comment]
Checked it now, the custom TextBox works on the Android client (typing anything, then pressing Enter), but not on Sober.

**Comment by apprehensions** [comment]
Related: #57

**Comment by PanIntegralus** [comment]
I found out that the TextBox "works" if you spam click and enter very fast, as shown here:

[Kooha-2024-08-13-09-19-25.webm](https://github.com/user-attachments/assets/2de083bd-ec67-4db1-b69a-7e11fcabdf15)

**Comment by MechaXYZ** [comment]
nah bro what the hell is this 💀

**Comment by ewd3v** [comment]
lsb doesn't use custom textboxes, they are normal ones. The only difference is that after FocusLost is fired lsb also checks if if InputBegan is fired with the Enter keycode (checks if it happens in the same frame). My guess is that InputBegan for some reason is fired before FocusLost, or not firing at all while typing in a textbox.
All of this is done to prevent bad actors from forcing inputs on others with :ReleaseFocus(true).

I've just now noticed that FocusLost also fires what InputObject caused FocusLost (and is nil when :ReleaseFocus(true) is called).

**Comment by ewd3v** [comment]
The reason why this works on the default Android client is because if ReturnPressedFromOnScreenKeyboard is fired I assume it wasn't forced.

**Comment by ewd3v** [comment]
(Pushed an update to the game to maybe fix this, so if it suddenly works now thats probably why.)

**Comment by km9l** [comment]
> The reason why this works on the default Android client is because if ReturnPressedFromOnScreenKeyboard is fired I assume it wasn't forced.

this is correct... we have stopped firing that while debugging something else about textboxes
anything that we should do?

**Comment by ewd3v** [comment]
As said in [#57](https://github.com/vinegarhq/sober/issues/57#issuecomment-2285804500), I believe the issue exists because UserInputService.InputBegan is not fired while typing in textboxes (I've tested if this is true as I do not use Sober).

**Comment by km9l** [comment]
> As said in [#57](https://github.com/vinegarhq/sober/issues/57#issuecomment-2285804500), I believe the issue exists because UserInputService.InputBegan is not fired while typing in textboxes (I've tested if this is true as I do not use Sober).

i actually do not have (rather forgot) knowledge about luau or any roblox api... is there any way i can check that?

i added the ReturnPressedFromOnScreenKeyboard fire back, no regression on anything else so far but im having twice output on the lua sandbox chatbox
the command textbox works fine but i think you recently changed it to work with sober, right?

**Comment by ewd3v** [comment]
> i actually do not have (rather forgot) knowledge about luau or any roblox api... is there any way i can check that?
https://create.roblox.com/docs/reference/engine/classes/UserInputService#InputBegan
> i added the ReturnPressedFromOnScreenKeyboard fire back
This api is supposed to fire when you press return on the on screen keyboard on Android.
> but i think you recently changed it to work with sober, right?
Yes I did.

As said I think the issue is that the InputBegan event is not fired when typing, but from what I remember this is a behavior that the Roblox Android client has.

**Comment by km9l** [comment]
> This api is supposed to fire when you press return on the on screen keyboard on Android.

im aware, but iirc android fired this for all keyboard return presses. probably not intentional

> Yes I did.

yea, seems like it works fine without any change.
in fact, the doubled chat input is gone after i take out the returnfromonscreenkeyboard press fire.
thanks for the help

**Comment by km9l** [comment]
ok... we figured why inputbegan event wasnt being sent in sober
issue solved without the need for devs to change their scripts
@ewd3v
